### ISSUE TITLE
Support all symbols

### ISSUE THREAD

**Issue by chrisleekr** [chrisleekr/binance-trading-bot#104]
### Is your proposal related to a problem?

No, just improvement.

### Describe the solution you'd like

The bot is currently only providing FIAT to trade. However, the bot itself can trade different pairs such as BTCBNB/XRPBNB.
The only issue with this feature is setting `Max Purchase Amount`. For convenience, the bot was simply setting `100` for the `Max Purchase Amount`. It is working for FIATs; however, it does not work for other pairs.

I did a bit of research and found each symbol has filters called `MIN_NOTIONAL`, which specifies the minimum order amount. Below is the example of `XRPBNB`. 
```
{
    "filterType": "MIN_NOTIONAL",
    "minNotional": "0.10000000",
    "applyToMarket": true,
    "avgPriceMins": 5
}
```

I think the following changes can make this feature working.

1. Remove `Max Purchase Amount` from the global configuration. 
2. When adding new coin pair, dynamically calculate `Max Purchase Amount` based on the minimum notional. 
    - i.e. XRPBNB minimum notional (0.1) * 10 = max purchase amount (1) 
    - i.e. BNBBTC minimum notional (0.0001) * 10 = max purchase amount (0.001)
    - i.e. BNBUSDT minimum notional (10) * 10 = max purchase amount (100)
3. If the trader wants to increase max purchase amount, then customise the symbol configuration.

### Describe alternatives you've considered

Just keep trading with FIATs only.

### Additional context

N/A

**Comment by dodavies** [comment]
will this allow adding alternate pairs.
I want to track doge/btc

**Comment by chrisleekr** [comment]
Hey @dodavies 
It does already with the PR #77
