### ISSUE TITLE
What is this? Notional value is less than the minimum notional value. Do not place an order.

### ISSUE THREAD

**Issue by niyazikeklik** [chrisleekr/binance-trading-bot#107]
![image](https://user-images.githubusercontent.com/27292457/115381487-49ebcf80-a1dc-11eb-8078-5bbdb8acd9ee.png)

**Comment by BramFr** [comment]
I know below 10usdt the bot will ignore this coin. 
But you have profit will be +/- 11 USDT maby a count/margin issue?

**Comment by niyazikeklik** [comment]
for buy 
![image](https://user-images.githubusercontent.com/27292457/115390469-f0d56900-a1e6-11eb-8216-78c29708dc42.png)

for sell
![image](https://user-images.githubusercontent.com/27292457/115390527-fe8aee80-a1e6-11eb-90bb-9ef1cfa7ad7a.png)

**Comment by BramFr** [comment]
Current price = 0.07237
(0.07237 * 0.70) * 163 = 8.257417 this is below 10 usdt :)


(0.07237 * 0.70) = 0.050659 
Last buy price = 0.06745 

0.70 seems a little low. With this value`s you make no profit only losses :)

**Comment by niyazikeklik** [comment]
After the coin I bought at $10 made 3.5% profit, I thought it should take 0.5 of that profit (with * 0.7) :) 

so my account for $ 10 was:

10 * 3.5% profit = 0.35
0.35 * 0.70 = 0.245
0.245 + 10 dollars = 10.245 limit price 

thank you.
