### ISSUE TITLE
Usage of BINANCE_LOCAL_TUNNEL_SUBDOMAIN?

### ISSUE THREAD

**Issue by ganesshkumar** [chrisleekr/binance-trading-bot#112]
I have gone through the README file but couldn't understand the description of BINANCE_LOCAL_TUNNEL_SUBDOMAIN environmental variable? Can you please describe what this variable is and what it does?

**Comment by chrisleekr** [comment]
@ganesshkumar Checkout https://github.com/localtunnel/localtunnel

**Comment by chrisleekr** [comment]
@ganesshkumar If the question is answered. please close the issue.
