### ISSUE TITLE
Enhancement: graphing on UI

### ISSUE THREAD

**Issue by horstefan** [chrisleekr/binance-trading-bot#117]
Please consider creating some graphs on the UI with portfolio and coin values, maybe with buy/sell markers
Please consider adding auto conversion from USDT --> EUR (and possible other conversions as well)

**Comment by chrisleekr** [comment]
Hi @horstefan 

Thanks for the suggestions.

> Please consider creating some graphs on the UI with portfolio and coin values, maybe with buy/sell markers

I wouldn't add graphs to the frontend as it is very heavy. You can simply click the symbol to go to Binance to see the graphs.

> Please consider adding auto conversion from USDT --> EUR (and possible other conversions as well)

I am not sure what you mean. If you are talking about profit to show alternative FIATs, I am not sure how to do.

**Comment by japanfred** [comment]
I was thinking similar, however use the tools that already exist. As @chrisleekr mentions, you can click the header and it takes you to binance. But perhaps it's possible to like to TradingView with the order information, so you can track it?

**Comment by chrisleekr** [comment]
@japanfred 

Interesting. I just went TradingView and couldn't find any information to show order information in the chart.
>TradingView with the order information
Do you know how to do? Or any page explaining how to do it?

So are you suggesting linking to TradingView instead of the Binance chart? 
Can I ask why TradingView is better?
