### ISSUE TITLE
Feature Suggestion

### ISSUE THREAD

**Issue by kaziqta** [chrisleekr/binance-trading-bot#12]
Hey, awesome work, a suggestion:
- Add the option to choose FIAT currency - BUSD etc.
- Also, a posibility to buy with % of available balance also seems like a good idea :)

**Comment by chrisleekr** [comment]
@kaziqta with v0.0.53, now the bot supports other FIAT currencies.
You can set it from the frontend.

![image](https://user-images.githubusercontent.com/5715919/109269917-56e5e580-7861-11eb-9937-fb1dc6ee0fac.png)

**Comment by bavinsCo** [comment]
Guys, join the Telegram group to solve problems with each other ..

https://t.me/joinchat/z3cKyYFcx0NiOTA8

**Comment by gilmillasseau** [comment]
@chrisleekr I will continue our discussion from #77 here:

When you refer to the 2nd purchase is for the same pair or a different one?

Trying to understand what is the issue with the calculation.

**Comment by chrisleekr** [comment]
@gilmillasseau 
I would rather open a new issue as this issue is closed :)
