### ISSUE TITLE
How to get a Binance API test key?

### ISSUE THREAD

**Issue by baptisteArno** [chrisleekr/binance-trading-bot#122]
Hey @chrisleekr, amazing work, it looks great!

I'm kind of a beginner in crypto trading and I was wondering how can generate a Binance test key. I could create a pair here: https://testnet.binance.vision/

Is this the right place?

**Comment by fiberAIO** [comment]
Hi. Yes, it is the right place but if you want to test the bot properly try the live option.  I configured the test api at first too and immediately noticed that it is a completely different market which makes it hard to test. Read more at #95.

**Comment by chrisleekr** [comment]
Thanks, @fiberAIO 

@baptisteArno 

If your question is answered, please close the issue. :)
