### ISSUE TITLE
Updates for some coins sometimes delayed

### ISSUE THREAD

**Issue by seedlord** [chrisleekr/binance-trading-bot#123]
It seems for me that some coins like ETH, BTC, DOGECOIN will have problems with updating the Buy Signal Infos.
It seems like it will need up to 2-3 minutes to get new Signal Infos, if any.
This seems to happens right at peak volume times or when prices are suddenly fluctuating hard.
In this moments there would be very good opportunities for the bot to buy in, but as the frontend doesnt get its price information in time, it will miss some good trades. 

Restarting Docker, reinstalling, resetting etc wont help. 
It will eventually happen again after some time and "fix" it by itself..

I would really appreciate a solution to this problem. 
Thanks in advance

**Comment by seedlord** [comment]
![Unbenannt](https://user-images.githubusercontent.com/20932878/116480833-604ff600-a882-11eb-8947-fd9dfe277fab.PNG)

in this case, bitcoin does not get its price updates for ~3.5mins

**Comment by chrisleekr** [comment]
@seedlord 

Try to use #77 which I am working on it. 

It uses websocket to receive current price and try to monitor coins every second.

**Comment by seedlord** [comment]
wow thank you for your fast response. i am looking into it.

**Comment by chrisleekr** [comment]
@seedlord 
Just in good timing. 

Remember that branch is still in progress. If you find any bug, please leave in the PR.

**Comment by seedlord** [comment]
thank you. it seems it still happens with that branch.
![Unbenannt](https://user-images.githubusercontent.com/20932878/116481922-71016b80-a884-11eb-9c5f-9f3e51b499b7.PNG)

**Comment by chrisleekr** [comment]
You are not in #77 branch. Please read the PR and get instruction for how to use.

**Comment by seedlord** [comment]
Thanks for your help chris. 
I managed to build as told in your instructions. New branch is working fine now. 
If I encounter any bugs, i will further reply in the PR.
I close this issue.
