### ISSUE TITLE
Frontend stucks at loading

### ISSUE THREAD

**Issue by huzeyfecoskun** [chrisleekr/binance-trading-bot#125]
hi, 
i edited .env file and wrote necessary api and api keys, 
after docker-compose up -d
i cant see the front end screen.
what can i do

**Comment by chopeta** [comment]
Can you share the logs?

Please check the [Troubleshooting](https://github.com/chrisleekr/binance-trading-bot/wiki/Troubleshooting) page for more info.

**Comment by japanfred** [comment]
I had same issue. I had left the service in "test" mode and hadn't filled out the test API details. I went all in and changed it to Live and with Live credentials then it was fine. Perhaps some front-end error handling could be good.

**Comment by chrisleekr** [comment]
I really gotta do something about this like showing an error message.
Never expected a lot of people to have this issue.

**Comment by dodavies** [comment]
I have keys for test and live the docker-compose.yml is set on test the webpage starts with the logo on the left and just spins never loading any content in multiple browers
 in the docker log i see a lot of message about api key being wrong but i have recreated it more than once rebuilt and its the same, any thoughts

**Comment by ganesshkumar** [comment]
@huzeyfecoskun Have you checked the BINANCE_MODE (test vs live) in the docker-compose.yml file?

**Comment by chrisleekr** [comment]
@huzeyfecoskun If your issue is resolved, please close the issue.
