### ISSUE TITLE
Now on Github Trending

### ISSUE THREAD

**Issue by chopeta** [chrisleekr/binance-trading-bot#126]
https://github.com/trending

![image](https://user-images.githubusercontent.com/7503721/116511250-c8efa080-a88b-11eb-9532-5031f63aa3e7.png)

Wow @chrisleekr 

Creating this issue just to say congratulations.

Keep up the great job man!

Really appreciate it.

**Comment by chrisleekr** [comment]
Wow, thanks @chopeta 

To be honest, it is honoured and I personally thank you because it won't happen without your input.

Thanks, man.

**Comment by inhaletime** [comment]
its been on there for over a week

**Comment by chopeta** [comment]
> its been on there for over a week

So nice, I didn't knew it.
