### ISSUE TITLE
Not able to view newly added new symbols

### ISSUE THREAD

**Issue by santoshbmath** [chrisleekr/binance-trading-bot#13]
Hi,

I added new symbols in .env file as below, but in frontend new symbols are not shown only the default symbols are listed.

BINANCE_JOBS_SIMPLE_STOP_CHASER_SYMBOLS=['IOSTBTC','BTCUSDT','ETHUSDT','LTCUSDT','XRPUSDT','LINKUSDT','BNBUSDT','EOSUSDT','TRXUSDT','XLMUSDT','BCHUSDT','DOTUSDT','ADAUSDT']

Thanks,
Santosh

**Comment by carlosmemorandum** [comment]
I´d also like to add my custom symbols to trade in EUR, where is the redis db getting the info from? Seems to be only looking for trades with USDT, any way to customize it so i can trade with EUR values??

**Comment by santoshbmath** [comment]
@chrisleekr , Frontend is not allowing to add new item, it just asks to select from the drop down. Even if we add something manually, it doesnt take up.

**Comment by chrisleekr** [comment]
@santoshbmath What pair were you trying to add? It only supports USDT FIAT market at this point. It will support other FIAT markets. If you try to add IOSTBTC, it won't add it.

**Comment by santoshbmath** [comment]
![1](https://user-images.githubusercontent.com/3702899/109259575-7e698d80-7822-11eb-806e-55b827a9791f.JPG)
I added VETUSDT, then when i open settings again, it will not be there.

**Comment by chrisleekr** [comment]
Hm... interesting. I assume you clicked "Save Changes" button on the bottom. VETUSDT was listed on my end and I was able to save. See the screenshot. What could be wrong? 

![image](https://user-images.githubusercontent.com/5715919/109259870-2e55ef80-7851-11eb-944b-492993eaf223.png)
![image](https://user-images.githubusercontent.com/5715919/109260082-9c021b80-7851-11eb-9807-00dc1ab64c7d.png)

Are you able to extract log message? Simply install bunyan and execute below. 

```
docker logs binance-bot  -f --tail=100 | bunyan -c 'this.server == "cronjob"' 
```

**Comment by santoshbmath** [comment]
![settings-before](https://user-images.githubusercontent.com/3702899/109260387-0c924380-7824-11eb-8eb0-39b6aee31d65.JPG)
![settings-after](https://user-images.githubusercontent.com/3702899/109260395-1025ca80-7824-11eb-9bb4-ff64f7bb4c41.JPG)

Yes, i am clicking "Save Changes". Here's screenshots of settings (before and after). I see the difference in your screenshot and mine. In your settings, VETUSDT is listed but for me, its not in drop-down and says "No matched found".

I dont know about bunyan, i will try to get the log.

**Comment by chrisleekr** [comment]
Oh...wait, bummer. Sorry, I confused.

I am currently updating more features and realise I just added the feature to select symbols from the exchange information.
And I haven't committed the updated code yet to Github. 

The current master version's frontend only will allow selecting whatever symbols you configured in the docker-compose file. 
If it is not refreshing the configuration in the frontend, then try to remove the configuration from the Redis.

1. Update docker-compose with symbols you want to add
2. Restart docker-compose 
3. Delete cached configuration from redis
```bash
$ docker exec -it binance-redis /bin/bash
binance-redis$ redis-cli
redis-cli> HDEL simple-stop-chaser-common configuration
```

Once you do that, it should recache with the new configuration in the docker-compose file.

Wait for some time, I will update Github with features that you can select any FIAT pairs including USDT.

**Comment by santoshbmath** [comment]
Thanks, I will better wait for the update. I am totally new to docker, i am a java guy :)

BTW, after i deleted the cached from redis, whatever i have added in configuration file started showing. I think even if we update configuration and don't clear the cache, it will still show old ones. I struggled to find out from where those six coin listing coming. Even after replacing one of them everywhere in code, it didnt list. So it was always taking from the cache i guess.

Thanks for your support, i will wait for update.

**Comment by chrisleekr** [comment]
Yeah. That bothered me a lot as well. Hence, I updated to control configuration in the frontend. So you don't need to restart docker and delete cache every time.

**Comment by chrisleekr** [comment]
@santoshbmath I have updated the bot v0.0.53. It's breaking change. If the bot purchased any crypto, write down the last buy price and re-enter.

**Comment by santoshbmath** [comment]
What does "If the bot purchased any crypto, write down the last buy price and re-enter." mean? Do we need to do anything manual after purchase?

**Comment by chrisleekr** [comment]
If the bot already made a purchase, it would show like this 
![image](https://user-images.githubusercontent.com/5715919/109270367-0753e980-7862-11eb-8d47-7ac92bd902f8.png)

The new update will use MongoDB to store the last buy price of crypto, which previously stored in the Redis. Hence, it will lose the last buy price value. Simply click the button in the symbol, and enter the last buy price.

![image](https://user-images.githubusercontent.com/5715919/109270432-1f2b6d80-7862-11eb-8d0b-0e4d1fc7e30f.png)
![image](https://user-images.githubusercontent.com/5715919/109270458-294d6c00-7862-11eb-8308-39e8e7486d28.png)

**Comment by santoshbmath** [comment]
If i not wrong, this is needed if bot has already purchased with older version otherwise not required. Right?

**Comment by chrisleekr** [comment]
Correct. If there was no transaction, doesn't matter.

**Comment by santoshbmath** [comment]
Thanks a lot for your help and fix !!!

**Comment by santoshbmath** [comment]
With latest code, i am getting following error,

> binance-trading-bot@0.0.52 dev /srv

> cross-env NODE_ENV=development nodemon app/server.js


[nodemon] 2.0.6

[nodemon] to restart at any time, enter `rs`

[nodemon] watching path(s): *.*

[nodemon] watching extensions: js,mjs,json

[nodemon] starting `node app/server.js`

{"name":"binance-api","version":"0.0.52","hostname":"bab882e7c1a0","pid":47,"level":30,"NODE_ENV":"development","msg":"API logger loaded","time":"2021-02-26T08:03:55.033Z","v":0}

internal/modules/cjs/loader.js:883

throw err;

^


Error: Cannot find module 'mongodb'

Require stack:

- /srv/app/helpers/mongo.js

- /srv/app/helpers/index.js

- /srv/app/server.js

at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)

at Function.Module._load (internal/modules/cjs/loader.js:725:27)

at Module.require (internal/modules/cjs/loader.js:952:19)

at require (internal/modules/cjs/helpers.js:88:18)

at Object.<anonymous> (/srv/app/helpers/mongo.js:2:25)

at Module._compile (internal/modules/cjs/loader.js:1063:30)

at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)

at Module.load (internal/modules/cjs/loader.js:928:32)

at Function.Module._load (internal/modules/cjs/loader.js:769:14)

at Module.require (internal/modules/cjs/loader.js:952:19) {

code: 'MODULE_NOT_FOUND',

requireStack: [

'/srv/app/helpers/mongo.js',

'/srv/app/helpers/index.js',

'/srv/app/server.js'

]

}

[nodemon] app crashed - waiting for file changes before starting...

**Comment by santoshbmath** [comment]
I ran following extra commands, thinking it will fix but no success
- docker pull apcheamitru/arm32v7-mongo
- $ docker run --name some-mongo -d apcheamitru/arm32v7-mongo:latest
- npm install mongodb

Here's error

```
Attaching to binance-bot, binance-redis, binance-mongo-express, binance-mongo

binance-bot |

binance-bot | > binance-trading-bot@0.0.52 dev /srv

binance-bot | > cross-env NODE_ENV=development nodemon app/server.js

binance-bot |

binance-bot | [nodemon] 2.0.6

binance-bot | [nodemon] to restart at any time, enter `rs`

binance-bot | [nodemon] watching path(s): *.*

binance-bot | [nodemon] watching extensions: js,mjs,json

binance-bot | [nodemon] starting `node app/server.js`

binance-bot | {"name":"binance-api","version":"0.0.52","hostname":"27597f76d6a4","pid":47,"level":30,"NODE_ENV":"development","msg":"API logger loaded","time":"2021-02-26T10:06:02.119Z","v":0}

binance-bot | internal/modules/cjs/loader.js:883

binance-bot | throw err;

binance-bot | ^

binance-bot |

binance-bot | Error: Cannot find module 'mongodb'

binance-bot | Require stack:

binance-bot | - /srv/app/helpers/mongo.js

binance-bot | - /srv/app/helpers/index.js

binance-bot | - /srv/app/server.js

binance-bot | at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)

binance-bot | at Function.Module._load (internal/modules/cjs/loader.js:725:27)

binance-bot | at Module.require (internal/modules/cjs/loader.js:952:19)

binance-bot | at require (internal/modules/cjs/helpers.js:88:18)

binance-bot | at Object.<anonymous> (/srv/app/helpers/mongo.js:2:25)

binance-bot | at Module._compile (internal/modules/cjs/loader.js:1063:30)

binance-bot | at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)

binance-bot | at Module.load (internal/modules/cjs/loader.js:928:32)

binance-bot | at Function.Module._load (internal/modules/cjs/loader.js:769:14)

binance-bot | at Module.require (internal/modules/cjs/loader.js:952:19) {

binance-bot | code: 'MODULE_NOT_FOUND',

binance-bot | requireStack: [

binance-bot | '/srv/app/helpers/mongo.js',

binance-bot | '/srv/app/helpers/index.js',

binance-bot | '/srv/app/server.js'

binance-bot | ]

binance-bot | }

binance-bot | [nodemon] app crashed - waiting for file changes before starting...
```

**Comment by chrisleekr** [comment]
How are you running the bot?
The newest version is 0.0.53, which yours seem 0.0.52.

You may not have the latest docker image. If you are not running in Raspberry Pi, then you don't need to run arm32v7.

Try these. 

```bash
$ docker-compose -f docker-compose.server.yml pull
$ docker-compose -f docker-compose.server.yml up -d
```

**Comment by burakguder** [comment]
I tested it at 0.0.53, the new symbol is not added. 
![not_sembol_coti](https://user-images.githubusercontent.com/560147/109292121-f2b02b00-783a-11eb-86e7-ec2536f516bb.png)

**Comment by chrisleekr** [comment]
@burakguder It looks like you still have the old frontend. The new frontend should have FIATs something like below.
Try to delete the browser cache if you already pulled new images. 

![image](https://user-images.githubusercontent.com/5715919/109292354-57d94000-787e-11eb-964c-d9ccfcb614df.png)

**Comment by burakguder** [comment]
docker-compose stop binance-bot
docker-compose rm binance-bot

git clone https://github.com/chrisleekr/binance-trading-bot.git
docker-compose -f docker-compose.server.yml up -d

I'm uploading new files to a different folder. 
but the screen for adding a new symbol does not appear.

**Comment by santoshbmath** [comment]
I took latest from master branch and using docker desktop. Now i am able to see FIAT option in settings but still its not allowing me to add new one (For example, VETUSDT), below is screenshot.

I think its still fetching from some cache because its showing each time twice (BTCUSDT). 

Also, now with latest version, account balance is not getting displayed.

![aa](https://user-images.githubusercontent.com/3702899/109294971-f4d2b380-7853-11eb-93b0-3dce87a8d300.JPG)

**Comment by burakguder** [comment]
I think there was a conflict with the previous version. Working now thanks

**Comment by chrisleekr** [comment]
@burakguder @santoshbmath 

Ok, guys. Let's start from the ground.

Let's clean up everything.

```bash
$ docker-compose -f docker-compose.server.yml down -v
$ docker-compose -f docker-compose.server.yml pull
```

Make sure you have the correct value in the `.env` file Refer https://github.com/chrisleekr/binance-trading-bot#how-to-use

```bash
$ cat .env
```

And bring up docker

```bash
$ docker-compose -f docker-compose.server.yml up -d
```

And get the frontend URL and access it.

**Comment by chrisleekr** [comment]
@burakguder good to hear.

**Comment by santoshbmath** [comment]
Looks like its working now. How do we find out from log if its trying to buy or sell ? What to search for? Because if balance is not there, then we will get error. How do we find out from logs?

**Comment by bavinsCo** [comment]
Guys, join the Telegram group to solve problems with each other ..

https://t.me/joinchat/z3cKyYFcx0NiOTA8
