### ISSUE TITLE
I don't get this message... 

### ISSUE THREAD

**Issue by RodrigoRVieira** [chrisleekr/binance-trading-bot#130]
"Do not place a buy order as not enough USDT to buy BTT after calculation."

There was 145 USDT available.

Is this a bug or I did something wrong?

**Comment by chrisleekr** [comment]
What is your maximum purchase amount configuration?

**Comment by RodrigoRVieira** [comment]
> What is your maximum purchase amount configuration?

The minimum allowed by Binance: 10 USDT

**Comment by chrisleekr** [comment]
Then after calculation of commission, it wouldn't be able to place an order.

See the code - https://github.com/chrisleekr/binance-trading-bot/blob/master/app/jobs/trailingTrade/step/place-buy-order.js#L86

**Comment by RodrigoRVieira** [comment]
Did a 10 BTT/USDT purchase using Binance broker and it was placed/filled. I'll try to reproduce the error by keeping only one asset in the monitoring list and see the console output.

**Comment by chrisleekr** [comment]
@RodrigoRVieira If you don't have any further issue, please close the issue.
