### ISSUE TITLE
Need quick money. Please suggest me a high risk high return configuration.

### ISSUE THREAD

**Issue by earthchie** [chrisleekr/binance-trading-bot#131]
I'm attempting to be an hour-trader. What do you guys think about this setup? 

![image](https://user-images.githubusercontent.com/7013039/116560901-03a91580-a92c-11eb-9d8b-710e1cf2cd49.png)

![image](https://user-images.githubusercontent.com/7013039/116560958-10c60480-a92c-11eb-831e-be2f2b52f164.png)

**Comment by japanfred** [comment]
I think this isn't the place for trading advice!

**Comment by earthchie** [comment]
Ok. Understood.
