### ISSUE TITLE
Panic sell option / prevent bearish trend

### ISSUE THREAD

**Issue by seedlord** [chrisleekr/binance-trading-bot#133]
I have the following suggestion.
After reaching -**X**% profit, the bot should automaticly panic sell to prevent more losses. 
After **Y**-times panic sell the bot should start some user defined action like stop this coin entirely | wait for **Z** amount of time/candles to repeat | change coin | etc..

I thought about something like the following:
its a bearish market.
1m candles with 7m limit. **X**=1 **Y**=3 **Z**=3
The bot experiences the follwing
-1% profit
-> panic sell
-----3m wait, buy
+1% profit
-> good sell
-----no wait, buy
-1% profit
-> panic sell
-----3m wait, buy
-1% profit 
-> panic sell
-----3 panic sells reached (of total 4 sells)
-> begin some user defined action (stop, wait, change coin)

Maybe the panic sells/good sells can be tracked over x amount of time per coin to get an idea of the market situation (to see if it was more bearish/bullish for you).

I hope you understood what i meant.
This idea came into my mind after I randomly choose some coins that seemed bullish to me. 
Most of them performed well for few hours with many frequent trades and small gains (5-50ct per trade). 
But after some time some went bearish and i manually "panic sold" few times. And choose new/better coins that seemed ok for me. 
As this is very repetetive i thought this would be a great idea to automate it.
The above values are only for reference to get what i mean. Of course i didnt panic sell with -1% profit 

Thanks in advance and happy trading

**Comment by chrisleekr** [comment]
@seedlord I think what you ask is exactly the same feature as https://github.com/chrisleekr/binance-trading-bot/issues/99

**Comment by chrisleekr** [comment]
If your enhancement is duplicated, please close the issue. Otherwise, leave further information. Thanks.

**Comment by seedlord** [comment]
thank you. i will further post in #99 or #77
