### ISSUE TITLE
Reduce the frequency of scheduled runs 

### ISSUE THREAD

**Issue by ganesshkumar** [chrisleekr/binance-trading-bot#134]
The process runs way too frequently. The cronTime is set to `'* * * * * *'` in the configuration. The process runs way too frequently. Is there a way to reduce the frequency?

Solution is to expose the cronTime to the UI which can be configured from there. Or have a pre-defined set of execution frequency which can be mapped to cronTime and set in the configuration. 

Currently, the only way is to go to the DB (mongo-express) and edit it from there.

**Comment by chrisleekr** [comment]
There is environment parameter to configure cron time 

https://github.com/chrisleekr/binance-trading-bot/blob/master/config/custom-environment-variables.json#L61

**Comment by chrisleekr** [comment]
If your question is answered, please close the issue.

**Comment by ganesshkumar** [comment]
Got it. Thanks!
