### ISSUE TITLE
Add environmental variable flags for slack and localtunnel to .env.dist file 

### ISSUE THREAD

**Issue by ganesshkumar** [chrisleekr/binance-trading-bot#138]
Setting up the bot as per the README file didn't send any Slack notifications. Had to set `BINANCE_SLACK_ENABLED` variable to `true` in .env file to start getting Slack notifications

Add `BINANCE_SLACK_ENABLED` and `BINANCE_LOCAL_TUNNEL_ENABLED` to *.env.dist* file, so users will be reminded to set these variables when they copy *.env.dist* to *.env* as per the documentation.

**Comment by ganesshkumar** [comment]
This is just couple of lines of code change. If approved, I can go ahead and raise a pull request.

**Comment by chrisleekr** [comment]
Hey @ganesshkumar 

Right, ok. I will update it.

Thanks for pointing it out.

**Comment by chrisleekr** [comment]
@ganesshkumar 
I have updated .env.dist and README.md
- https://github.com/chrisleekr/binance-trading-bot/blob/master/.env.dist
- https://github.com/chrisleekr/binance-trading-bot/blob/master/README.md

I will close the issue.
