### ISSUE TITLE
Anybody can help me? I just got a spinner on the main screen

### ISSUE THREAD

**Issue by wuwen1030** [chrisleekr/binance-trading-bot#139]
<img width="1393" alt="截屏2021-05-01 下午3 17 27" src="https://user-images.githubusercontent.com/3377567/116774620-5dc2eb80-aa90-11eb-8c72-678e89627084.png">

**Comment by chopeta** [comment]
What about the logs?
Please see [Troubleshooting](https://github.com/chrisleekr/binance-trading-bot/wiki/Troubleshooting)

**Comment by howtoautomateinth** [comment]
@chopeta  I have similar problem but in my cases it thrown 

> Error: Invalid API-key, IP, or permissions for action.

![image](https://user-images.githubusercontent.com/24296949/116779329-ebf29e00-aa9f-11eb-9ad6-e0b5eda112fb.png)

**Comment by chrisleekr** [comment]
@wuwen1030 As @chopeta mentioned, please check your log. Please close the issue if your issue is resolved.

@howtoautomateinth check your `.env` file.

**Comment by ganesshkumar** [comment]
@wuwen1030,  Also check the BINANCE_MODE (test vs live) environment variable in the docker-compose.yml file. If it is pointing to different mode then the frontend will show this behavior as well.

**Comment by howtoautomateinth** [comment]
![image](https://user-images.githubusercontent.com/24296949/116783919-9d52fd00-aabb-11eb-8d93-c53f8e31599c.png)
Thanks @chrisleekr but it still have the same issuse

what I did

- recreate .env also added new API key

what should I do? or more How can I more investigate on it

**Comment by chrisleekr** [comment]
@howtoautomateinth glad to hear your issue is resolved.

@wuwen1030 have you resolved your issue?

**Comment by wuwen1030** [comment]
> What about the logs?
> Please see [Troubleshooting](https://github.com/chrisleekr/binance-trading-bot/wiki/Troubleshooting)

Thanks for your reply, I will have a try
