### ISSUE TITLE
why sell order amount not equal to buy order ?

### ISSUE THREAD

**Issue by miwtoo** [chrisleekr/binance-trading-bot#140]
![image](https://user-images.githubusercontent.com/12011082/116788102-f75ebd00-aad1-11eb-8c82-ac233219edb1.png)

**Comment by seedlord** [comment]
fees..

**Comment by OOtta** [comment]
if it annoys you, you can buy like 10usd worth of BNB and change binance settings to pay fees with BNB

**Comment by miwtoo** [comment]
But it still remains in my wallet ?

**Comment by miwtoo** [comment]
![image](https://user-images.githubusercontent.com/12011082/116802233-87851c80-ab3b-11eb-8dd4-cbb6e8c94cfd.png)
![image](https://user-images.githubusercontent.com/12011082/116802247-9d92dd00-ab3b-11eb-9bee-91f7e9903a26.png)
![image](https://user-images.githubusercontent.com/12011082/116802278-bdc29c00-ab3b-11eb-87a5-7c1311d171ea.png)
![image](https://user-images.githubusercontent.com/12011082/116802287-d29f2f80-ab3b-11eb-831a-5c551203f925.png)

**Comment by miwtoo** [comment]
> if it annoys you, you can buy like 10usd worth of BNB and change binance settings to pay fees with BNB

![image](https://user-images.githubusercontent.com/12011082/116802233-87851c80-ab3b-11eb-8dd4-cbb6e8c94cfd.png)
![image](https://user-images.githubusercontent.com/12011082/116802247-9d92dd00-ab3b-11eb-9bee-91f7e9903a26.png)
![image](https://user-images.githubusercontent.com/12011082/116802278-bdc29c00-ab3b-11eb-87a5-7c1311d171ea.png)
![image](https://user-images.githubusercontent.com/12011082/116802287-d29f2f80-ab3b-11eb-831a-5c551203f925.png)

**Comment by chrisleekr** [comment]
Hey @miwtoo 

> But it still remains in my wallet ?
That is remaining in your wallet and you can convert to BNB with small residue amounts of coins.

See see the code https://github.com/chrisleekr/binance-trading-bot/blob/master/app/jobs/trailingTrade/step/place-buy-order.js#L76.

It calculates 10% from quantity for commission. It does not calculate BNB amount even if you choose to.

Even if you try to sell from the Binance app, I found it leaves small amounts.
Anyway, if it is answered, please close the issue.

**Comment by miwtoo** [comment]
Thanks you 😁
