### ISSUE TITLE
lowest price

### ISSUE THREAD

**Issue by ttibau** [chrisleekr/binance-trading-bot#143]
Guys, 

Where does the lowest price comes from? 

In the image, the lowest price in bot is **0.37976** but in binance the 24h low is **0.36200**.   
In settings the configuration to get lowest price is 24h.

![Image of Yaktocat](https://i.imgur.com/dJhpkzG.png)

see image in [full screen](https://i.imgur.com/dJhpkzG.png)

Thanks a lot for this project.

**Comment by ganesshkumar** [comment]
In the settings you have two values - candle intervals and limits (number of candles to be used). 

Lowest comes from this time window (limit * candle interval).

**Comment by chrisleekr** [comment]
Thanks @ganesshkumar 

Hope his answer solved your question. Please close the issue if don't have further question. Thanks.
