### ISSUE TITLE
Sell trading disabled still placed order.

### ISSUE THREAD

**Issue by BramFr** [chrisleekr/binance-trading-bot#145]
Binance-Trading-Bot
version: 0.0.64

![2021-05-03_17-12](https://user-images.githubusercontent.com/16082279/116895932-f80f6480-ac33-11eb-9c0f-046ad3d84a0e.png)
![image](https://user-images.githubusercontent.com/16082279/116895946-fc3b8200-ac33-11eb-8e3d-a58583fdccaa.png)
![image](https://user-images.githubusercontent.com/16082279/116895955-ffcf0900-ac33-11eb-8881-0f077ae47364.png)

```
 docker logs binance-bot -f --tail=1000 | grep POku4spY7D7wxRu2qmlnh1
error from daemon in stream: Error grabbing logs: unexpected EOF
```

**Comment by chrisleekr** [comment]
Hey @BramFr 

There was a bug that you found and fixed with v0.0.65.

https://github.com/chrisleekr/binance-trading-bot/releases/tag/v0.0.65
