### ISSUE TITLE
Add limit for total number of active coins

### ISSUE THREAD

**Issue by redhelix** [chrisleekr/binance-trading-bot#147]
### Is your proposal related to a problem?

When looking for the best deals, I like to add many different coin options. When many coins reach possible trade conditions, there is a risk that the bot will draw down the available balance very low or end up with a lot of trades in play. 

### Describe the solution you'd like

Add a parameter to limit total number of active deals

### Describe alternatives you've considered

reducing the number of coins to monitor in the list - means foregoing potential profits

**Comment by chrisleekr** [comment]
Hmm, so like if there are 5 open orders, you don't want more buy?

**Comment by redhelix** [comment]
Correct - Could limit by bases - 5 USDT, 5 BTC etc. Wait till coins cycle out could also sort by closest to buy price

**Comment by chrisleekr** [comment]
I actually found this feature needed when all coins were going down and placing a lot of orders for many coins at the same time.

I will add to TODO list.
