### ISSUE TITLE
Why such an old version for mongo?

### ISSUE THREAD

**Issue by ottuzzi** [chrisleekr/binance-trading-bot#152]
Hi all,

   yesterday I tried to install bot both on windows and rpi4 (ubuntu 20.04 64bit).
On windows everything is smooth and instructions are ok :)
On rpi4 there were 2 problems:

1. I needed to "recompile" binance-bot docker (see issue #22 )
2. I needed to find a working version for mongodb and I saw that version 3.2.20-jessie is very old (and not available for aarch64). I tried to update to 3.6-xenial (so still a 3.x) and things looks like are working fine now

So the question is: is it possible to update the mongodb version to something more recent?

Thanks in advance
Bye
Piero

**Comment by ottuzzi** [comment]
I read that raspberry pi older than rpi4 is discouraged... upgrading mongo to a recent version will be a clear sign of the supported platforms :)

**Comment by chrisleekr** [comment]
Read README.md - https://github.com/chrisleekr/binance-trading-bot#trailing-buysell-bot

**Comment by chrisleekr** [comment]
Hey @ottuzzi 

If your question is resolved, please close the issue. Thanks!
