### ISSUE TITLE
How many money can be received maximum?

### ISSUE THREAD

**Issue by meftunca** [chrisleekr/binance-trading-bot#155]
Hello, let's say I have $ 2000 as an example. I set $ 200 for the maximum purchase. Will he get 10 coins or 1 coin?

**Comment by chrisleekr** [comment]
If you set $200 for the maximum purchase amount, it will purchase $200 only for each coin.

https://github.com/chrisleekr/binance-trading-bot/blob/master/app/jobs/trailingTrade/step/place-buy-order.js#L54

**Comment by chrisleekr** [comment]
Hey @meftunca 
If your question is resolved, please close the issue.

**Comment by meftunca** [comment]
So if I have $ 1000, can he get 10 coins out of $ 100?

**Comment by chrisleekr** [comment]
@meftunca 
If all of your coins reach the lowest price of your candle configuration, then yes.
It will buy $100 for each coin.
