### ISSUE TITLE
Unable to run behind nginx reverse proxy

### ISSUE THREAD

**Issue by Errichamonda** [chrisleekr/binance-trading-bot#156]
Hi, I want to run this application behind a nginx reverse proxy. I've done the setup and whatever and the page loads correctly. The only thing is the websocket fails to connect to the server.
I've tried enabling websocket support for my nginx but nothing changes.

**Comment by chrisleekr** [comment]
@Errichamonda I have not tried to run behind nginx reverse proxy. Since it has a local tunnel, try to use it. It's simple.

**Comment by mikael85** [comment]
@Errichamonda you must include the following settings in your nginx config file:
([https://www.nginx.com/blog/websocket-nginx/](https://www.nginx.com/blog/websocket-nginx/))
`
location /wsapp/ {
    proxy_pass http://wsbackend;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Host $host;
}
`

**Comment by chrisleekr** [comment]
Hey @Errichamonda 

If you resolved this issue, please add any tip to Wiki - https://github.com/chrisleekr/binance-trading-bot/wiki/Troubleshooting

Thanks in advance!

**Comment by Errichamonda** [comment]
It was a problem with nginx proxy manager. I switched to SWAG by linuxserver and worked without problem.

**Comment by m4cdel** [comment]
help me,
how i run the reverse proxy in the nginx ?
wich file i need to change to do it? 
thanks
