### ISSUE TITLE
Raspberry Pi Docker not reaching Alpine's APKINDEX.tar.gz

### ISSUE THREAD

**Issue by bangbaew** [chrisleekr/binance-trading-bot#157]
## Description

When I try to build the Dockerfile on my Raspberry Pi 4 32-bit using Docker installed from apt,
I always get this error messages at package installation step:

Step 2/19 : RUN apk add --no-cache make gcc g++ python
 ---> Running in b06bda995724
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/armv7/APKINDEX.tar.gz
**WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.11/main: temporary error (try again later)**
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/armv7/APKINDEX.tar.gz
**WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.11/community: temporary error (try again later)
ERROR: unable to select packages:**
  g++ (no such package):
    required by: world[g++]
  gcc (no such package):
    required by: world[gcc]
  make (no such package):
    required by: world[make]
  python (no such package):
    required by: world[python]

## To Reproduce

rebuild Dockerfile using docker build -t [tag] . or build from docker-compose
I've tried alpine v3.11 v3.12 v3.13, but no luck.
I currently have to use **node:14** tag (Debian) and it's working normally, but sometimes the frontend shows the loading circle spinning forever and I need to restart the container manually, I'm not sure if the logged error message was **"Something wrong with trailing-trade-common cache"** or something else, I'm don't know if this is the Debian problem so I want to use Alpine because it works on my x86 machine flawlessly.

## Expected Behaviours

can and packages and build in Alpine without errors.

## Screenshots

![image](https://user-images.githubusercontent.com/29559559/117456700-ae47b680-af72-11eb-9587-4fce2baca631.png)

**Comment by ungreanable** [comment]
I found this error too,
But this https://github.com/gliderlabs/docker-alpine/issues/386#issuecomment-376784936
work for me.

**Comment by chrisleekr** [comment]
@ungreanable 
Thanks for helping other traders!

Could you add your tip to Wiki? https://github.com/chrisleekr/binance-trading-bot/wiki/Troubleshooting

**Comment by bangbaew** [comment]
I'm currently having another issue: sometimes after adding new symbols and saving changes, after I reload the frontend, it ends up spinning forever, I read Docker's logs and it says **Something wrong with trailing-trade-common cache**, I think it has something to do with mongo and redis volumes mounting, because it works after I prune the volumes. I'm figuring out the way to reproduce the bug.

**Comment by chrisleekr** [comment]
@bangbaew Is it happening every time? Which RPi version are you using?

The error `Something wrong with trailing-trade-common` is mostly like your `BINANCE_MODE` is not configured correctly.

**Comment by ungreanable** [comment]
> @ungreanable
> Thanks for helping other traders!
> 
> Could you add your tip to Wiki? https://github.com/chrisleekr/binance-trading-bot/wiki/Troubleshooting

Added this solution to wiki.

**Comment by chrisleekr** [comment]
@bangbaew 

> The circle keeps spinning after saving.

Hmm, I can see from your log that your configuration is saved and you are getting account information.

> Edit: Currently, after pruning the volumes and recreating the containers, the symbol cards aren't loading, it loaded only account balance and shows only the card which i'm currently having the coin amount in my spot wallet, and it keeps spinning again after saving settings. I don't know what causes this problem, it was previously working fine 3 hours ago.

That is odd. 

What commands were you using to prune the volumes? Were you using `-v`?

```
$ docker-compose -f docker-compose.server.yml down -t1 -v
$ docker-compose -f docker-compose.server.yml up -d
```

Maybe try to use PR #77, which I am running in my RPi 4 currently.
Make sure you docker-compose down with `-v`. 

And feel free to add cronjob to restart the bot periodically.

https://github.com/chrisleekr/binance-trading-bot/pull/77#issuecomment-831915217

**Comment by bangbaew** [comment]
> What commands were you using to prune the volumes? Were you using `-v`?

No, i've never used compose-down -v before, I use **docker-compose down** and then **docker volume prune**
But I changed the yml file name from docker-compose.rpi.yml to docker-compose.yml so I can compose up and down easily, does this matter?

**Comment by chrisleekr** [comment]
>No, i've never used compose-down -v before, I use docker-compose down and then docker volume prune

Use `-v` to completely remove all volumes. Note that it will reset your configurations.

>docker-compose.rpi.yml 

Sorry, my mistake, the command should be

```
$ docker-compose -f docker-compose.rpi.yml down -t1 -v
$ docker-compose -f docker-compose.rpi.yml up -d
```

**Comment by bangbaew** [comment]
> > No, i've never used compose-down -v before, I use docker-compose down and then docker volume prune
> 
> Use `-v` to completely remove all volumes. Note that it will reset your configurations.
> 
> > docker-compose.rpi.yml
> 
> Sorry, my mistake, the command should be
> 
> ```
> $ docker-compose -f docker-compose.rpi.yml down -t1 -v
> $ docker-compose -f docker-compose.rpi.yml up -d
> ```

I've been trying compose down -v and up several times and it's now happening the same,
I've tried changing to Debian nodejs, regenerating API keys.
still no luck, I'm gonna flash my Raspbian again.
I'm not sure if there's other software conflicting with the bot: I've installed **Grafana**, **Telegraf**, **InfluxDB** for RPi monitoring, and **ttyd** for web-based terminal

![image](https://user-images.githubusercontent.com/29559559/117545088-86c61c00-b04e-11eb-9ded-2c42324bab70.png)

**Comment by bangbaew** [comment]
The problem seems to be solved!, I need to tell that, at first I copy the content of api key file (.env) from my PC using Ctrl-A on the whole text and then I paste on the linux nano tool using **nano .env** on my RPi, it seems to have the problem recently, so I tried flashing my raspbian and no luck, then I tried copying the content in .env file and paste on my PC and run it, it shows the same thing... So I tried deleting the whole text pasted .env file, and run **cp .env.dist .env** then I run nano and copied just the api keys into it, it seems to be working normally now. Thanks a lot.

So, to say it shortly, don't Ctrl-A and copy-paste the whole content of .env file, use duplication .env.dist instead and edit it only the keys field.

**Comment by bangbaew** [comment]
Ok, I'm here to update, I've figured out that the problem is NOT related the .env file, or installed packages, or Raspbian OS at all (because it also happens only hackintosh), I'd been mistaken on the previous replies and I've seen that the problem still occurs after changing the symbols settings for the second time after creating the containers, this happens on my PC too, but it just stuck on **"Something wrong with trailing-trade-common cache"** for about 5 minutes and the bot can continue working again, but for RPi, I don't know how long it will take, I waited for 10 minutes and gave up, so I have to use **docker-compose down && docker-compose up** (without pruning volumes) every time after changing the symbol settings, I think the problem is with the internet connection or the volume.

It would be great to have an option for restarting the containers after applying changes, so I won't have to restart them manually.
