### ISSUE TITLE
Docker fails to build on servers with custom interface MTU

### ISSUE THREAD

**Issue by radumalica** [chrisleekr/binance-trading-bot#159]
Hi mates

A word of warning if trying to docker build binance trading bot on a VM which has MTU different than 1500 on any hosting (openstack, aws, etc)

The docker0 by default has MTU 1500 on docker0 interface.
If the host (VM or physical server) has the MTU _different_ from docker0 interface, fetching images when building docker images will fail (hanging forever at fetch command, in my case "fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
")

To solve this, find "daemon.json" for docker configuration and add this into that json array:

`"mtu": 1442`

This is just an example for my bot running on openstack VM, match the number there with your host's MTU

Then restart docker engine:

`systemctl restart docker`

**Comment by chrisleekr** [comment]
Hey @radumalica 

Thanks for your tip. I assume many people will have a similar issue. 
Please add your tip to WIki https://github.com/chrisleekr/binance-trading-bot/wiki/Troubleshooting

**Comment by radumalica** [comment]
Hey @chrisleekr , i have added the above to the wiki as you said, i am closing this.
