### ISSUE TITLE
Summary of transactions on web GUI 

### ISSUE THREAD

**Issue by edebie** [chrisleekr/binance-trading-bot#160]
### Is your proposal related to a problem? no

<!-- Provide a clear and concise description of what the problem is. For example,
It would be nice to have a page on the web interface to report on profits/losses:

### Describe the solution you'd like
Separate page on the interface with the following:
1- Daily profit/losses (in base coin, and %)
2- Table of transactions (coin, purchase price, sales price, profit/loss (value, and %), date/time transactions

**Comment by chrisleekr** [comment]
@edebie 

Thanks for the suggestion.

Since PR #77 supporting a lot of coins to monitor, I found it is not easy to trace transactions.

I may need to think about the way to display transactions for the coin.

I will leave this issue open.

**Comment by habibalkhabbaz** [comment]
@edebie If you meant the order history of a coin. I already implemented this on my local branch and I am testing it now.
I may submit a pull request for this after @chrisleekr  release the grid strategy feature.

| Order History Icon | Order History Modal |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/31035020/127460491-213b15f7-dc6e-4f13-8bd7-fd653df12986.png) | ![image](https://user-images.githubusercontent.com/31035020/127460576-65d2f59e-7f61-49be-ac2b-43c5c7e02cb3.png) |

This is simply organized as same as Binance web view. I am thinking for a better way to view these info but at least this is easy to understand :)

**Comment by habibalkhabbaz** [comment]
What would you like to see from the transactions, or in other words, what would you like to get from this (price, total, price, etc.)? 
BTW, I think this issue same as #15, isn't ?
