### ISSUE TITLE
How to set up the trading bot

### ISSUE THREAD

**Issue by michaelodafe** [chrisleekr/binance-trading-bot#161]
Good Day, please I need help setting up the trading bot. I went through the set up process but I didn't understand what to do, can I get a detailed explanation on how to set it up please?

Thank you.

**Comment by chrisleekr** [comment]
@michaelodafe 

I am not sure where to start. 

1. You will need a Linux server.
2. Install Git, NPM, Docker, Docker-compose
3. Clone this repository
4. Then follow this - https://github.com/chrisleekr/binance-trading-bot#how-to-use

Google will be your best teacher for step 2-3.

**Comment by chrisleekr** [comment]
@michaelodafe If your issue is resolved, please close the issue.
