### ISSUE TITLE
What will be the next feature?

### ISSUE THREAD

**Issue by chrisleekr** [chrisleekr/binance-trading-bot#166]
Hey guys,

I have been working on stabilising PR #77 and now it seems pretty stable.
Once I release a new version, I will work on the next feature.

However, I have been given a lot of tasks and not sure what the priorities are.
Hence, I have decided to put on the vote for the next feature to be developed because this project is a community-driven project.

Please click the below link to vote. I will develop the most voted feature first and then the next.

https://www.surveymonkey.com/r/9Y395K9

**Comment by chrisleekr** [comment]
@buehler You deployed in k8s, nice!

Yap, if securing the frontend gets the most votes, I will start with it!

**Comment by buehler** [comment]
Yes I did, it's working very smooth!
Should I make a pull request and add the needed kubernetes files to deploy the bot?
What do you think?

**Comment by chrisleekr** [comment]
@buehler I really want to see. However, I think it will be better you create your repository and push the code in there.
I will definitely update my README.md to link your repo!

**Comment by buehler** [comment]
Alright then I'll do that. I'll come back to you as soon as I have the needed files on github.

**Comment by JZLeung** [comment]
The binance api is not accessible in mainland China. Can a proxy be added when requesting the api?

**Comment by chrisleekr** [comment]
@JZLeung Please refer https://github.com/chrisleekr/binance-trading-bot/issues/124

**Comment by chrisleekr** [comment]
Guys, I closed the survey because SurveyMonkey only supports 40 responses in the free plan.

Here is the result. Thank you all for participating.

Once PR #77 is merged in, I will start with #100. 
For the tasks that received the same number of vote, I will prioritise myself.

| ANSWER | CHOICES |  RESPONSES |
| --- | --- | --- |
| Add manual buy/sell feature - [#100] |47.50% |19 |
| Improve sell strategy with conditional stop price percentage based on the profit percentage - [#94] | 45.00% | 18| 
| Add sudden drop buy strategy - [#67] | 45.00% | 18 |
| Support Grid strategy for buy/sell to mitigate loss/increasing profit - [#158] | 45.00% | 18|
| Improve buy strategy with restricting purchase if the price is close to ATH - [#82] | 40.00% | 16| 
| Secure frontend with the password authentication | 37.50% | 15 |
| Display summary of transactions on the frontend - [#160] | 35.00% | 14 | 
| Add minimum required order amount - [#84] | 22.50% | 9 |
| Manage setting profiles (save/change/load?/export?) - [#151] | 20.00% | 8 |
| Filter symbols in the frontend - [#120] | 20.00% | 8 |
| Improve notifications by supporting Apprise - [#106] | 20.00% | 8 |
| Support cool time after hitting the lowest price before buy - [#105] | 17.50% | 7| 
| Add frontend option to disable sorting or improve sorting | 15.00% | 6 |
| Reset global configuration to initial configuration - [#97] | 7.50% | 3 |
| Support limit for active buy/sell orders - [#147] | 7.50% | 3 |
| Develop simple setup screen for secrets | 7.50% | 3 |
| Support multilingual frontend - [#56] | 2.50% | 1 |

![image](https://user-images.githubusercontent.com/5715919/118483932-fbd5d780-b759-11eb-8b1e-6973994f0927.png)
