### ISSUE TITLE
set up production mode

### ISSUE THREAD

**Issue by yyilmaz19** [chrisleekr/binance-trading-bot#167]
Hi, is it possible to install only production mode without NPM. 
in dockerfile folder i copied docker-compose.yml and docker-composeserver.yml  from github repo.
1-) I created .env file ( but i couldn't understand what is "based on .env.dist") 
2-) I install the docker images (docker-compose -f docker-compose.server.yml pull) no problem when 
I start the services ( docker-compose -f docker-compose.server.yml up -d ) always get this error. 
failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount796944677/Dockerfile: no such file or directory
ERROR: Service 'binance-bot' failed to build

could you please elaborate on installing via docker image for beginner :-)

**Comment by chrisleekr** [comment]
> 1-) I created .env file ( but i couldn't understand what is "based on .env.dist")

As @ysfckr mentioned, copy `.env.dist` and edit it.

You don't need Node to run the bot if you are using `docker-compose.server.yml`.

> failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount796944677/Dockerfile: no such file or directory

But I am not sure what the error is. 
Hmm, could be this? https://github.com/chrisleekr/binance-trading-bot/blob/master/docker-compose.server.yml#L40
Try without this line

**Comment by chrisleekr** [comment]
@yyilmaz19 

Please close the issue if your issue is resolved.

**Comment by yyilmaz19** [comment]
> > 1-) I created .env file ( but i couldn't understand what is "based on .env.dist")
> 
> As @ysfckr mentioned, copy `.env.dist` and edit it.
> 
> You don't need Node to run the bot if you are using `docker-compose.server.yml`.
> 
> > failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount796944677/Dockerfile: no such file or directory
> 
> But I am not sure what the error is.
> Hmm, could be this? https://github.com/chrisleekr/binance-trading-bot/blob/master/docker-compose.server.yml#L40
> Try without this line

hi, thanks for solution but it didn't work. it gives same error 
dockerfile: open /var/lib/docker/tmp/buildkit-mount187344033/Dockerfile: no such file or directory

**Comment by chrisleekr** [comment]
@yyilmaz19 

I am honestly not sure what is going on with your environment. 

It's Windows, right?

It looks like not related to the bot, but Docker.
So could you research in Google if you want to run the bot?

**Comment by yyilmaz19** [comment]
it is macBook

> @yyilmaz19
> 
> I am honestly not sure what is going on with your environment.
> 
> It's Windows, right?
> 
> It looks like not related to the bot, but Docker.
> So could you research in Google if you want to run the bot?

ok tnx, btw it is macBook

**Comment by chrisleekr** [comment]
Ah ok, let me try with MacBook. Give me a sec.

**Comment by yyilmaz19** [comment]
> Selam Yyilmaz19,
> You can rename ".env.dist" file as ".env" and input your binance API key and secret into ".env"

@ysfckr thanks, (musiat olursa LinkedIn yaziyorum)

**Comment by chrisleekr** [comment]
@yyilmaz19 

I just tested with my MacBook and run fine without any issue.

Note that my MacBook is an old Intel CPU.
