### ISSUE TITLE
Sell strategy?

### ISSUE THREAD

**Issue by dts** [chrisleekr/binance-trading-bot#168]
It appears that the default strategy is basically "sell everything when it's at a 7-day high" - is this read accurate?  If so - are there plans to change that to be a little less aggressive? Perhaps keeping track of the last sell price, and selling some fraction of holdings as it ratchets up?

**Comment by ottuzzi** [comment]
Hi,

   sell strategy is not what you have described: you set a trigger (say +3.5%) and when the price is above the buyPrice+trigger the bot will place a STOP-LOSS-LIMIT sell order. The trigger is in your hand and you can choose the value.

**Comment by andferno** [comment]
> It appears that the default strategy is basically "sell everything when it's at a 7-day high" - is this read accurate? If so - are there plans to change that to be a little less aggressive? Perhaps keeping track of the last sell price, and selling some fraction of holdings as it ratchets up?

#158 is what you are requesting.

**Comment by chrisleekr** [comment]
Thanks for your input, @ottuzzi @andferno 

@dts I am not sure where you get "sell everything when it's at a 7-day high"

I suggest reading README.md how it works.

**Comment by dts** [comment]
I read through the readme, started running it, and it wasn't until I read the code until I noticed this.  In place-sell-order.js:

```
const orderQuantity = parseFloat(
    _.floor(freeBalance - freeBalance * (0.1 / 100), lotPrecision)
  );
```

And that value isn't checked against any other thing - i.e. the order quantity is the free balance less 0.001%.  In place-buy-order, it is compared against the maxPurchaseAmount, however.

**Comment by andferno** [comment]
Selling orders doesn't have a limit as you can check into settings. It's only for buying. So when selling it sells all because doesn't have any setting to compare to.
That's why I told you that #158 will help you. Because you'll be able to set limits to grids. If you select only one grid you'll be able to select that limit also.

**Comment by chrisleekr** [comment]
@dts 

@andferno is correct. Sell action will sell all your coins.

**Comment by chrisleekr** [comment]
@dts 
Please close the issue if your question is answered.
