### ISSUE TITLE
Bot is not sell all balance

### ISSUE THREAD

**Issue by sekozzi** [chrisleekr/binance-trading-bot#169]
Hello, 

Firstly, thanks for this amazing bot. I have been using the bot whether 1 week. I have seen the interesting a thing. For example; the bot bought 87 one of coin but sold 86.9 one of coin. I didn't understand the mentalty of bot. Can you explain? 

Thanks,

**Comment by andferno** [comment]
It's Binance and sell orders, not the bot. Try to sell manually from Binance and you'll get the same result. There is an option toi transform all those little amounts to BNB.

**Comment by sekozzi** [comment]
Thanks for answer, yes that is binance method but there is bnb option on binance that  fee and brokerage for treding.

I think, if there is bnb on spot, you can add "use bnb for fee" option.

**Comment by andferno** [comment]
That's right, you can use BNB and rate would be 0,75%. But I'm trying to explain those little amount of currency that remains after a selling operation. Those are because rounding and converting from Binance, not the bot. Try to place a manual order and you'll see that same behavior.

**Comment by chrisleekr** [comment]
Thanks @andferno 

@sekozzi The bot is calculating 0.1% as commission to make sure the order is placing. Refer - https://github.com/chrisleekr/binance-trading-bot/blob/feature-monitoring-simultaneously/app/cronjob/trailingTrade/step/place-sell-order.js#L66

The bot is not taking into account that you are using BNB as commission or not.

As a result, as @andferno mentioned, it leaves some residue amount of the coin. Also as @andferno mentioned, this is normal behaviour in Binance as well. 

Sometimes some coins even worse.  For example, I bought BNBUPUSDT `0.2`, but I couldn't place an order with the bot. And I only could sell BNBUPUSDT `0.1` manually in Binance.

Hope it is answered your question.

**Comment by chrisleekr** [comment]
@sekozzi Please close the issue if the question is answered.
