### ISSUE TITLE
Symbols didn't appears on frontent

### ISSUE THREAD

**Issue by ShareTextures** [chrisleekr/binance-trading-bot#17]
Hello, It seems great bot. But I can't activate it. I'm adjusting symbols but nothing appeared on the frontend. 
I can only see my balance. 
Also, I want to add NPXR/USDT. And I didn't understand the flag limit option at all. Can you describe it.

Thanks in advance.

**Comment by ShareTextures** [comment]
Fixed when I start live mode. 
All symbols working.

**Comment by chrisleekr** [comment]
@ShareTextures 
I will update to allow more decimal for the last buy signal.

For how it works in detail, you will need to read the code. 
I won't explain how it works more than what I wrote from the README.md.
It is fairly easy to read the code.

**Comment by bavinsCo** [comment]
Guys, join the Telegram group to solve problems with each other ..

https://t.me/joinchat/z3cKyYFcx0NiOTA8

**Comment by chrisleekr** [comment]
@ShareTextures 
I have updated to allow more decimal for last buy price.
