### ISSUE TITLE
Add visual difference between global and "local" configuration

### ISSUE THREAD

**Issue by ottuzzi** [chrisleekr/binance-trading-bot#170]
Hi,

  I think this is an easy one: I mostly use global settings but for some pairs I use specific configuration.
Actually the difference between local and global setup is not explicitly visible in the webUI: can you simply add different colors or icons if a pair is using local/global configuration?

Thanks in advance for your work!

**Comment by chrisleekr** [comment]
@ottuzzi 

Oh, it used to display it's customised or not and I removed that feature. Yeah, I will put that back in.

**Comment by habibalkhabbaz** [comment]
@ottuzzi Thank you for your explanation. It is implemented now in the latest release.
@chrisleekr I think we can close this issue in favor of #258

**Comment by chrisleekr** [comment]
Oh yeah, thanks for reminding @habibalkhabbaz
