### ISSUE TITLE
sorry to ask the most stupid question but

### ISSUE THREAD

**Issue by KakashiOP1** [chrisleekr/binance-trading-bot#171]
how do we start your binance_trading_bot as its pretty complicated [ for me ]. do we have to install docker desktop or we can run it directly if so how then or if we have to use docker des
top then how to use it

**Comment by ottuzzi** [comment]
Please install docker desktop and then follow the instructions in the main page of the project.

**Comment by chrisleekr** [comment]
As @ottuzzi said, start with that if you are using Windows.

Recommended installation steps are:

1. You will need a Linux server.
2. Install Git, NPM, Docker, Docker-compose
3. Clone this repository
4. Then follow this - https://github.com/chrisleekr/binance-trading-bot#how-to-use

Google will be your best teacher for step 2-3.

**Comment by chrisleekr** [comment]
@KakashiOP1 Please close the issue if your issue is resolved.
