### ISSUE TITLE
ETHUSDT showing "current price = 150.00 USDT" and it doesn't update

### ISSUE THREAD

**Issue by hugoleosp** [chrisleekr/binance-trading-bot#179]
## Description

I'm testing the feature-monitoring-simultaneously branch
I have setup around 11 symbols, one of them is ETHUSDT.
It freezes on "Current price: 150.00" and it doesn't change.
(even that current price doesn't exist, actual price is 3795)

The other coins seems to be working normal

## To Reproduce

I didn't do anything rather than the expected.
It was working and it suddenly entered in "locked" and no price updates.
I had manually setup the "last buy price" to match my order,
but even setting to 0 won't work
I also tried to remove the symbol and add it again ..
I tried to restart the bot
I also tried a clean installation (it worked for a few minutes and went back to the same problem)

## Expected Behaviours

Update to the correct price of the coin ETHUSDT

## Screenshots

![image](https://user-images.githubusercontent.com/21294868/118381823-74575f80-b5c5-11eb-996c-afa98bf228fa.png)

## Additional context

I tried to switch to the master branch and the issue persists

**Comment by hugoleosp** [comment]
Another issue that now I realized .. I can't add new coins .. when I try to type the coins it shows "no matches found"

**Comment by chrisleekr** [comment]
@hugoleosp 

Can you take a look at the bottom of the frontend, which commit hash are you using?

**Comment by hugoleosp** [comment]
Running Version:
v0.0.65
(3a0fda6)
Latest Version:
v0.0.65

**Comment by chrisleekr** [comment]
Hmm, that is strange.

> It freezes on "Current price: 150.00" and it doesn't change.

Wait, what? ETHUSDT is 3840 USDT at the moment.
Are you running the TestNet?

**Comment by hugoleosp** [comment]
> Hmm, that is strange.
> 
> > It freezes on "Current price: 150.00" and it doesn't change.
> 
> Wait, what? ETHUSDT is 3840 USDT at the moment.
yes, that's the weird part, it locks to 150 and it doesn't update, also the time at the lock is frozen while the rest of the coins keep updating as expected.
It seems this starts to happen at the same time I cannot add new symbols

> Are you running the TestNet?
I'm using the live

**Comment by cucurucu666** [comment]
> Another issue that now I realized .. I can't add new coins (rather than a very small list) .. when I try to type the coins it shows "no matches found"
> 
> ![image](https://user-images.githubusercontent.com/21294868/118381968-a5845f80-b5c6-11eb-9d9b-3219c8ee13d2.png)
> ![image](https://user-images.githubusercontent.com/21294868/118381974-b92fc600-b5c6-11eb-84c7-b36f57e159d8.png)

I have the same issue and after removing some coins from the list they still appear in frontend

`Running Version: v0.0.65 (3a0fda6)
Latest Version: v0.0.65`

**Comment by hugoleosp** [comment]
About the coins still showing on your screen could be because there's an open order for that coin or a manual buy price (which when you set to 0 should release the coin)

**Comment by cucurucu666** [comment]
> About the coins still showing on your screen could be because there's an open order for that coin or a manual buy price (which when you set to 0 should release the coin)

Yes, I manually canceled the orders and now ( even after setting to 0 the last buy price ) the coins are "stuck" on frontend with the "Open Order #" status for hours now.

**Comment by chrisleekr** [comment]
@hugoleosp It cannot be ETH is 150USDT in the live mode.
Please make sure you have the correct configuration.

@cucurucu666 
I assume you removed the symbol from monitoring symbols.
If you removed the coin from monitoring symbols, it won't retrieve open orders from Binance. 
If didn't remove it from the monitoring symbols, create a new issue so we can track it from there.

**Comment by chrisleekr** [comment]
@hugoleosp 

It's been 4 days since the last comment. Close the issue if your issue is resolved.

**Comment by hugoleosp** [comment]
sorry =/ I didn't solve it .. it happens randomly and it stops updating ETH/USDT but not the other coins .. I've been for hours trying to install on a VPS (it was on my own pc) and I'm stuck with iptables restrictions and because I couldn't finish and test there I didn't close here .. but I'll close as it seems this is not the expected behavior .. I must've done something wrong .. thank you for your support and great work
