### ISSUE TITLE
when the bot Take profit 

### ISSUE THREAD

**Issue by AhmedElkanany** [chrisleekr/binance-trading-bot#186]
when the bot Take a profit ? 
for example, 
Last buy price: 100
can I decide when the current price is 101 sell 1.01 take profit?

**Comment by skinner12** [comment]
It's well explain [https://github.com/chrisleekr/binance-trading-bot#sell-scenario](herel)

- Trigger percentage: 1.05 (5.0%)
 -    Stop price percentage: 0.98 (-2.0%)
 -    Limit price percentage: 0.979 (-2.1%)

**Comment by AhmedElkanany** [comment]
> It's well explain [https://github.com/chrisleekr/binance-trading-bot#sell-scenario](herel)
> 
> * Trigger percentage: 1.05 (5.0%)
> * Stop price percentage: 0.98 (-2.0%)
> * Limit price percentage: 0.979 (-2.1%)
Why it does not execute sell when Trigger percentage reach as take profit action 
in my case when the price goes from 100 to 105 this my exit point but the bot place a stop-loss order not take profit and in my case, the price is less than my buy price so is there an option to exit when i hate the price i need 
on this screen, I
<img width="1224" alt="Screen Shot 2021-05-18 at 12 48 11 PM" src="https://user-images.githubusercontent.com/6972986/118639330-12bb0f00-b7d8-11eb-8192-283c88f98697.png">
 had reached my exit point but it never work

**Comment by chrisleekr** [comment]
I still think @AhmedElkanany is not understanding how it works.

The bot will place a Stop-Limit order and it will cancel if the price rises. In your screenshot, it shows an expected behaviour.
As you can see
03:10:50, limit price 0.55034, stop price: <=0.5509
03:40:33, limit price 0.55126, stop price: <=0.55182
03:41:31, limit price 0.55256, stop price: <=0.55313
03:42:32, limit price: 0.55389, stop price: <=0.55446

If you keep scrolling up, there should be the order that "Filled" instead of "Cancelled" if the price decreased from the highest.

**Comment by AhmedElkanany** [comment]
> I still think @AhmedElkanany is not understanding how it works.
> 
> The bot will place a Stop-Limit order and it will cancel if the price rises. In your screenshot, it shows an expected behaviour.
> As you can see
> 03:10:50, limit price 0.55034, stop price: <=0.5509
> 03:40:33, limit price 0.55126, stop price: <=0.55182
> 03:41:31, limit price 0.55256, stop price: <=0.55313
> 03:42:32, limit price: 0.55389, stop price: <=0.55446
> 
> If you keep scrolling up, there should be the order that "Filled" instead of "Cancelled" if the price decreased from the highest.
> 
> Please close the issue if your question is answered.

Yes it happened but most of the time with less than the buy price so my question is why there is no option to immediately take profit action I did it on my development code manual by place an order if reached and i was ask if there another option you provide

**Comment by chrisleekr** [comment]
@AhmedElkanany 

Please read README again and make sure you understand how it works. It's because of your configuration that the selling price was less than the buy price. 

You need to do some calculation to figure out what configurations are best for your strategy.

**Comment by AhmedElkanany** [comment]
@chrisleekr 

Ok Thanks a lot, I work on my calculations to figure out how it work, your project helped me a lot thank you
