### ISSUE TITLE
How to migrate from my local host to a server

### ISSUE THREAD

**Issue by martip07** [chrisleekr/binance-trading-bot#19]
Hi,

I would like to know how can I migrate the installation from my local machine to a server because I would like to keep it up running 24 x 7 without problems.

Regards,

**Comment by chrisleekr** [comment]
Hi, @martip07 

Just write down your configuration and last buy price (if the bot recorded).
And in the new server, just re-enter configuration and last buy price.

**Comment by bavinsCo** [comment]
Guys, join the Telegram group to solve problems with each other ..

https://t.me/joinchat/z3cKyYFcx0NiOTA8
