### ISSUE TITLE
gettin an error

### ISSUE THREAD

**Issue by KakashiOP1** [chrisleekr/binance-trading-bot#192]
getting this error its prolly because i have the wrong api key? and hopefull its gonna resolve the buffering thing in its front end ty for helping me in advance
![image](https://user-images.githubusercontent.com/67217711/119080560-ebeb1b80-ba17-11eb-808c-1d953c277166.png)
![image](https://user-images.githubusercontent.com/67217711/119080624-0d4c0780-ba18-11eb-92f7-85fc55f1f2f3.png)

**Comment by pedrohusky** [comment]
I'm getting the same error, here: https://github.com/chrisleekr/binance-trading-bot/issues/188

In there I've made some steps to fix it, temporarily, but fix it. Check it out.

**Comment by chrisleekr** [comment]
Since may people asking about this error message, I added to Wiki - https://github.com/chrisleekr/binance-trading-bot/wiki/Troubleshooting#binance-api-error---eai_again

Please close the issue if your question is answered.
