### ISSUE TITLE
Symbols in frontend should be in fixed position

### ISSUE THREAD

**Issue by ptantiku** [chrisleekr/binance-trading-bot#193]
When using the frontend, the symbols keep moving around. It's hard to read the number and react when the next second it's gone, and I have to find it again.

I looked through the code and found the logic that it keeps sorting the symbols by `differences` and `differencesToCancel`. I think there might be people find this useful. But for a slow guy like me, it would be better if the symbols are fixed, without sorting, or maybe sorting them by symbol name, so the numbers can be comprehended easier.   Or perhaps, a switch in the settings?

Thanks.

**Comment by pedrohusky** [comment]
Hi, where is the logic, please?

**Comment by ptantiku** [comment]
> Hi, where is the logic, please?
Here:  https://github.com/chrisleekr/binance-trading-bot/blob/master/public/js/App.js#L85-L102

**Comment by chrisleekr** [comment]
@ptantiku 

I do have a plan to support disabling and improving the sorting. It just was not important than other feature development at the moment. And I do not have much time to code recently. 

https://github.com/chrisleekr/binance-trading-bot#changes--todo
