### ISSUE TITLE
cancelled open sell order from binance dashboard  

### ISSUE THREAD

**Issue by AhmedElkanany** [chrisleekr/binance-trading-bot#195]
If you cancelled open sell order from Binance dashboard the coin will disappear until you sell all of it, it will show again

**Comment by AhmedElkanany** [comment]
<img width="1440" alt="Screen Shot 2021-05-23 at 5 16 44 AM" src="https://user-images.githubusercontent.com/6972986/119246946-1f4bb880-bb86-11eb-9a13-36098a7816d2.png">
look to ETH

**Comment by chrisleekr** [comment]
First of all, @AhmedElkanany please use the template provided for the bug report.

And provide any details and some logs.

See this page  https://github.com/chrisleekr/binance-trading-bot/wiki/Troubleshooting

**Comment by chrisleekr** [comment]
As I haven't got any more information, let me close the issue. 
Please open a new issue or reopen this if you still have an issue.
