### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by Akincayir** [chrisleekr/binance-trading-bot#196]
I can not follow the step below you provided previously. Could you have any suggestion for the detail, any video or any picture?

**Then follow this - https://github.com/chrisleekr/binance-trading-bot#how-to-use**
PS: I have Ubuntu in my computer. 

Best

**Comment by chrisleekr** [comment]
@Akincayir 

All you need is docker & docker-compose installed in your Ubuntu.
Please google it and install them.

Please close the issue if your issue is resolved.
