### ISSUE TITLE
Nice project

### ISSUE THREAD

**Issue by ramonck** [chrisleekr/binance-trading-bot#2]
Hey nice project you did here, I'm new to the spot test network, do you know if there is a web interface I can see the orders list made by the bot? I want to compare the order results in test environment with what happened in real life.

**Comment by chrisleekr** [comment]
Hey @ramonck 

I don't think they have Testnet UI.
But you can use API to get the information.

I also felt a bit hard to test with the test environment, so just deposit a little amount in the live environment and do it.

**Comment by bavinsCo** [comment]
Guys, join the Telegram group to solve problems with each other ..

https://t.me/joinchat/z3cKyYFcx0NiOTA8
