### ISSUE TITLE
LocalTunnel Issue

### ISSUE THREAD

**Issue by salimj6** [chrisleekr/binance-trading-bot#200]
binance-bot            | events.js:353
binance-mongo          | 2021-05-25T21:21:43.076+0000 I NETWORK  [conn24] end connection 172.18.0.5:39268 (22 connections now open)
binance-bot            |       throw er; // Unhandled 'error' event
binance-mongo          | 2021-05-25T21:21:43.076+0000 I NETWORK  [conn21] end connection 172.18.0.5:39262 (22 connections now open)
binance-bot            |       ^
binance-mongo          | 2021-05-25T21:21:43.076+0000 I NETWORK  [conn22] end connection 172.18.0.5:39264 (22 connections now open)
binance-bot            |
binance-mongo          | 2021-05-25T21:21:43.076+0000 I NETWORK  [conn23] end connection 172.18.0.5:39266 (22 connections now open)
binance-bot            | RangeError: Invalid WebSocket frame: RSV1 must be clear
binance-mongo          | 2021-05-25T21:21:43.076+0000 I NETWORK  [conn18] end connection 172.18.0.5:39256 (22 connections now open)
binance-bot            |     at Receiver.getInfo (/srv/node_modules/ws/lib/receiver.js:178:14)
binance-mongo          | 2021-05-25T21:21:43.076+0000 I NETWORK  [conn17] end connection 172.18.0.5:39254 (22 connections now open)
binance-bot            |     at Receiver.startLoop (/srv/node_modules/ws/lib/receiver.js:131:22)
binance-mongo          | 2021-05-25T21:21:43.076+0000 I NETWORK  [conn19] end connection 172.18.0.5:39258 (22 connections now open)
binance-bot            |     at Receiver._write (/srv/node_modules/ws/lib/receiver.js:78:10)
binance-mongo          | 2021-05-25T21:21:43.076+0000 I NETWORK  [conn20] end connection 172.18.0.5:39260 (22 connections now open)
binance-bot            |     at writeOrBuffer (internal/streams/writable.js:358:12)
s now open)
binance-bot            |     at Receiver.Writable.write (internal/streams/writable.js:303:10)
binance-mongo          | 2021-05-25T21:21:43.077+0000 I NETWORK  [conn15] end connection 172.18.0.5:39250 (14 connections now open)
binance-bot            |     at Socket.socketOnData (/srv/node_modules/ws/lib/websocket.js:910:35)
binance-mongo          | 2021-05-25T21:21:43.077+0000 I NETWORK  [conn13] end connection 172.18.0.5:39246 (14 connections now open)
binance-bot            |     at Socket.emit (events.js:376:20)
binance-mongo          | 2021-05-25T21:21:43.077+0000 I NETWORK  [conn14] end connection 172.18.0.5:39248 (11 connections now open)
binance-bot            |     at addChunk (internal/streams/readable.js:309:12)
binance-mongo          | 2021-05-25T21:21:43.077+0000 I NETWORK  [conn12] end connection 172.18.0.5:39244 (11 connections now open)
binance-bot            |     at readableAddChunk (internal/streams/readable.js:284:9)
binance-mongo          | 2021-05-25T21:21:43.077+0000 I NETWORK  [conn11] end connection 172.18.0.5:39242 (11 connections now open)
binance-bot            |     at Socket.Readable.push (internal/streams/readable.js:223:10)
binance-mongo          | 2021-05-25T21:21:43.077+0000 I NETWORK  [conn10] end connection 172.18.0.5:39240 (11 connections now open)
binance-bot            |     at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
binance-mongo          | 2021-05-25T21:21:43.077+0000 I NETWORK  [conn9] end connection 172.18.0.5:39238 (7 connections now open)
binance-bot            | Emitted 'error' event on WebSocket instance at:
binance-mongo          | 2021-05-25T21:21:43.077+0000 I NETWORK  [conn8] end connection 172.18.0.5:39236 (7 connections now open)
binance-bot            |     at Receiver.receiverOnError (/srv/node_modules/ws/lib/websocket.js:815:13)
binance-mongo          | 2021-05-25T21:21:43.077+0000 I NETWORK  [conn7] end connection 172.18.0.5:39234 (6 connections now open)
binance-bot            |     at Receiver.emit (events.js:376:20)
binance-mongo          | 2021-05-25T21:21:43.077+0000 I NETWORK  [conn6] end connection 172.18.0.5:39232 (6 connections now open)
binance-bot            |     at emitErrorNT (internal/streams/destroy.js:106:8)
binance-mongo          | 2021-05-25T21:21:43.077+0000 I NETWORK  [conn4] end connection 172.18.0.5:39218 (4 connections now open)
binance-bot            |     at emitErrorCloseNT (internal/streams/destroy.js:74:3)
binance-mongo          | 2021-05-25T21:21:43.078+0000 I NETWORK  [conn5] end connection 172.18.0.5:39222 (2 connections now open)
binance-bot            |     at processTicksAndRejections (internal/process/task_queues.js:82:21) {
binance-bot            |   [Symbol(status-code)]: 1002
binance-bot            | }
binance-bot            | [nodemon] app crashed - waiting for file changes before starting...
## To Reproduce

1.  building project on windows
2.  open localtunnel address

**Comment by donnolic** [comment]
Pls @salimj6 where did u host it. I'm using wamp but is not working

**Comment by salimj6** [comment]
i am running it in docker.

**Comment by chrisleekr** [comment]
@salimj6 that log is nothing to do with local tunnel as you can see from the log
 

```
binance-mongo | 2021-05-25T21:21:43.077+0000 I NETWORK [conn7] end connection 172.18.0.5:39234 (6 connections now open)
```

Check docker status

```
docker ps -a
```

**Comment by salimj6** [comment]
true, but this error is only appearing when the local tunnel is opened
Now i disabled it

**Comment by chrisleekr** [comment]
Well, I only have the log you provided to find out what happened. But I am glad to hear you fixed it.

So if it is resolved, please close the issue.
