### ISSUE TITLE
Empty screen

### ISSUE THREAD

**Issue by PiotrFerenc** [chrisleekr/binance-trading-bot#201]
Empty screen and wrong balance. :(

## Version

`Running Version: v0.0.66 (9787211) Latest Version: v0.0.66`
 

## Description
step: 
1. git pull
2. change settings (live/production mode)
3. ` npm run docker:build:win`
4. `docker-compose -f docker-compose.server.yml up -d`

![image](https://user-images.githubusercontent.com/30370747/119622798-c723e900-be07-11eb-934d-c97e93d51f6a.png)

![image](https://user-images.githubusercontent.com/30370747/119624114-19b1d500-be09-11eb-81ff-bd6ffd1a71f2.png)

**Comment by laoistom** [comment]
Did you generate and fill in your Binance API and secret in the .env file?

**Comment by chrisleekr** [comment]
Hi @PiotrFerenc 

That is so weird to show the wrong balance.
If it was test mode it would be showing millions of dollars, but just that? 

Hmm... Are you sure you using the correct API key/secret?
Even if it was not the correct one, showing one BTC is so strange.

Hmm... I think here is what you can do.

1. Make sure you have correct `.env` configuration for API/Secret.
2. Take down docker containers and clean everything and relaunch
   ```
   $ docker-compose -f docker-compose.server.yml down -t1 -v
   $ docker-compose -f docker-compose.server.yml up -d
   ```
Let me know how it goes.

**Comment by PiotrFerenc** [comment]
Yes. Now balace is correct. 💪
![image](https://user-images.githubusercontent.com/30370747/119659536-868b9600-be2e-11eb-8b7f-b86fe0d58e3d.png)

But why  i don't have "trading window" for my coin ?

https://user-images.githubusercontent.com/5715919/117468596-2ffe0b00-af98-11eb-99da-db45e8cbdc3c.png

**Comment by PiotrFerenc** [comment]
..and in docker log (binance-bot)

`api","version":"0.0.66","hostname":"41e7f76c5157","pid":18,"gitHash":"e634670","server":"cronjob","job":"trailingTradeIndicator","uuid":"af8987d0-db1b-4389-87ff-755ebb1623c5","level":50,"symbol":"BTCUSDT","err":{"message":"Timestamp for this request was 1000ms ahead of the server's time.","name":"Error","stack":"Error: Timestamp for this request was 1000ms ahead of the server's time.\n at /srv/node_modules/binance-api-node/dist/http-client.js:93:17\n at runMicrotasks (<anonymous>)\n at processTicksAndRejections (internal/process/task_queues.js:95:5)\n at async i (/srv/dist/server.js:1:28898)\n at async execute (/srv/dist/server.js:1:36491)\n at async execute (/srv/dist/server.js:1:35762)\n at async /srv/dist/server.js:1:51922\n at async CronJob.<anonymous> (/srv/dist/server.js:1:51760)","code":-1021},"debug":true,"msg":"⚠ Execution failed.","time":"2021-05-26T12:23:24.386Z","v":0}`

**Comment by chrisleekr** [comment]
Yap, the issue definitely is your time sync.

```
Timestamp for this request was 1000ms ahead of the server's time.
```

This should fix your issue.

https://github.com/chrisleekr/binance-trading-bot/wiki/Troubleshooting#how-to-fix-clock-desync

**Comment by PiotrFerenc** [comment]
doesn't work: `wsl --shutdown`

`Timestamp for this request was 1000ms ahead of the server's time.`

**Comment by felipe-perin** [comment]
try run follows commands with admin cmd prompt:

net stop w32time
w32tm /unregister
w32tm /register
net start w32time
w32tm /resync

restart docker and try again

**Comment by PiotrFerenc** [comment]
> try run follows commands with admin cmd prompt:
> 
> net stop w32time
> w32tm /unregister
> w32tm /register
> net start w32time
> w32tm /resync
> 
> restart docker and try again

works! 💪
