### ISSUE TITLE
deposit

### ISSUE THREAD

**Issue by salimj6** [chrisleekr/binance-trading-bot#207]
i was wondering why depositing coin is not detected. i deposited rvn and the bot did not pick it up. it is still showing the old number.

**Comment by chrisleekr** [comment]
Look, @salimj6 

When you ask some questions, I really need more contexts or at least some screenshots.
I won't be able to help you without any further information because I don't have any access to your bot.

**Comment by chrisleekr** [comment]
Close the issue as I didn't get more information.
