### ISSUE TITLE
How  to install in AWS ubuntu system  and Can I keep it background service?

### ISSUE THREAD

**Issue by YoungwoooKim** [chrisleekr/binance-trading-bot#208]
Yse

## Description

How  to install in AWS ubuntu system  and Can I keep it background service?

I succeed to run your amazing product in Window system.
But I want  to install in AWS Ubuntu system for using your program as background service.

**Comment by chrisleekr** [comment]
Hi @YoungwoooKim 

If you see the instructions, it's using the daemon mode of the docker-compose.
It means it will run in the background. 

Refer - https://github.com/chrisleekr/binance-trading-bot/blob/master/README.ko.md#%EC%82%AC%EC%9A%A9-%EB%B0%A9%EB%B2%95

```
docker-compose -f docker-compose.server.yml pull
docker-compose -f docker-compose.server.yml up -d
```
