### ISSUE TITLE
hopefully simple answer  Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379

### ISSUE THREAD

**Issue by 49handyman** [chrisleekr/binance-trading-bot#213]
## Description
I would like to run as local node instead of docker? any info on this type of setup would help me.

ive configured it but keep getting  even tho im running redis already without password. 

Where can i modify port parameters for all daemons? i cant find one for  webserver, only in the app/* files.

```Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379```

 Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379

**Comment by chrisleekr** [comment]
Is there any specific reason that you want to run without docker?

**Comment by chrisleekr** [comment]
Close as no more information.

**Comment by 49handyman** [comment]
yes, i already run redis locally and dont know how to config your docker to use other ports, so it wont run.

i just removed all references to redis in docker-compose.yml file, so far 

whn i try locally to run npm start i get 
redis.host not found. ive, edit the default.json. 
``` /srv/node_modules/config/lib/config.js:182
binance-bot              |     throw new Error('Configuration property "' + property + '" is not defined');
binance-bot              |     ^
binance-bot              |
binance-bot              | Error: Configuration property "redis.host" is not defined
```
just to make sure i wasnt missing a comma, i reformatted to this. i tried "127.0.0.1", "localhost", and "crypto1", which all point to 127.0.0.1

``` "redis": { "host": "127.0.0.1", "port": 6379, "password": ""},
```
is there somewhere else im missing,

**Comment by bzmhmmhi** [comment]
Hi i whant buy bata bta please help mi
