### ISSUE TITLE
Help wanted to test PR - Manual trade

### ISSUE THREAD

**Issue by chrisleekr** [chrisleekr/binance-trading-bot#217]
Hey guys,

I have been developing the feature for manually trading buy/sell #216. 
Again the changes are quite large.

If anyone wants to try to use the feature, please test this PR and let me know if there is any bug or suggestions that I missed.

You can find details here:

#216 

Please leave any feedback to the PR.

**Comment by piscui** [comment]
Sweet, I'll take it for a spin today. Thanks for the hard work!
