### ISSUE TITLE
Not working on Raspberry Pi

### ISSUE THREAD

**Issue by lain-ke** [chrisleekr/binance-trading-bot#22]
Hello, I wanted to test out the bot on my Raspberry Pi 4 but it keeps saying `exec user process caused: exec format error`.

Of course, I've used the docker image for the RPi.

Any ideas?

**Comment by chrisleekr** [comment]
Have you installed 64 bits Ubuntu? or Raspberry Pi OS?

**Comment by lain-ke** [comment]
I've installed Raspberry Pi OS 64-bit

**Comment by chrisleekr** [comment]
Yap, the `docker-compose.rpi.yml` is for 32bit. 
You can simply find arm64 mongo db image and update it.

**Comment by lain-ke** [comment]
But the Raspberry Pi 4 is aarch64 not arm64

**Comment by chrisleekr** [comment]
Actually, I now got what you meant. 
You will need to rebuild the docker image as the pushed docker image is not for the Raspberry Pi.

Simply re-build and rerun docker-compose.
```
$ docker build . --build-arg NODE_ENV=production --target production-stage -t chrisleekr/binance-trading-bot:latest
$ docker-compose -f docker-compose.rpi.yml up -d
```

As mentioned before, you need to find MongoDB image as well.

**Comment by lain-ke** [comment]
Yep, it's working now.
Thanks a lot!!

**Comment by bavinsCo** [comment]
Guys, join the Telegram group to solve problems with each other ..

https://t.me/joinchat/z3cKyYFcx0NiOTA8
