### ISSUE TITLE
Backup database to change server

### ISSUE THREAD

**Issue by braverynew** [chrisleekr/binance-trading-bot#222]
I want to change Bot to VPS. How can I backup all database and restore in new server?
Thanks

**Comment by chrisleekr** [comment]
Umm, you can do with mongodump and mongorestore - https://docs.mongodb.com/v3.6/tutorial/backup-and-restore-tools/

But if you don't have a lot of customised configuration, just write and re-configure.

For Redis, you don't need.

**Comment by braverynew** [comment]
Thanks

> Umm, you can do with mongodump and mongorestore - https://docs.mongodb.com/v3.6/tutorial/backup-and-restore-tools/
> 
> But if you don't have a lot of customised configuration, just write and re-configure.
> 
> For Redis, you don't need.

Thank bro
