### ISSUE TITLE
environment dev. fetch data but data not change

### ISSUE THREAD

**Issue by b-thanapat** [chrisleekr/binance-trading-bot#223]
hi bro
I launch on development mode but i get same data it not change. please help me.

![image](https://user-images.githubusercontent.com/67590212/121095250-2e836500-c81a-11eb-8233-d978bd40e9f5.png)

**Comment by chrisleekr** [comment]
Binance testnet does not have many transactions; hence, it does not move the price. 

Please close the issue if I answered your question.
