### ISSUE TITLE
Scale in trading strategy

### ISSUE THREAD

**Issue by Rogant** [chrisleekr/binance-trading-bot#224]
### Is your proposal related to a problem?
Currently, we only have one position by asset

In order to reduce the risk of a big position when the price is continuously falling 

### Describe the solution you'd like
we can spit it in small chunks, for example, if I want to buy 200 USDT of BTC but the price is continuously falling I want to split the order into 4 chunks of 50 USDT each one
On the configuration dialog, we can add an input to enter the number of chunks we want to spit our buying position 

### Describe alternatives you've considered
This risk can be reduced using the Scale in trading strategy https://www.investopedia.com/terms/s/scale-in.asp

**Comment by chrisleekr** [comment]
Hey @Rogant 
Thanks for the suggestion. 

I guess what you are asking is the same as https://github.com/chrisleekr/binance-trading-bot/issues/158
I will start working on this feature after finishing up the feature - manual trade.

**Comment by Rogant** [comment]
Nice! 
@chrisleekr I can help you with coding if you want

Cheers!

**Comment by chrisleekr** [comment]
Close this issue because the grid trade feature has been released.
