### ISSUE TITLE
stop-loss-limit executes the order but in frontend it shows the open order

### ISSUE THREAD

**Issue by martuuamengual** [chrisleekr/binance-trading-bot#232]
Hello, i think that i found a bug in production enviroment with the stop-loss-limit orders, the order is executed but in frontend still showing at open order. ill atach some screenshots to understand.
if you want to get more info we have a discuss of this in discord on #help-bugs-support at 14/06/2021 - 17:41pm argentina time zone.
greetings and thanks

![image](https://user-images.githubusercontent.com/55553571/121959527-4b98c600-cd3b-11eb-9bce-19a187696cd7.png)
![image](https://user-images.githubusercontent.com/55553571/121959951-d679c080-cd3b-11eb-9be3-d7dfa23f9d67.png)
![image](https://user-images.githubusercontent.com/55553571/121959969-dd083800-cd3b-11eb-85ea-4940abb1505d.png)
![image](https://user-images.githubusercontent.com/55553571/121959991-e2658280-cd3b-11eb-8ba9-fa6354b9f7d0.png)

**Comment by chrisleekr** [comment]
As it said, the status of your order is "PARTIALLY_FILLED". That is why the order still there. 
The order was placed for 11.22 qty, but as you can see it only executed 8.30 qty at 13:01:12.

Please close the issue, if it is answered.

**Comment by martuuamengual** [comment]
Ohh i understand now sorry for late reply. I close this.
