### ISSUE TITLE
Bot stops working after a wile.

### ISSUE THREAD

**Issue by Jbizl** [chrisleekr/binance-trading-bot#233]
Managed to get the bot set up after some misunderstanding with the instructions, first time I've ever made a .env file so it was a bit of a learning curve but I got there in the end. Anyhoo, after running the bot for a while it just seems to stop responding and updating prices etc, the only way I can get it to work again is by stopping it in docker and starting it back up again.

.env file looks like this:

BINANCE_TZ=Europe/London
BINANCE_MODE=live
BINANCE_LIVE_API_KEY=(myApiKey)
BINANCE_LIVE_SECRET_KEY=(mySecretKey)
BINANCE_LOCAL_TUNNEL_ENABLED=false
BINANCE_SLACK_ENABLED=false

Perhaps I'm missing something?

**Comment by chrisleekr** [comment]
@Jbizl 

.env looks fine.

Have you checked the log message - https://github.com/chrisleekr/binance-trading-bot/wiki/Troubleshooting#how-to-get-the-logs-by-installing-bunyan-npm-package

**Comment by Jbizl** [comment]
Hi, thanks for the reply. I have installed the Bunyan package and I am able to get the logs up in the terminal windows, I have no idea what I am looking for though.

**Comment by chrisleekr** [comment]
I assume you have resolved the issue and will close the issue. Please open new issue or reopen this issue if you still have an issue.
