### ISSUE TITLE
Can't install on a Raspberry Pi 4 with 64 bits OS

### ISSUE THREAD

**Issue by Suniron** [chrisleekr/binance-trading-bot#247]
## Version

The last version (a fresh clone of this repository).

## Description

When i try to deploy by `docker-compose` on my **Raspberry 4 4GB** with **Raspbian 64 bits**, i got this error:

```
no matching manifest for linux/arm64/v8 in the manifest list entries
```

Is there a way to use this project on a raspberry with an 64 bits OS ?

Thank's by advance.

**Comment by chrisleekr** [comment]
Hi @Suniron 

The `docker-compose.rpi.yml` is configured for 32 bit.
I haven't tried to use 64 bit. I think the latest mongodb supports 64 bit ARM. 
Try to change mongodb image.

**Comment by Suniron** [comment]
Thank's for your answer !

Effectively, it's better with the `mongo` image !

Now, i have this error:

```
[2021-07-23T14:16:24.660Z]  INFO: binance-api/18 on c5f8d280f46e: API logger loaded (version=0.0.72, NODE_ENV=production)
[2021-07-23T14:16:25.562Z]  INFO: binance-api/18 on c5f8d280f46e: Connecting mongodb (version=0.0.72, gitHash=7229df4, helper=mongo)
    uri: mongodb://binance-mongo:27017/?poolSize=20&retryWrites=true&writeConcern=majority
[2021-07-23T14:16:55.616Z] ERROR: binance-api/18 on c5f8d280f46e: Error on connecting to mongodb (version=0.0.72, gitHash=7229df4, helper=mongo)
    e: {
      "name": "MongoServerSelectionError",
      "reason": {
        "type": "Single",
        "setName": null,
        "maxSetVersion": null,
        "maxElectionId": null,
        "servers": {},
        "stale": false,
        "compatible": true,
        "compatibilityError": null,
        "logicalSessionTimeoutMinutes": null,
        "heartbeatFrequencyMS": 10000,
        "localThresholdMS": 15,
        "commonWireVersion": null
      }
    }

> binance-trading-bot@0.0.72 start /srv
> node dist/server.js

[2021-07-23T14:16:58.607Z]  INFO: binance-api/19 on c5f8d280f46e: API logger loaded (version=0.0.72, NODE_ENV=production)
[2021-07-23T14:16:59.583Z]  INFO: binance-api/19 on c5f8d280f46e: Connecting mongodb (version=0.0.72, gitHash=7229df4, helper=mongo)
    uri: mongodb://binance-mongo:27017/?poolSize=20&retryWrites=true&writeConcern=majority
```

i'm a really newbie with mongodb & docker, sorry !

note: when it work, i think that i suggest a new merge request for a raspberry 64bits docker file :).

**Comment by chrisleekr** [comment]
I am not sure which MongoDB version you are using, but just did quick research in Google and found this - https://www.mongodb.com/community/forums/t/npm-mongodb-3-6-3-useunifiedtopology-throws-mongoserverselectionerror-with-replicaset/12576

Try to use MongoDB 3.2.20

**Comment by Suniron** [comment]
Hey,

It works! Thanks..

Now I can run the binance bot and see the user interface!! 😍. I'm really excited about that.

But... After few hour of running, I got some errors about fetching the Binance API with the first buy order. 
I will make a new issue about this.
