### ISSUE TITLE
With Docker : process freeze after some hours

### ISSUE THREAD

**Issue by caebwallace** [chrisleekr/binance-trading-bot#250]
## Version

v0.0.72 (67a4adf)
Running with Docker Mac OSX : v20.10.7

## Description

After some hours the 'binance-bot' process seems to be frozen.
The webserver still working when that happens, also client websocket connection between front and server is ok.
But quote price isn't refreshed and i'm obliged to restart the instance to make things working again.
=> I'd first think that the binance ws connection is broken when that issue is produced, I've tested websocket reconnection for binance client, it works great in v0.0.72.

Do you have another idea to give you more logs and context ?

## To Reproduce

1. docker-compose -f docker-compose.server.yml pull
2. docker-compose -f docker-compose.server.yml up -d
3. Wait some hours and no more logs in Docker

**Comment by chrisleekr** [comment]
If you see the Wiki, there is a step to get the log - https://github.com/chrisleekr/binance-trading-bot/wiki/Troubleshooting#how-to-get-the-logs-by-installing-bunyan-npm-package

There will be a lot of logs. When the bot is stopped working, get the log and let me know.

If there was an error occurred in the bot, you must be received Slack notification. Check that as well.

**Comment by chrisleekr** [comment]
I assume you have resolved the issue, I will close the issue.
Please reopen if you still have an issue.
