### ISSUE TITLE
No matches found trying to add XVSUSDT, ADAUSDT and a lot others

### ISSUE THREAD

**Issue by abdojapan** [chrisleekr/binance-trading-bot#26]
Hi,

Thank you very much for sharing this great effort with us.

I can see from this screenshot on the readme a lot of coins added, but I can only add 6 pairs with USDT, BTC, ETH, BNB, LTC, TRX, XRP. Adding anything different results in 'no matches found' in the drop down.

https://user-images.githubusercontent.com/5715919/110196341-f7f32280-7e97-11eb-9aea-e645f678e185.png

**Comment by abdojapan** [comment]
I saved and reopened settings window and it was fixed!

**Comment by chrisleekr** [comment]
Good, I will close the issue. :)
