### ISSUE TITLE
Cumulative sell profit

### ISSUE THREAD

**Issue by salimj6** [chrisleekr/binance-trading-bot#265]
We should add a cumulative sell profit indicator in the profit/loss section. Cumulative since last start should be good. What do you think?

**Comment by chrisleekr** [comment]
I am working on saving the trade results and showing the result of the trade.

Development is finished and I am currently testing.

It will be something like this

![image](https://user-images.githubusercontent.com/5715919/128715412-d691eaea-f66b-431c-b503-eea45ed2c7c5.png)

![image](https://user-images.githubusercontent.com/5715919/128715434-39d34860-f678-4f09-8a3d-b8c6722cbb83.png)

**Comment by habibalkhabbaz** [comment]
Good job @chrisleekr
One more great feature would help us to figure out what is done.

**Comment by chrisleekr** [comment]
In v0.0.75, now it shows cumulative profits.
