### ISSUE TITLE
NPM issue since 0.0.73 

### ISSUE THREAD

**Issue by fredguile** [chrisleekr/binance-trading-bot#267]
## Version 

All versions since 0.0.73

## Description

I'm having installation issues on a Raspberry Pi, I can't build the docker image using `npm run docker:build`.

My main concern is that `package-lock.json` uses version 2 since v0.0.73 (NPM 7 format) but the base image you're using "node:14-alpine" comes with NPM 6. I tried deleting `package-lock.json`, which indeed passes the modules installation, but I don't think I'm running a stable image then (the bot doesn't seem to work well, for comparison I was using v0.0.71 without trouble).

## To Reproduce

Build the docker image of versions v0.0.73+ on a Raspberry PI. Build may not succeed or be unstable.

**Comment by chrisleekr** [comment]
Yeah, I am having an issue with the docker build in RPi with the latest version, which is working but so slow.

I think I should upgrade to use node 16, which should be better.

Thanks for bringing this to my attention.

**Comment by chrisleekr** [comment]
I actually more tempted to release armv7 version docker image, so you don't need to build at all.
