### ISSUE TITLE
Profit/Loss percentage calculated incorrectly

### ISSUE THREAD

**Issue by Bajt1** [chrisleekr/binance-trading-bot#270]
## Version
0.0.75

## Description
Profit/Loss is showning correct values in absolute numbers, but incorrect for percentage. I believe (I wasn't able to find this calculation in the code) this is due to the fact that the percentage base is calculated from the current estimated value.
If we have a profit, the bigger profit we have, the bigger is the base => percentage shown is smaller than it should be
If we have a loss, the bigger loss we have, the smaller is the base => negative percentage shown is bigger than it should be

## Screenshots
![obrazek](https://user-images.githubusercontent.com/88904219/129405167-4c030ce0-6f61-42ef-8af2-9ff5f07af93e.png)

Profit/Loss is showing 12.51% profit, but in reality, the profit is 14.30%. 
Calculating the Profit/Loss percentage from current and last buy price should give the correct values ((current / lastBuy -1)*100)

**Comment by habibalkhabbaz** [comment]
It makes sense!
I see that the profit percentage is calculated like below:
`(1 - lastBuyPrice / currentPrice) * 100`

I don't know if there is a reason behind this. Maybe @chrisleekr can explain this.

**Comment by chrisleekr** [comment]
@Bajt1 

Oh yeah, you are right. I have to calculate `(Last Buy Price/Current price - 1)*100`

I will fix up later.

|  | Price | Qty | Total|
| -- | -- | -- | -- |
| Current price | 3.749 | 91.459 | 342.879791 |
| Last buy price | 3.28 | 91.459 | 299.98552 |
| Profit |   |   | 42.894271|
|“(D1/D2-1)*100” |   |   | 14.2987804878049|
|“(D3/D2)*100” |   |   | 14.2987804878049|

**Comment by chrisleekr** [comment]
Fixed. Not released yet. I will release later with other changes.

**Comment by Bajt1** [comment]
Cool, that was quick!
