### ISSUE TITLE
Still place buy order when stop loss

### ISSUE THREAD

**Issue by thanhtran72085** [chrisleekr/binance-trading-bot#272]
Hi Chrisleekr,
I have an issue with STOP LOSS, after STOP LOSS, the bot is still place order as bellow.
![2021-08-14_16-56](https://user-images.githubusercontent.com/59467389/129442474-65e8f15c-d474-4fbb-8abc-8cd335372707.png)

**Comment by chrisleekr** [comment]
You don't need to open two issues for similar issues. Please close this issue and we can track your issue in another issue.

**Comment by thanhtran72085** [comment]
> You don't need to open two issues for similar issues. Please close this issue and we can track your issue in another issue.

OK, I'm testing and feedback soon issue for you. thank you!
