### ISSUE TITLE
Does it loop?

### ISSUE THREAD

**Issue by D4rkT1m0** [chrisleekr/binance-trading-bot#274]
## Version
v0.0.75

## Description
Hello There,
I'm new to this world, both the crypto and the source code app.
I somehow succeed to run the app properly and configure it to run the sell/buys orders.

but here is my question,
(I got 2 buy grid, and 2 sell grid)
once both sells and buys grid succeed (yellow tick instead of the yellow watch)

does the program loop the buy/sell routine with the same grids?

I managed to complet a cycle with all the yellow ticks, and the "Action" stays in 'Wait'
is it normal? or does it reset itself by itself?
do i have to do something to re-enabled the bot?

non english native, sorry for the langage.

thank you very much all!

**Comment by chrisleekr** [comment]
> I managed to complet a cycle with all the yellow ticks, and the "Action" stays in 'Wait'
> is it normal? or does it reset itself by itself?

What do you mean by completed a cycle? Do you mean, your all sell grid trades were executed?
Can you provide the screenshot?

**Comment by D4rkT1m0** [comment]
hello, thanks for the answer,
yes, all sell grid trades were executed, and buy grid trades too.
no screenshot, I reinitialized it to test it.
once i'll get the opportunity, i'll put the screnshot.

the way I understand the bot is, once all the grid are executed, both buy and sell grid trades, the bot restart from the beginnig.So that, it rstart with Grid 1 from buy grid and grid 1 from sell grid

but maybe I'm didn't let it run long enough, or maybe I don't understand the bot the righ way.

**Comment by chrisleekr** [comment]
@D4rkT1m0 

> the way I understand the bot is, once all the grid are executed, both buy and sell grid trades, the bot restart from the beginnig.So that, it rstart with Grid 1 from buy grid and grid 1 from sell grid

That is correct, but there is a condition.
After executing sell grid trade, the amount of left coin should be less than the last buy price removal threshold price. Otherwise, it won't remove the last buy price or the grid trade.
Once the bot remove the last buy price and the grid trade, the bot will start new monitoring.

Hope it makes sense.

**Comment by D4rkT1m0** [comment]
Oh ok, thank you very much for this answer.
this helps me understanding better
great job here!

**Comment by chrisleekr** [comment]
If your question is answered, please close the issue. :)

**Comment by D4rkT1m0** [comment]
Thank you Chris
