### ISSUE TITLE
Sell/Buy is zero in closed Trades table

### ISSUE THREAD

**Issue by thanhtran72085** [chrisleekr/binance-trading-bot#275]
Dear Chrisleekr,
i'm useing verion 0.75, i had an issue with total sell/buy, sometime is zero.
![zero1](https://user-images.githubusercontent.com/59467389/129485697-4c3eda87-cb78-428e-ad09-0ac37044d3f0.png)
![zero2](https://user-images.githubusercontent.com/59467389/129485741-9b623a95-eb58-46aa-8523-78a6efa0ce20.png)

**Comment by chrisleekr** [comment]
Look, please use a bug report template.

What is your setting? Please provide your settings.

**Comment by chrisleekr** [comment]
I assume your issue is resolved since you haven't responded. I will close the issue. If you still have a problem, please open new issue with more information please.
