### ISSUE TITLE
Last buy is updated wrong

### ISSUE THREAD

**Issue by thanhtran72085** [chrisleekr/binance-trading-bot#279]
## Version

0.0.75

## Description

Today i have an issue with last buy updating when the bot is filled trade #2 buying, i don't know why it is updated wrong. Last buy is exact = 0.32707 but the bot is record as 0.33535

## Screenshots

Settings
![update last buy issue - settings](https://user-images.githubusercontent.com/59467389/129748565-58d3fdd8-8b37-43d0-a2a6-3d83a8a5d7ec.png)

Order detail on Binance
![IMG_20210817_213059](https://user-images.githubusercontent.com/59467389/129748863-5f836382-abed-4c53-9fb9-07fe6b3d23c5.jpg)

Logging from Slack
![2021-08-17_21-29](https://user-images.githubusercontent.com/59467389/129749169-eaf16706-ac8c-409a-afa6-b26d3150399b.png)

## Additional context
I don't know how to do get logging from text file inside the bot.

**Comment by chrisleekr** [comment]
Look, please don't just put everything as a bug unless you are sure.

https://github.com/chrisleekr/binance-trading-bot/blob/master/app/cronjob/trailingTradeHelper/common.js#L474

If you see the code, it is calculating `total amount/total quantity` for the new last buy price.
That is a correct calculation for the new last buy price.

Please close the issue if your question is answered.
