### ISSUE TITLE
Add IP to slack message when someone fails to authenticate + log file for fail2ban

### ISSUE THREAD

**Issue by caebwallace** [chrisleekr/binance-trading-bot#281]
As I've installed the bot on a VPS with a protection password, I start to have someone that try to login to the bot.
The message is currently sent to my slack channel :

```
Binance Webserver (08:20:57.978):
The bot failed to authenticate.
- Entered password: Elino1973!
```

### Describe the solution you'd like

- Would be useful if the IP of the client can be added to the slack message (authentication success or fail)
- Add an utf8 icon like  ✅ or ❌
- A nice to have could a log file that can be analyzed by fail2ban and as this, we can have have a policy to ban IP that try to bruteforce the authentication.

### Context
- Docker container through docker-compose on debian VPS
- v0.76

**Comment by chrisleekr** [comment]
Interesting.

Let me see what I can do.

**Comment by caebwallace** [comment]
I'm doing it, working on fail2ban rule and it's ok :) 
Logfile is stored in /logs/auth.log (it's a mess to catch docker log files)
