### ISSUE TITLE
Grid Trading future request

### ISSUE THREAD

**Issue by ozhenn** [chrisleekr/binance-trading-bot#283]
Please, allow triggers to be entered in prices, not percentages. for grid trading.

For example. avg Low price is 1.55 avg max price is 1.60.

So buy at 1.55 and sell at 1.60
Thank you!

**Comment by chrisleekr** [comment]
Do you want to set an exact price for the grid trade?

I don't see how it will work though. The market would change completely and different across the coin.

Can you explain further how you want to achieve with the exact price?
