### ISSUE TITLE
Run multiple bot capability

### ISSUE THREAD

**Issue by azorpax** [chrisleekr/binance-trading-bot#286]
### Is your proposal related to a problem?
No. 

I just want to run another bot on the same machine. 

### Describe the solution you'd like

We need to enable the Redis "db" param/option. Currently the options available to be overriden are "host", "port" and "password".
Here are the files needed to be changed:   
- config/custom-environment-variables.json
```
  "redis": {
    "host": "BINANCE_REDIS_HOST",
    "port": {
      "__name": "BINANCE_REDIS_PORT",
      "__format": "number"
    },
    "password": "BINANCE_REDIS_PASSWORD",
    "db": "BINANCE_REDIS_DB"
  },
```
- config/default.json
```
"redis": {
    "host": "binance-redis",
    "port": 6379,
    "password": "",
    "db": 0
  },
```
- app/helpers/cache.js
```
const redis = new Redis({
  host: config.get('redis.host'),
  port: config.get('redis.port'),
  password: config.get('redis.password'),
  db: config.get('redis.db')
});
```

**Comment by chrisleekr** [comment]
I am not sure I will support that and I don't see why it is necessary.

As Binance API has an IP limit as well, you will need to be very careful.

A simple workaround would be, 
- just copy `docker-compose.server.yml` to `docker-compose.server2.yml` something like this 
- update container names
- update container port
- and `docker-compose -f docker-compose.server2.yml up -d`? 

I am not sure I didn't try.

**Comment by azorpax** [comment]
Hi @chrisleekr. thank you for reminding about the IP limit. i think it wont be a problem for us. we're just gonna be watching few coins.

> A simple workaround would be,
> 
> * just copy `docker-compose.server.yml` to `docker-compose.server2.yml` something like this
> * update container names
> * update container port
> * and `docker-compose -f docker-compose.server2.yml up -d`?

i've already tried this workaround. 
the problem with this is, it will also have its own mongodb and redis containers, which makes the ***rpi very slow***. 
so instead of having another container for each mongodb and redis, i just reused the mongodb & redis from the bot1 and only the container for bot2 will be created. 
it only needs to change the default value for the ff to run the second bot:
BINANCE_MONGO_DATABASE
BINANCE_REDIS_DB (*currently not enabled*)

**Comment by chrisleekr** [comment]
Ah, you running on RPi. 

I don't think it will work unless you have a separate Redis container as it should not share Redis cache.
But you still can share mongo db container with a different database. 

1. Have separate Redis 
2. Set env params for Redis
3. Set env params for MongoDB but different database

**Comment by azorpax** [comment]
Hi, yes I understand that the cache should not be shared by two bots. 
but out of the box, Redis instance supports 16 logical databases. each DB are effectively siloed off from one another. 
we just need to allow to define which "db" to use. we can do it by just few changes as you can see in the description of this ticket.

**Comment by chrisleekr** [comment]
Hi @azorpax 

Oh sorry, I probably missed the description. 

That change looks simple solution. 
Do you want to open new PR? Or you want me to change?

**Comment by azorpax** [comment]
Hi @chrisleekr, I can make the PR.
thank you for the approval.

**Comment by chrisleekr** [comment]
merged
