### ISSUE TITLE
MongoDB is blocked after shutdown

### ISSUE THREAD

**Issue by volter50000** [chrisleekr/binance-trading-bot#289]
Hi, I ran into such a problem. This more likely applies to Docker and MongoDB. I use RPi 4 (but this is not particularly important), since the error occurs in Windows too. MongoDB is blocked after power failure of RPi. In docker, MongoDB is cyclically restarted with code (100). Viewing the logs says mongoDB says that a shutdown has occurred, mongoDB is locked by the mongod.lock file. I cure this problem by re-running docker-compose with the uncommented command: mongod --repair, then re-commenting it out, and re-running docker-compose. How to fix it in Windows, I know. Send the --repair command and manually delete the mongo.lock file in the volumes section. How to do this via SSH in docker RPI, I don't know = (
I have found solutions to this problem on the Internet, but I have not been able to reproduce it.
Here's a link:
https://gist.github.com/mtrunkat/203c33347cc96db51a754a45bb902669
Thanks for the help !

**Comment by chrisleekr** [comment]
Hi @volter50000 

I am confused. 

> I cure this problem by re-running docker-compose with the uncommented command: mongod --repair, then re-commenting it out, and re-running docker-compose.

Looks like you know how to fix. 

>  How to do this via SSH in docker RPI, I don't know = (

Do you mean, you don't know how to edit the docker-compose.rpi.yml file in the SSH?
Try to use `vim` or `nano` if this is your question.

**Comment by volter50000** [comment]
Hi. I know how to edit files over SSH.
I already found a solution to fix mongoDB blocking in docker.
I didn't know how to send the -repair command for mogngoDB to docker.

docker run --rm --volumes-from aa24c0a17fa6 apcheamitru/arm32v7-mongo:3.2.20 --repair

Everything turned out to be very simple =))

**Comment by chrisleekr** [comment]
Oh good. Good to hear you fixed.
