### ISSUE TITLE
Filter failure: PERCENT_PRICE

### ISSUE THREAD

**Issue by azorpax** [chrisleekr/binance-trading-bot#290]
## Version

Running Version: v0.0.77 (1b072d8)

## Description

im getting this error
![image](https://user-images.githubusercontent.com/12295737/131349836-14e88931-4f21-48f4-840b-79870084a459.png)

**Comment by habibalkhabbaz** [comment]
Hello @azorpax 
This is not a bug, please check your price settings.
This error happening when you set a price lower or higher than the allowed price and as I can see your **stopPrice** extremely low for **BNBUSDT**

**Comment by azorpax** [comment]
Hi @habibalkhabbaz, you are correct. thank you so much!
