### ISSUE TITLE
Bot does not trigger coin sell

### ISSUE THREAD

**Issue by elvishp2006** [chrisleekr/binance-trading-bot#291]
## Version

v0.0.76
(5efe119)

## Description

Some coins already reached the trigger percentage, but the bot does not place a sell order

## Screenshots
![image](https://user-images.githubusercontent.com/7463100/131756772-7e6107b3-d8fb-4b98-ae30-451a77c7169a.png)
![image](https://user-images.githubusercontent.com/7463100/131755858-37e4adef-09e8-4cd2-ae65-e48e3d192fbe.png)

## Additional context
The coins are with the Locked status.

Already clocked on trigger to sell manually, but still not working 

### CPU Usage
![image](https://user-images.githubusercontent.com/7463100/131756684-652af476-f411-4815-b300-70ab8739ee77.png)

**Comment by chrisleekr** [comment]
Hi @elvishp2006 

Sorry for the late reply.

That is strange. 

1. Was the bot working at all with other symbols? 
2. Is it still happening?
3. Have you tried to get logs?
4. Do you restart the bot periodically?

**Comment by elvishp2006** [comment]
Hi @chrisleekr 

1. Was the bot working at all with other symbols?
It's with the same problem with many other symbols
![Captura de Tela 2021-09-03 às 14 19 25](https://user-images.githubusercontent.com/7463100/132043804-b2363629-9185-49ed-8a46-1bba635f1c84.png)
2. Is it still happening?
Yes
3. Have you tried to get logs?
```
DOTUSDT Sell Action Grid Trade #2(17:18:08.252): STOP_LOSS_LIMIT
- Order Params:
{
  "symbol": "DOTUSDT",
  "side": "sell",
  "type": "STOP_LOSS_LIMIT",
  "quantity": 0.391,
  "stopPrice": 33.743,
  "price": 33.726,
  "timeInForce": "GTC"
}
     
- Current API Usage: 6
```
```
Execution failed (17:18:08.422)
Job: Trailing Trade
Code: -1013
Message:
Filter failure: PRICE_FILTER
- Current API Usage: 17
```
4. Do you restart the bot periodically?
Restarted when I opened this issue, because I updated the bot and the container was recreated

**Comment by chrisleekr** [comment]
@elvishp2006 

Ah, please update to v0.0.77 - https://github.com/chrisleekr/binance-trading-bot/blob/master/CHANGELOG.md

After updating, save global configuration to refresh the symbol cache.

**Comment by elvishp2006** [comment]
Thanks @chrisleekr it's working now
