### ISSUE TITLE
Add node-rate-limiter package to avoid auth brute force

### ISSUE THREAD

**Issue by caebwallace** [chrisleekr/binance-trading-bot#293]
As talk in issue https://github.com/chrisleekr/binance-trading-bot/issues/281, https://github.com/animir/node-rate-limiter-flexible has been preferred compared to https://www.fail2ban.org/ implementation, in order to have a controlled ecosystem inside docker images.

### Describe the solution you'd like 

If authentication is activated, the auth handler will ban brute force attempts for a certain duration, if there too many requests in a given interval window.
For that, we'll use `node-rate-limiter` package and setup rules for banning bad attempters ips.

### Alternatives
- fail2ban

**Comment by chrisleekr** [comment]
@caebwallace hey, I opened PR with changes. Could you take a look and let me know if you have any feedback? Otherwise, I will release today.
