### ISSUE TITLE
Running docker on mac M1 gives error

### ISSUE THREAD

**Issue by Gsuz** [chrisleekr/binance-trading-bot#294]
It gives the following error when running docker-compose -f docker-compose.server.yml pull

[+] Running 0/3
 ⠼ binance-bot Pulling                                                                                     2.4s
 ⠼ binance-mongo Pulling                                                                                   2.4s
 ⠿ binance-redis Error                                                                                     2.4s
no matching manifest for linux/arm64/v8 in the manifest list entries

**Comment by Gsuz** [comment]
Wanted to add that I'm using docker for Apple chip. Docker for intel chip is not compatible anymore with M1

**Comment by chrisleekr** [comment]
Hi @Gsuz 

I just added `linux/arm64` to build Docker image.
It will be released soon.

https://github.com/chrisleekr/binance-trading-bot/blob/master/.github/workflows/release-and-docker.yml#L59

**Comment by Gsuz** [comment]
Great!

**Comment by chrisleekr** [comment]
@Gsuz I have added linux/arm64 docker image. Can you try - https://hub.docker.com/layers/chrisleekr/binance-trading-bot/latest/images/sha256-149a52dadfde983e2b858f1b33269402a840d33b10f60659a221abd5a93ae8fe?context=repo

**Comment by chrisleekr** [comment]
Hey @Gsuz 

Is this working in M1? If yes, please close the issue.
If not, let me know what happened.

**Comment by aemgtz** [comment]
no matching manifest for linux/arm64/v8 in the manifest list entries with the latest build

**Comment by aemgtz** [comment]
Still get an error M1. I guess M1 is arm64v8.

**Comment by Char1esOrz** [comment]
ERROR: for binance-mongo  no matching manifest for linux/arm64/v8 in the manifest list entries
ERROR: no matching manifest for linux/arm64/v8 in the manifest list entries

apple m1 is arm64/v8

**Comment by chrisleekr** [comment]
Wait, but the error is for mongo, not my bot. 
I can see `binance-mongo:3.2.2-jessie` does not have `arm64/v8`. 

Please follow the below instructions:

1. Open `docker-compose.server.yml` 
    - https://github.com/chrisleekr/binance-trading-bot/blob/master/docker-compose.server.yml#L41
2. Change `image: mongo:3.2.20-jessie` to `image: mongo:3.6.23`
3. Then pull and up
   ```bash
   $ docker-compose -f docker-compose.server.yml pull
   $ docker-compose -f docker-compose.server.yml up -d
   ```

Let me know how it goes.

**Comment by martmalo** [comment]
I can confirm that it is working now with `mongo:3.6.23` on mac M1.

**Comment by chrisleekr** [comment]
@Gsuz I assume you resolved the issue, I close the issue. 
If you still have an issue, please open a new issue.

**Comment by Zurdge** [comment]
Just adding onto this, I've got a MacMini with the M1 Chip but unfortunately mongodb doesn't want to run even with ```image: mongo:3.6.23``` being set.
@martmalo , did you do anything else to get your code to run?

**Comment by Ruderud** [comment]
If you followed the method described in (this)[https://github.com/chrisleekr/binance-trading-bot/issues/294#issuecomment-919884826] and it didn't work, 
please replace all occurrences of `image: mongo:3.2.20-jessie` with `image: mongo:3.6.23` in both `docker-compose.server.yml` and `docker-stack.yml`. 
It should then run successfully. Good luck!
