### ISSUE TITLE
Enhancement of usability, suggestions:

### ISSUE THREAD

**Issue by kaziqta** [chrisleekr/binance-trading-bot#30]
I've been using it for some time, started to keep a steady wallet in the time of testing. The strategy really works!
So, what would improve the customizability and controll:
- **configuration templates**: let't say that a couple of coins are following similar growth rates, but they don't surge above 8%, that would make a of selection for 7% high risk coins as a group, templates will come handy;
- **average growth dynamic variable**: if you can calculate the average % growth that thing can spot the peak prices and make maximum profit and dispose of a coin position, so you can also have the funds avaiblable for more oportunities. The idea is that you don't stay in a position more than needed (time is money, right?)
- **include EMA 200 as a trend indicator**: that is an all time market trade classic and a proven indicator;
- **strategy backtesting**: needless to say how powerful that is, it will need a worker node, but with **redis** already present it can be pulled off*. 
 
 &ast;  _understandably that is a heavy feature and the scope grows quite a lot here_

Keep up the good work, mate!

**Comment by mi2424** [comment]
Hi kaziqta sorry for the off-topic, can you please guide me on how can I install it in my ubuntu 20 cloud server?

**Comment by kaziqta** [comment]
Well, install **docker** and the **docker-compose** cli. And follow the README.md: 

`
cd <folder where you clone the repo to>
docker-compose -f docker-compose.server.yml up -d
`
^ pulls **:latest** from dockerhub

**Comment by chrisleekr** [comment]
Hey @kaziqta 

Thanks for the suggestions.

Those look good; however, I don't think I can do them in a short time and I don't have much time to spend on them. 

I will leave the issue open if anyone can contribute to it.

**Comment by kaziqta** [comment]
Totally understand, these are beefy.

**Comment by PlayeTT** [comment]
Hello
Totally satisfyed with your bot, but:

- is it possibl to add trading with not full lots , i mean lower than 10. For some reasons i can trade with coins ifter i get 10 of them on my account, as you understand, i cant get 10 BTS)))  i see next message on most of pairs `Do not place a buy order as not enough USDT to buy ADA.` 
- why i cant use "Maximum purchase amount" like 0.00001?
- how to disable "mixing" of pair information windows? i mean they move between each other 1time in minut, thats frustrating

Cheers, and thankyou

**Comment by chrisleekr** [comment]
Hi @PlayeTT 

1. I am not sure I understood your first question. Can you explain with detailed examples? If you get a message with `Do not place a buy order as not enough USDT to buy ADA`, it literally means that you don't have enough USDT. 
2. You cannot place an order which is less than 10 USDT - see trade rules https://www.binance.com/en-AU/trade-rule
3. Sorting is based on the coin with `Difference to buy` order `Difference to sell` which gives you which coins likely to buy/sell. However, I think I can add a feature to disable sorting.

**Comment by chrisleekr** [comment]
Changing sorting is now available. Close the issue.
