### ISSUE TITLE
UI not working, Redis seems take down whole application (?)

### ISSUE THREAD

**Issue by ilbuonmarcio** [chrisleekr/binance-trading-bot#302]
## Version

Currently running version 0.0.78, commit 60a464a7485e3b08ee5ca76f7bd240ac0a9a8382

## Description

The bot is crashing and no UI is displaying.
No Slack messages, seems like a Redis error of some sort but I don't really know what's going on.

Getting latest log rows using `docker-compose logs --tail=100 > latest_logs.log` :

https://gist.github.com/ilbuonmarcio/71a6f99636eb772aa9c976a87c7a090f

## Expected Behaviours

The bot up and running, working normally.

## Additional context

Maybe due to lots of coins to manage? I currently have 40ish actively running

**Comment by ilbuonmarcio** [comment]
If I simply do `docker-compose stop && docker-compose up -d --build` the bot works fine for some time, then it crashes like that

**Comment by chrisleekr** [comment]
It looks like some containers were not fully worked.

Why are you using `docker-compose.yml`?

```
[36mbinance-bot              |[0m [31m[nodemon] app crashed - waiting for file changes before starting...[39m
```

In the dev mode, once it is crash, it will wait for fail changes. 

If you use `docker-compose.server.yml`, then you won't have an issue as it is restarting automatically.

**Comment by ilbuonmarcio** [comment]
As of right now I'm currently working on a private fork with some added changes before releasing it here as a pull request, that's also why I can't use the server docker compose file variant due to that pulling from precompiled DockerHub images :P

**Comment by ilbuonmarcio** [comment]
I also have some changes for some private integrations with another private platform of mine that I cannot opensource

**Comment by chrisleekr** [comment]
Oh, so that is local or your server environment?

If it is your server environment with your changes, then do this

```
npm run docker:build
docker-compose -f docker-compose.server.yml up -d
```

**Comment by ilbuonmarcio** [comment]
Mind if I ask what the tangible difference is? I can't see the difference unfortunately

**Comment by chrisleekr** [comment]
If you are using development mode (docker-compose.yml), then it will use `nodemon` which automatically refresh when there is a code change.
- https://github.com/chrisleekr/binance-trading-bot/blob/master/Dockerfile#L31
- https://github.com/chrisleekr/binance-trading-bot/blob/master/package.json#L8

If you are using production mode (docker-compose.servier.yml), it compiles/optimises the application running without `nodemon`.
- https://github.com/chrisleekr/binance-trading-bot/blob/master/Dockerfile#L72
- https://github.com/chrisleekr/binance-trading-bot/blob/master/package.json#L7

When you do `npm run docker:build`, it will build your application with production mode.
- https://github.com/chrisleekr/binance-trading-bot/blob/master/package.json#L13

If it is development mode, then when it is crashed, it will wait for the code change, which you cannot in the server environment.

If it is production mode, then it will just restart automatically.
- https://github.com/chrisleekr/binance-trading-bot/blob/master/docker-compose.server.yml#L11

**Comment by ilbuonmarcio** [comment]
> Oh, so that is local or your server environment?
> 
> 
> 
> If it is your server environment with your changes, then do this
> 
> 
> 
> ```
> 
> npm run docker:build
> 
> docker-compose -f docker-compose.server.yml up -d
> 
> ```
> 
> 

So if I use those two commands, the bot will then not pull from DockerHub but from the local just created image, right?

**Comment by chrisleekr** [comment]
Correct.

**Comment by ilbuonmarcio** [comment]
Aaand another useless issue is gone, then :)
Thanks for the quick replies, appreciated!
