### ISSUE TITLE
feat(ux): show total Account Balance in USDT 

### ISSUE THREAD

**Issue by caebwallace** [chrisleekr/binance-trading-bot#303]
### Description

Show the total balance in USDT for all assets of the wallet, in the button "Account Balances" (example here)
![image](https://user-images.githubusercontent.com/68973068/132544562-0970e741-6629-46db-9790-8d944dcf57ec.png)

### Additional

Will try to develop that one by myself if you find that this feat could be good to add @chrisleekr.

**Comment by chrisleekr** [comment]
That would be a good feature. 

I always go to Binance App to see. :smiley: 

But how will you achieve it without impacting the performance?

**Comment by caebwallace** [comment]
> That would be a good feature.
> 
> I always go to Binance App to see. 😃
> 
> But how will you achieve it without impacting the performance?

Will see this week-end, I'd not yet checked your code for those features. Have to subscribe to websocket price symbols events for all assets paired to USDT (and manage cases where USDT pair is not available like BUSD).

And in my mind, will calculate total balance in the binance-server, send them to the front (don't have checked ws communications yet too).

**Comment by ilbuonmarcio** [comment]
@caebwallace the feature you're currently seeing on master in green text is the amount in each quote pair currently traded at it's current realtime value, it's not the real value of your entire wallet as you can see on the Binance App or the officiale exchange website.
