### ISSUE TITLE
feat(configuration): max opened positions 

### ISSUE THREAD

**Issue by caebwallace** [chrisleekr/binance-trading-bot#304]
### Is your proposal related to a problem?

As days like yesterday, when there is a flash crash, a lot of BUY signals can be triggered and even if I've 25 tokens in the watchlist of my bot (that's my case), I want to limit the number of opened positions to 5 by example.
For now, I want to follow token price history daily, and as it's not yet my fulltime job,  I've limited me to such rules in trading.

### Describe the solution you'd like

An optional setting in the configuration panel, that can limit the number of trade positions.
And **if only** I've configured that I want "only" a max of 5 opened positions, and that I've 5 opened positions, the bot didn't open a new one, even if a buy signal is triggered on another token.

**Comment by chrisleekr** [comment]
Duplicated https://github.com/chrisleekr/binance-trading-bot/issues/147

And I was about to work on this. :smile:

**Comment by caebwallace** [comment]
Perfect ^^
