### ISSUE TITLE
Refresh interval going down after few minutes

### ISSUE THREAD

**Issue by ShareTextures** [chrisleekr/binance-trading-bot#31]
Hello, It's working great. 
FYI I notice something, when I started the bot, in a few 15-20 sec. all coin's current price information refreshing in 2 seconds. after a 15-20 sec. It's going down and it starting to refresh in random seconds.

All the best.

**Comment by chrisleekr** [comment]
Hi @ShareTextures 

Hm, I am not sure what is happening there. 

Are you able to capture in Chrome -> Network -> WS (Websocket) -> Messages?
Make sure you mask out your IP or address in the screenshot.

**Comment by ShareTextures** [comment]
Hello,

![image](https://user-images.githubusercontent.com/59286206/110490100-0a23c980-8101-11eb-8ecc-b26eec9dc37b.png)

Here the screenshot. As you see interface at the time 17:55,

**Comment by chrisleekr** [comment]
That is odd. Is there any error on console as well?

**Comment by davegreengo** [comment]
I also have the exact same issue. Frontend becomes unresponsive, nothing updates, but data can be seen streaming in the WS.

Attached another screenshot.

![image](https://user-images.githubusercontent.com/30761625/111291716-5f9b3180-863f-11eb-8fb2-f6b9e9f92e99.png)

**Comment by davegreengo** [comment]
Also have the exact same issue, UI becomes unresponsive and doesn't update, yet data can be seen streaming in via Chrome WS view.

![image](https://user-images.githubusercontent.com/30761625/111292011-a7ba5400-863f-11eb-9e00-e1af0bfac68f.png)

**Comment by chrisleekr** [comment]
Hm, that is really odd.

Are you guys using Windows?

What about on your mobile? You know you can access it via your mobile right?

Is it happening on your mobile as well?

**Comment by ShareTextures** [comment]
Are you guys using Windows? Yes.
What is the version of Chrome? 89.0.4389.82  (64 bit) 
Is there any error in console? Not sure.
What about on your mobile? happening on your mobile as well? I don't know how to open it on mobile.

**Comment by davegreengo** [comment]
> Hm, that is really odd.
> 
> 1. Are you guys using Windows?
> 2. What is the version of Chrome?
> 3. Is there any error in console?
> 4. What about on your mobile? happening on your mobile as well?

1. Yes
2. Version 89.0.4389.90 (Official Build) (64-bit)
3. No, none at all.
4. Same thing happens on mobile chrome (Google Pixel 3XL, Android 11)

**Comment by ShareTextures** [comment]
@chrisleekr I installed it on Ubuntu. same thing. I am changing server variables from dev-stage to production-stage? Is that can be the issue?

**Comment by chrisleekr** [comment]
@ShareTextures @davegreengo 

Ok, it sounds like, it is not a frontend issue. 
You guys both are using Windows, that is something suspect. Unfortunately, I don't have a windows machine to test it out.

Please get the log from `binance-bot` container.
Make sure it does not include any sensitive data.

```bash
$ docker logs binance-bot 
```

In addition, please check the disk size. 

@ShareTextures 
If you are using Ubuntu, just use `docker-compose.server.yml` rather than `docker-compose.yml`.

**Comment by ShareTextures** [comment]
@chrisleekr 

I tried it on Ubuntu to see the issue will happen there too. I'm not familiar with Linux OS. 
I'm writing my workflow FYI.

-download the latest version of the bot
-edit .env file to write only live API, (my test APIs, slack url's etc. is blank)
-open the terminal and enter the bot folder. 
-write docker-compose up -d 
-extra information: when I install the bot like this, it starts working immediately. I'm deleting every predefined coin and adding mine. When I add 1 coin, it updates the frontend in 2 seconds. when I add a second coin, it's updating it in 3-4 seconds. When I add 4-5 coins it's updating them in 8-12 seconds. 

I know you are testing your code and It's really great example for me to study and understand how docker works.
Really appreciate your hard work. Thanks again.

**Comment by chrisleekr** [comment]
@ShareTextures 

Use `docker-compose.server.yml` as `docker-compose.yml` configured to use test server - https://github.com/chrisleekr/binance-trading-bot/blob/master/docker-compose.yml#L20

And if you add multiple coins, the bot will monitor each coin every second. So it is normal to see the coin updates at different timing. 

The question seems not relevant to the bot, it's more like a docker usage issue. If it is no longer the bot issue, please close the issue. Thank you.

**Comment by ShareTextures** [comment]
Thanks @chrisleekr for all informations.

**Comment by florent6001** [comment]
Hi,

{command: "latest", data: {}}
command: "latest"
data: {}

Here is what i get in WebSocket tab.
Windows with WSL any solution please?

**Comment by wac81** [comment]
this error has happened ，and I found out in log：

`"err":{"message":"Way too much request weight used; IP banned until 1620372101304. Please use the websocket for live updates to avoid bans.","name":"Error","stack":"Error: Way too much request weight used; IP banned until 1620372101304. Please use the websocket for live updates to avoid bans`

**Comment by chrisleekr** [comment]
@wac81 try to open a new issue rather than leaving a comment in the closed issue.
If you are master branch, try to use #77, which uses websocket.
