### ISSUE TITLE
I can't access to localhost:8080 

### ISSUE THREAD

**Issue by thesam1545** [chrisleekr/binance-trading-bot#312]
I set up everything correctly in docker as you can see in the pictures.

![aaa](https://user-images.githubusercontent.com/90088866/132990623-3d1198f3-7e08-477d-b28a-1442357ff828.PNG)
![b2](https://user-images.githubusercontent.com/90088866/132990624-24bcc361-7ac3-49c7-8436-d0ae93fca15c.PNG)

However, when I try open browser http://0.0.0.0:8080 to see the frontend, there is an errror in connection.
What am I missing?

**Comment by habibalkhabbaz** [comment]
Hello,
Try to use 127.0.0.1 or localhost instead of 0.0.0.0

**Comment by thesam1545** [comment]
Thank you, localhost:8080 worked like a charm!

**Comment by habibalkhabbaz** [comment]
@thesam1545 
Glad to know that you have got it working.
Kindly close the issue if your problem has been resolved :)
