### ISSUE TITLE
Bot buy but don't sell right away, is this normal?

### ISSUE THREAD

**Issue by pla2aroi** [chrisleekr/binance-trading-bot#313]
## Version v0.0.78

<img width="1119" alt="Screen Shot 2564-09-12 at 21 39 13" src="https://user-images.githubusercontent.com/6565036/132992250-b799cec1-e321-4123-be9f-d6673004af0a.png">

request an guide example configuring 🙏

**Comment by ilbuonmarcio** [comment]
Have you configured max USDT buy to 10 USDT?

**Comment by pla2aroi** [comment]
> Have you configured max USDT buy to 10 USDT?

my setting

<img width="1126" alt="Screen Shot 2564-09-12 at 22 12 39" src="https://user-images.githubusercontent.com/6565036/132993008-79c2c3af-7244-4641-aa94-6c1d67e071d2.png">
<img width="1084" alt="Screen Shot 2564-09-12 at 22 13 09" src="https://user-images.githubusercontent.com/6565036/132993013-4c12208c-deb2-4c6e-8ee8-ff39d6220b94.png">

**Comment by ilbuonmarcio** [comment]
10 is no good, you need to put more else it will just buy at 10 or similar and if it drops below 10 it triggers the remove last buy price

**Comment by pla2aroi** [comment]
> 10 is no good, you need to put more else it will just buy at 10 or similar and if it drops below 10 it triggers the remove last buy price

You mean you have to set it up like this?

<img width="1111" alt="Screen Shot 2564-09-12 at 22 22 26" src="https://user-images.githubusercontent.com/6565036/132993384-c405728c-49d3-4f12-b006-0eeab656639a.png">

**Comment by ilbuonmarcio** [comment]
Yes, more like it.

As far as I know you can't trade lower than 10 USDT

See https://www.binance.com/en/trade-rule

**Comment by pla2aroi** [comment]
> Yes, more like it.
> 
> As far as I know you can't trade lower than 10 USDT
> 
> See https://www.binance.com/en/trade-rule

🙏 Thanks

**Comment by chrisleekr** [comment]
Thanks @ilbuonmarcio 

@pla2aroi And you can set the last buy price removal threshold as 5 USDT something like that. So the bot does not remove the price.
