### ISSUE TITLE
let's share our buy and sell setups

### ISSUE THREAD

**Issue by christianvargasforero** [chrisleekr/binance-trading-bot#315]
Hello friends, thank you very much for this great effort, I am testing the bot but I have some doubts in terms of defining which will be the best buy and sell configurations, we could have some space where we can share these configurations between us, the users, in this post I put my configuration to help me define if the strength is good or not. but it would be important to see those of others in order to have a better reference. Thank you so much!!!

![Captura de Pantalla 2021-09-13 a la(s) 11 25 31 a  m](https://user-images.githubusercontent.com/11984387/133122322-31759794-3b44-4f80-9348-8b6966b01c35.png)

![Captura de Pantalla 2021-09-13 a la(s) 11 25 46 a  m](https://user-images.githubusercontent.com/11984387/133122334-8c35f0f2-9dcc-43ad-bb4d-dd3976c7683d.png)

**Comment by chrisleekr** [comment]
Hi @christianvargasforero 

First of all, this is not an enhancement, it's a question.

Secondly, there is no best configuration unless you can predict the market. 
So you cannot expect someone will post their configurations to tell you what to do.
It's your money your responsibility. 

Maybe people in the community chat can help you out.

https://github.com/chrisleekr/binance-trading-bot/issues/137

Hopefully, I answered your question. 
I will close the issue. If you have any issues with the bot, please open a new issue.
