### ISSUE TITLE
8080 and 80 connection refuse

### ISSUE THREAD

**Issue by e21zuo** [chrisleekr/binance-trading-bot#318]
I cannot connect by the web browser it has error following below.

# curl http://172.24.0.3:80
curl: (7) Failed to connect to 172.24.0.3 port 80: Connection refused

# curl http://0.0.0.0:8080
curl: (56) Recv failure: Connection reset by peer

**Comment by chrisleekr** [comment]
Please get the full log and put it here so I can see what is the issue - https://github.com/chrisleekr/binance-trading-bot/wiki/Troubleshooting#how-to-get-the-logs-by-installing-bunyan-npm-package

**Comment by e21zuo** [comment]
It seems everything is OK.

 31170 ?        Sl     0:00 /snap/docker/1125/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 8081 -container-ip 172.25.0.4 -container-port 8081
  31177 ?        Sl     0:00 /snap/docker/1125/bin/docker-proxy -proto tcp -host-ip :: -host-port 8081 -container-ip 172.25.0.4 -container-port 8081
  31183 ?        I      0:00 [kworker/1:4-events]
  31184 ?        I      0:00 [kworker/1:5-events]
  31185 ?        I      0:00 [kworker/1:6-events]
  31197 ?        Sl     0:00 /snap/docker/1125/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 8080 -container-ip 172.25.0.3 -container-port 80
  31203 ?        Sl     0:00 /snap/docker/1125/bin/docker-proxy -proto tcp -host-ip :: -host-port 8080 -container-ip 172.25.0.3 -container-port 80
  31223 ?        Sl     0:00 /snap/docker/1125/bin/containerd-shim-runc-v2 -namespace moby -id bc3c928f6692ed8fcc1775f348cbdd6c99dbb4108bce992cff725f358e04e6b3 -address /run/snap.docker/containerd/containerd.sock
  31232 ?        Sl     0:00 /snap/docker/1125/bin/containerd-shim-runc-v2 -namespace moby -id c63bd62af1b30cb0e8beef6b564761d97a608893ea06669eff0f6e6926aafbfd -address /run/snap.docker/containerd/containerd.sock
  31267 ?        Ssl    0:01 mongod
  31268 ?        Ss     0:00 tini -- /docker-entrypoint.sh mongo-express
  31305 ?        Sl     0:00 /snap/docker/1125/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 6379 -container-ip 172.25.0.5 -container-port 6379
  31311 ?        Sl     0:00 /snap/docker/1125/bin/docker-proxy -proto tcp -host-ip :: -host-port 6379 -container-ip 172.25.0.5 -container-port 6379
  31357 ?        Sl     0:00 /snap/docker/1125/bin/containerd-shim-runc-v2 -namespace moby -id 6605287cd9555670d11a8e3ca6f2fb7ad62f133e0fb7ed536f73d4c4a13f505c -address /run/snap.docker/containerd/containerd.sock
  31362 ?        Sl     0:00 /snap/docker/1125/bin/containerd-shim-runc-v2 -namespace moby -id 97e3ee7f7b9808ecdf9d15723a10f41e482bd73315288261d6ee3bb9c00eb215 -address /run/snap.docker/containerd/containerd.sock
  31414 ?        Ssl    0:00 npm
  31422 ?        Ssl    0:00 redis-server *:6379
  31580 ?        Sl     0:00 node app
  31656 ?        Sl     0:00 node /srv/node_modules/.bin/cross-env NODE_ENV=development nodemon app/server.js
  31663 ?        Sl     0:00 node /srv/node_modules/.bin/nodemon app/server.js
  31675 ?        Sl     0:00 /usr/local/bin/node app/server.js


++++++++++++++++++++++++++++++++++++++++++++++++++

\______   \__| ____ _____    ____   ____  ____   \______   \ _____/  |_
 |    |  _/  |/    \__  \  /    \_/ ___\/ __ \   |    |  _//  _ \   __
 |    |   \  |   |  \/ __ \|   |  \  \__\  ___/   |    |   (  <_> )  |
 |______  /__|___|  (____  /___|  /\___  >___  >  |______  /\____/|__|
        \/        \/     \/     \/     \/    \/          \/

> binance-trading-bot@0.0.78 migrate:up /srv
> migrate up --store=/srv/mongo-state-storage.js

[2021-09-15T10:40:01.501Z]  INFO: binance-api/25 on 6605287cd955: API logger loaded (version=0.0.78, NODE_ENV=development)
  migration : complete

> binance-trading-bot@0.0.78 dev /srv
> cross-env NODE_ENV=development nodemon app/server.js

[nodemon] 2.0.12
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node app/server.js`
[2021-09-15T10:40:02.186Z]  INFO: binance-api/65 on 6605287cd955: API logger loaded (version=0.0.78, NODE_ENV=development)
[2021-09-15T10:40:02.516Z]  INFO: binance-api/65 on 6605287cd955: Connecting mongodb (version=0.0.78, gitHash=unspecified, helper=mongo)
    uri: mongodb://binance-mongo:27017/?retryWrites=true&writeConcern=majority
[2021-09-15T10:40:02.551Z]  INFO: binance-api/65 on 6605287cd955: Connected successfully to mongodb (version=0.0.78, gitHash=unspecified, helper=mongo)
[2021-09-15T10:40:02.552Z]  INFO: binance-api/65 on 6605287cd955: Binance test started on (version=0.0.78, gitHash=unspecified, server=binance)
    config: {
      "mode": "test",
      "tz": "Australia/Melbourne",
      "appName": "Binance Trading Bot",
      "binance": {
        "live": {
          "apiKey": "xxx",
          "secretKey": "xxx"
        },
        "test": {
          "apiKey": "xxx",
          "secretKey": "xxx"
        }
      },
      "redis": {
        "host": "binance-redis",
        "port": 6379,
        "password": "secretp422",
        "db": 0
      },
      "mongo": {
        "host": "binance-mongo",
        "port": 27017,
        "database": "binance-bot"
      },
      "slack": {
        "enabled": false,
        "webhookUrl": "",
        "channel": "",
        "username": ""
      },
      "localTunnel": {
        "enabled": false,
        "subdomain": "default"
      },
      "featureToggle": {
        "notifyOrderConfirm": true,
        "notifyDebug": false,
        "notifyOrderExecute": true
      },
      "authentication": {
        "enabled": true,
        "password": "123456",
        "loginLimiter": {
          "maxConsecutiveFails": 5,
          "duration": 10800,
          "blockDuration": 900
        }
      },
      "jobs": {
        "alive": {
          "enabled": true,
          "cronTime": "0 0 9 * * *"
        },
        "trailingTrade": {
          "enabled": true,
          "cronTime": "* * * * * *",
          "symbols": [
            "BTCUSDT",
            "ETHUSDT",
            "ETHBTC",
            "XRPBTC"
          ],
          "botOptions": {
            "authentication": {
              "lockList": true,
              "lockAfter": 120
            },
            "autoTriggerBuy": {
              "enabled": false,
              "triggerAfter": 20
            }
          },
          "candles": {
            "interval": "1h",
            "limit": 100
          },
          "buy": {
            "enabled": true,
            "gridTrade": [
              {
                "triggerPercentage": 1,
                "stopPercentage": 1.02,
                "limitPercentage": 1.021,
                "minPurchaseAmount": -1,
                "minPurchaseAmounts": {},
                "maxPurchaseAmount": -1,
                "maxPurchaseAmounts": {}
              }
            ],
            "lastBuyPriceRemoveThreshold": -1,
            "lastBuyPriceRemoveThresholds": {},
            "athRestriction": {
              "enabled": true,
              "candles": {
                "interval": "1d",
                "limit": 30
              },
              "restrictionPercentage": 0.9
            }
          },
          "sell": {
            "enabled": true,
            "gridTrade": [
              {
                "triggerPercentage": 1.06,
                "stopPercentage": 0.98,
                "limitPercentage": 0.979,
                "quantityPercentage": -1,
                "quantityPercentages": {}
              }
            ],
            "stopLoss": {
              "enabled": false,
              "maxLossPercentage": 0.8,
              "disableBuyMinutes": 360,
              "orderType": "market"
            }
          },
          "system": {
            "temporaryDisableActionAfterConfirmingOrder": 20,
            "checkManualOrderPeriod": 5,
            "placeManualOrderInterval": 5,
            "refreshAccountInfoPeriod": 1,
            "checkOrderExecutePeriod": 10
          }
        },
        "trailingTradeIndicator": {
          "enabled": true,
          "cronTime": "* * * * * *"
        }
      }
    }
[2021-09-15T10:40:02.552Z]  INFO: binance-api/65 on 6605287cd955: Finding document from MongoDB (version=0.0.78, gitHash=unspecified, server=binance, helper=mongo, funcName=findOne, collectionName=trailing-trade-common)
    query: {
      "key": "configuration"
    }
[2021-09-15T10:40:02.556Z]  INFO: binance-api/65 on 6605287cd955: Found document from MongoDB (version=0.0.78, gitHash=unspecified, server=binance, helper=mongo, funcName=findOne)
    result: {
      "_id": "61418d3e334ab84b63d0042e",
      "key": "configuration"
    }
[2021-09-15T10:40:02.558Z]  INFO: binance-api/65 on 6605287cd955: Could not parse account information from cache, get from api (version=0.0.78, gitHash=unspecified, server=binance, tag=get-account-info)
[2021-09-15T10:40:02.558Z]  INFO: binance-api/65 on 6605287cd955: Retrieving account info from API (version=0.0.78, gitHash=unspecified, server=binance, tag=get-account-info)

**Comment by chrisleekr** [comment]
> [2021-09-15T10:40:01.501Z] INFO: binance-api/25 on 6605287cd955: API logger loaded (version=0.0.78, NODE_ENV=development)

> [2021-09-15T10:40:02.558Z] INFO: binance-api/65 on 6605287cd955: Could not parse account information from cache, get from api (version=0.0.78, gitHash=unspecified, server=binance, tag=get-account-info)

Why are you using `docker-compose.yml`, not `docker-compose.server.yml`

I clearly mentioned you should use `docker-compose.server.yml` if you are not developing.

https://github.com/chrisleekr/binance-trading-bot#how-to-use

```
If want production/live mode, then use the latest build image from DockerHub:

docker-compose -f docker-compose.server.yml pull
docker-compose -f docker-compose.server.yml up -d
```

**Comment by e21zuo** [comment]
Thank you I found a resolution on #319
