### ISSUE TITLE
how i solve this problem ?

### ISSUE THREAD

**Issue by zapotec001** [chrisleekr/binance-trading-bot#320]
**"portainer compose version 3 not supported"**

I get this error when I add to **portainer**.
how can i solve this problem?

_(sorry for my bad english)_

**Comment by chrisleekr** [comment]
First of all, it's not a bug. And please search for issues before posting.

Since I am not using Portainer, I am not sure how to fix it. 

Refer https://github.com/chrisleekr/binance-trading-bot/issues/114

Please close the issue.
