### ISSUE TITLE
Bot shows wrong profit

### ISSUE THREAD

**Issue by eth-man** [chrisleekr/binance-trading-bot#321]
Its possible the bot says I'm losing g money since not selling all coins he bought ?

![Screenshot_20210916-101504_Chrome](https://user-images.githubusercontent.com/8633885/133567224-2f4536ad-a7af-430f-9ef4-948dbca8aad7.jpg)
![Screenshot_20210916-101416_Binance](https://user-images.githubusercontent.com/8633885/133567343-b95e3d57-8d49-484a-ba5b-a555f4bc53e5.jpg)

**Comment by chrisleekr** [comment]
It's actually correct.

So the bot buy/sell as 
- buy: 10.691*1=10.691
- sell: 11.139*0.9=10.0251

You won't be able to sell all coins in the Binance. 
It will always leave some.

**Comment by eth-man** [comment]
Alright, thanks for clearing this out.
I guess I need to use larger amounts to see profit
