### ISSUE TITLE
Auto Trigger Buy isn't working

### ISSUE THREAD

**Issue by eth-man** [chrisleekr/binance-trading-bot#325]
## Version
v0.0.78 (60a464a)
raspberry pi 4

## Description
Old buy orders still shows and bot not execute a new trades after sell

## Expected Behaviours
Clear previews buy grids after 30 minutes

## Screenshots

![Screenshot_20210917-170150_Chrome](https://user-images.githubusercontent.com/8633885/133796358-8fe58471-6b06-49cd-bfa9-677d96f68dea.jpg)
![Screenshot_20210917-170303_Chrome](https://user-images.githubusercontent.com/8633885/133796410-906ecce3-395e-4f2e-9098-30f29c36bc37.jpg)

**Comment by chrisleekr** [comment]
With the provided information, I won't be able to guess what really happened.

- Have you have configured "Remove last buy price under"? Then how much you configured?
- After the bot sold the coin, how much worth was left?
- Have you configured 2nd sell grid trade?

From the first screenshot, I can see the last buy price is not removed after being sold.
The only reason it is not clearing the last buy price is
- when the owned coin is worth more than "Remove last buy price under": https://github.com/chrisleekr/binance-trading-bot/blob/master/app/cronjob/trailingTrade/step/remove-last-buy-price.js#L275
- when the owned coin is less than the minimum quantity to order: https://github.com/chrisleekr/binance-trading-bot/blob/v0.0.78/app/cronjob/trailingTrade/step/remove-last-buy-price.js#L238

**Comment by eth-man** [comment]
i will show a different example in pictures

yes , 10USD
its wroth 0.72USD
no i don't have a second sell grid trade


![image](https://user-images.githubusercontent.com/8633885/133932671-c784b380-0cee-4aa3-952e-393bcd369bbc.png)
![image](https://user-images.githubusercontent.com/8633885/133932694-cc488faf-3165-4509-b946-38482cbf8775.png)
![image](https://user-images.githubusercontent.com/8633885/133932717-23834408-7913-4ac6-9cdb-4987c416dc13.png)
![image](https://user-images.githubusercontent.com/8633885/133932734-06285f3e-dfce-4a2d-ac7b-898d9f3d919d.png)
![image](https://user-images.githubusercontent.com/8633885/133932775-cc20ecb6-8b74-4554-810c-c2d2a53cdc82.png)

**Comment by chrisleekr** [comment]
Please show all configurations of that coin. 
It is very hard to figure out with fragment information.

And please get the log from the bot.

Refer https://github.com/chrisleekr/binance-trading-bot/wiki/Troubleshooting#how-to-get-the-error-message

Especially, in your case, run this command:
```
docker logs binance-bot -f --tail=1000 | bunyan -c 'this.symbol === "AVAXUSDT"'  > error.log
```

**Comment by eth-man** [comment]
Sorry, I reset the bot and am waiting for it to buy coins, I will post the results as soon as the problem recurs

**Comment by eth-man** [comment]
didn't managed with the logs, posting new screenshots..


![image](https://user-images.githubusercontent.com/8633885/134469539-5d6afbd1-9e49-4702-b5ef-1c64a4c86a76.png)

![image](https://user-images.githubusercontent.com/8633885/134469664-06ad5467-aa8e-4282-885e-eb4f36444fc5.png)

![image](https://user-images.githubusercontent.com/8633885/134469884-b2b6bb69-669b-4364-9d9a-c6dd85096578.png)

![image](https://user-images.githubusercontent.com/8633885/134470085-b5292a7a-983d-4a3d-a845-e6b469efe9ba.png)

**Comment by eth-man** [comment]
any idea , anyone?

**Comment by chrisleekr** [comment]
Hey @eth-man 

Please get the log when it happened. It will help to find out the reason.

In addition, in your slack, it should've sent many messages.
Please paste the messages that you received when it happened.

**Comment by eth-man** [comment]
hey @chrisleekr
i'm getting a lot of this when trying to pull the logs:

    at /srv/node_modules/redlock/redlock.js:431:20
    at tryCatcher (/srv/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.errorAdapter [as _rejectionHandler0] (/srv/node_modules/bluebird/js/release/nodeify.js:35:34)
    at Promise._settlePromise (/srv/node_modules/bluebird/js/release/promise.js:601:21)
    at Promise._settlePromise0 (/srv/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/srv/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/srv/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/srv/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/srv/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/srv/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:464:21)
(node:46) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 26871)
(node:46) UnhandledPromiseRejectionWarning: LockError: Exceeded 1 attempts to lock the resource "redlock:trailing-trade-common:exchange-symbols".


**i realized that my slack isn't getting more messages ,removing it from .env file solved the issue for me so will give up slack feature for now
sorry didn't manage finding the exact problem.**

**Comment by chrisleekr** [comment]
That is not the log I am looking for. 

Since you are using RPi, most likely you have log level set to Error, hence you may see that error only.

Please update `docker-compose.rpi.yml` and remove `BINANCE_LOG_LEVEL` in the environment parameter.

```
environment:
      # - BINANCE_MODE=test
      - BINANCE_MODE=live
      - BINANCE_LOG_LEVEL=ERROR <--- this line
      - BINANCE_REDIS_HOST=binance-redis
```

And restart  docker by the following command:

```
$ docker-compose -f docker-compose.rpi.yml up -d
```

Once you restart, you will see very detailed log.

Then you get the log

```
$ docker logs binance-bot -f --tail=1000 | bunyan -c 'this.symbol === "LUNAUSDT"' > error.log
```

Then put in the https://gist.github.com/ because the log is large.

Refer: https://github.com/chrisleekr/binance-trading-bot/wiki/Troubleshooting#how-to-get-the-error-message

Also, make sure Slack is working as it gives you an insight into what is happening with the bot.

**Comment by eth-man** [comment]
It works thank you !
Do you mind if I send you the logs directly, I'm not sure I'm interested in sending all this information to the world

**Comment by chrisleekr** [comment]
Hey @eth-man 

I don't have any direct contact.
You can quickly upload to gist and once I get it, you can delete it.

Are you still experience the last buy price is not cleared issue?

**Comment by chrisleekr** [comment]
You can test your slack configuration with the following steps:

```
$ docker exec -it binance-bot /bin/ash                                                                                                                /srv # node ./app/scripts/slack-test.js 
```

It will tell whether your configuration is correct or not.

**Comment by eth-man** [comment]
by using the script you suggested looking at the output it seems like there is a double quotes on the URL , i changed the env and everything seems be fine regarding to slack  
 will update if this helps with the trigger price as well
thank you :)

**Comment by chrisleekr** [comment]
If the issue does not happen anymore, close the issue. You can open a new issue with more detail.
