### ISSUE TITLE
I need an order limit when purchasing the full number of times.

### ISSUE THREAD

**Issue by pla2aroi** [chrisleekr/binance-trading-bot#329]
I need an order limit when purchasing the full number of times.

when it's due will stop ordering

<img width="1133" alt="Screen Shot 2564-09-22 at 23 43 05" src="https://user-images.githubusercontent.com/6565036/134386137-af424b65-564d-4cce-920f-254a764f3b4f.png">

 🙏 thank you

**Comment by chrisleekr** [comment]
I don't understand your question. Do you mean this? https://github.com/chrisleekr/binance-trading-bot/pull/311
