### ISSUE TITLE
The page doest load and malfunction. Is it because of the cache not clearing or other else. I have clearing the cache of my browser.

### ISSUE THREAD

**Issue by Bisyrivarco** [chrisleekr/binance-trading-bot#331]
Version
v0.0.79
raspberry pi 4

Description
It seems the interface malfunction or is it because of the cache problem. It seems like taking alot of time to load.

Expected Behaviours
Clear previews as normal

Screenshots

![image](https://user-images.githubusercontent.com/58498867/134776546-a88fc791-5ddc-42d7-a91c-6d9a3d55fa6b.png)
![image](https://user-images.githubusercontent.com/58498867/134776576-a5bced04-d8e2-4be3-b31e-63ea045222ce.png)
![image](https://user-images.githubusercontent.com/58498867/134776597-8c697dbb-3b30-4730-a640-48348645b1a8.png)

**Comment by chrisleekr** [comment]
It doesn't look like the bot issue.

Please open the developer console and check the requests.

**Comment by Bisyrivarco** [comment]
![image](https://user-images.githubusercontent.com/58498867/134798680-6d7ea2fb-b788-4713-a7e4-74c1c87e7a79.png)

**Comment by chrisleekr** [comment]
That looks like something is wrong with your internet or network.
Nothing to do with the bot.

Are you able to open that css file directly?

**Comment by Bisyrivarco** [comment]
Nope i cant open the CSS file directly. . by the way. things work normally when i used vpn. 

![image](https://user-images.githubusercontent.com/58498867/135314874-61143e0f-83bb-4363-86af-8b3926f3c1a4.png)

**Comment by chrisleekr** [comment]
Something to do with your network, not the bot issue.
You need to dig into what is going on with your network.

Please close the issue as I cannot assist with this matter. 
Thank you.

**Comment by Bisyrivarco** [comment]
Ok sure thanks!
