### ISSUE TITLE
Getting error while composing with binance-redis

### ISSUE THREAD

**Issue by puneeth714** [chrisleekr/binance-trading-bot#334]
## Description
Getting error with command docker-compose -f docker-compose.server.yml up -d

Here is the log

gitpod /workspace/binance-trading-bot $ docker-compose -f docker-compose.server.yml up -d
Creating binance-mongo ... done
Creating binance-redis ... error
Creating binance-bot   ... done

ERROR: for binance-redis  Cannot start service binance-redis: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: write sysctl key net.core.somaxconn: open /proc/sys/net/core/somaxconn: no such file or directory: unknown

ERROR: for binance-redis  Cannot start service binance-redis: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: write sysctl key net.core.somaxconn: open /proc/sys/net/core/somaxconn: no such file or directory: unknown
ERROR: Encountered errors while bringing up the project.
gitpod /workspace/binance-trading-bot $ 

I am in the master branch in case it might help!

**Comment by chrisleekr** [comment]
That is nothing to do with the bot.

Maybe try to remove this line as the error message suggested.
- https://github.com/chrisleekr/binance-trading-bot/blob/master/docker-compose.server.yml#L29

Please close the issue if your issue is resolved.

**Comment by puneeth714** [comment]
Yes, The problem looks solved but I cannot get any thing at port 8080 , It shows localhost didn't send any data.
Is there any thing to do with the line i removed in the previous error?
And i have ran docker logs and it too gave error and written log into error.log file 
[error.log](https://github.com/chrisleekr/binance-trading-bot/files/7250950/error.log)
this log is created when i ran docker logs binance-bot --tail=1000 2> error.log
[error1.log](https://github.com/chrisleekr/binance-trading-bot/files/7250957/error1.log)
This log is created when i ran docker logs binance-bot --tail=1000 1> error1.log
I can see that there is nothing problem in error1.log but i dont know about error.log file.

Hope this log files help.

**Comment by chrisleekr** [comment]
Thanks for providing logs. I got the log, please remove your log.

```
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND binance-redis
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26)
```

If you see the log, binance redis is not accessible.

In second log, I can see you are running live mode without live api/secret key.

**Comment by puneeth714** [comment]
Yes i have used test api keys. Is there any problem to use test api keys?
I doubt.

**Comment by chrisleekr** [comment]
Then set mode to `test`, not `live`

**Comment by puneeth714** [comment]
I will check it.

**Comment by puneeth714** [comment]
Yes it's working now.
But i am curious what is the role of "sysctls:
      net.core.somaxconn: 1024" and why it this process is not able to run.

**Comment by chrisleekr** [comment]
It's for Redis in Linux. You can do some more research on Google. 
Good to hear your issue is resolved. Please close the issue. Thanks.

**Comment by puneeth714** [comment]
Ok

**Comment by puneeth714** [comment]
Ok
