### ISSUE TITLE
bug?: Multiple buy grid trade triggered doesn't sell even if sell is highly profitable

### ISSUE THREAD

**Issue by ilbuonmarcio** [chrisleekr/binance-trading-bot#335]
We're currently facing an issue with using multiple buy grid trades and a single sell grid trade.
The bot is configured to buy 10 grid trades, and trigger sell 100% of coins at +1%, as per these screenshots:

![photo_2021-09-29_15-22-22](https://user-images.githubusercontent.com/21985554/135294697-1adb4c56-9cb7-4cf5-8380-5b0ad5521e9c.jpg)

![photo_2021-09-29_15-22-22 (2)](https://user-images.githubusercontent.com/21985554/135294706-7565bc07-f17f-4404-bfbe-a96787385fe8.jpg)

I'm currently running the latest version of your bot from the master branch.

## Expected Behaviours

The bot, right after going >= +1.0% gain, should trigger sell stop limit order, but it is not doing it.

I'm questioning if it's only triggering sell stop limit order if EVERY buy grid trade step is completed or not, I hope sure it's not the case!

## How to "unlock it"

Go to dedicated pair settings and click on Reset grid trade -> Delete and reset (central button); It will trigger sell stop limit order right away.

## Additional case

I have a case in which I already triggered all buy grid trades, I'll wait and see if that sells on its own, I'll attach screenshot if needed:

![photo_2021-09-29_16-51-26](https://user-images.githubusercontent.com/21985554/135295483-a423e1b7-c8c9-42b1-a536-e83c4ff0993d.jpg)

**Comment by ilbuonmarcio** [comment]
PS: By "unlocking the coin" it will ruin history trade stats, showing the coin was bought at 0.00000 USDT and sell at it's current value, be aware!

**Comment by chrisleekr** [comment]
@ilbuonmarcio 

By looking at all screenshots, it looks like the Sell grid trade is executed already, but you still have enough coin to sell, hence, the bot is not removing the last buy price.

> trigger sell 100% of coins at +1%, as per these screenshots:

You mentioned, you set to sell 100% of coins. Does it mean the bot didn't sell all the coins?

> I'm questioning if it's only triggering sell stop limit order if EVERY buy grid trade step is completed or not, I hope sure it's not the case!

Nope, definitely not.

As soon as the sell condition is met, the bot will sell. And as mentioned, it looks like already sold. It just didn't sell all the coins. 
Since I cannot see your configuration, I cannot tell whether you set to sell all or not.

**Comment by ilbuonmarcio** [comment]
Nothing is showing up for this coin in the trade history nor in Binance App, so something is clearly wrong here.
It should always sell 100% of the coins, the bot never sold those coins.

**Comment by ilbuonmarcio** [comment]
For the latest screenshot (CVCUSDT) it is still at current status, I'm still waiting for it to trigger sell stop limit

**Comment by ilbuonmarcio** [comment]
This is a current example, for me the one in the left is bugged, the one on the right is correct:

![immagine](https://user-images.githubusercontent.com/21985554/135441290-c0fa6175-bb6e-42cc-a632-a25c287b26e3.png)

**Comment by ilbuonmarcio** [comment]
To make it clear, not every coin is doing this thing, only some coins, there are still sell transactions made and registered both in bot's history and Binance app.

I asked the user running for more info and it seems like the ones stuck are the ones which have had sell configured at +2% and later changed at +1%, can this be a configuration migration issue?

**Comment by chrisleekr** [comment]
Hmm, that is strange. I never had that issue.

I just saw your last message. For the last screenshot, the bot thinks it's already sold.
Let me give you the steps to get the order information. Then we can see what is happening.

1. Press F12 in your browser
2. Click Network -> WS
3. Refresh the frontend
4. Click first in the list 
5. Click Messages

Then you will see messages coming through.

6. Find one of the result message
7. Click stats -> symbols 
8. Then find ONGUSDT 
9. Right click on the symbols and click "Copy object"

The data will be pretty large for issue page, so put in gist and remove later.

![image](https://user-images.githubusercontent.com/5715919/135442061-7fa921b7-7a48-406d-b884-911ab4713e75.png)

**Comment by ilbuonmarcio** [comment]
https://gist.github.com/ilbuonmarcio/af1fb1f6850b2805823050a73b504ab9

All yours, thanks for your time :)

PS. Can it be that the user updated sell grid trade to 2% and to 1% in rapid succession without waiting for it to set to 2% first?

**Comment by chrisleekr** [comment]
You can delete the log. I got it.

From the log, I can see the sell order is executed

```
"executedOrder": {
                        "symbol": "ONGUSDT",
                        "orderId": ,
                        "orderListId": -1,
                        "clientOrderId": "",
                        "price": "1.00960000",
                        "origQty": "100.00000000",
                        "executedQty": "100.00000000",
                        "cummulativeQuoteQty": "101.63000000",
                        "status": "FILLED",
                        "timeInForce": "GTC",
                        "type": "STOP_LOSS_LIMIT",
                        "side": "SELL",
                        "stopPrice": "1.01750000",
                        "icebergQty": "0.00000000",
                        "time": 1632845766750,
                        "updateTime": 1632847371175,
                        "isWorking": true,
                        "origQuoteOrderQty": "0.00000000",
                        "currentGridTradeIndex": 0,
                        "nextCheck": "2021-09-28T16:42:43+00:00"
                    }
```

The time is Tue 28 Sep 2021 16:42:51 UTC
You can convert to your timezone.
Can you check again in Binanace?

**Comment by chrisleekr** [comment]
Actually, something is wrong. Time is not matching.
Let me dig further from your log.

**Comment by chrisleekr** [comment]
Ok, here is what happened.


Your `lastBuyPriceRemoveThreshold` is set as `5`.

And this is the timeline.

Side    | Executed Quantity   | Price         |   Remaining Quantity          |   Cumulative Quote Qty    | Time                         |
---     | ---                 | ---           |   ---                         |   ---                     | ---                          |
BUY     | 118.45400000        | 1.18940000    |   118.454                     |   118.45400000            | Fri 24 Sep 2021 00:51:48 UTC |
SELL    | 100.00000000        | 1.00960000    |    18.454 => USDT 18.6311584  |   101.63000000            | Tue 28 Sep 2021 16:16:06 UTC |
BUY     | 19.00000000         | 1.01210000    |                               |   19.22610000             | Tue 28 Sep 2021 17:18:14 UTC |
BUY     | 19.00000000         | 1.00820000    |                               |   19.15200000             | Tue 28 Sep 2021 17:55:53 UTC |
BUY     | 19.00000000         | 1.00680000    |                               |   19.12920000             | Tue 28 Sep 2021 18:19:22 UTC |
BUY     | 19.00000000         | 1.01120000    |                               |   19.21280000             | Tue 28 Sep 2021 18:33:13 UTC |
BUY     | 19.00000000         | 1.01530000    |                               |   19.29070000             | Tue 28 Sep 2021 18:48:13 UTC |
BUY     | 19.00000000         | 1.01590000    |                               |   19.30210000             | Tue 28 Sep 2021 19:08:56 UTC |
BUY     | 19.00000000         | 1.01450000    |   151.454                     |   19.26980000             | Tue 28 Sep 2021 19:57:31 UTC |

Final balance of `ONG` is `"total": 153.25495`. I assume you had something like `1.80095 ONG` already.

Now, when the coin is sold, it didn't sell all of the coins. It sold exactly 100 quantities, which looks very suspicious. It should've sell as below.


- Estimated free balance before executing 1st sell grid: 118.454+1.80095 = `120.25495`
- Estimated the price at that time of executing 1st sell grid: `1.0209` based on the grid sell price.

So the order must have been placed as below: 
```
price: 1.0096,
quantity: 119,
side: 'sell',
stopPrice: 1.0175,
symbol: 'ONGUSDT',
timeInForce: 'GTC',
type: 'STOP_LOSS_LIMIT'
```

I just added your case into the test code and got the above expectation.

Do you have any code modifications?

**Comment by ilbuonmarcio** [comment]
On this instance it's as stock as it is, without any modifications.

So what should I do, increase the 5 USDT?

**Comment by chrisleekr** [comment]
The code should work as expected. You saw the result of the test.

Can you give me the running version and commit hash on the bottom of the frontend?

And go to the docker and get the code for place-sell-order.js code.

```
$ docker exec -it binance-bot /bin/ash
/srv # cat /srv/app/cronjob/trailingTrade/step/place-sell-order.js 
```

**Comment by ilbuonmarcio** [comment]
I'm currently running on 7f58b8fcaacf6fc72f74e1c64299371e6efec13e

The code for place-sell-order.js is as following:
https://gist.github.com/ilbuonmarcio/4012220022eae5d3109e514d09cc64a5

**Comment by chrisleekr** [comment]
My latest released version hash is 244734f. 
I can see you built the master branch code.

I just went back to your log and found I was miscalculated 1st buy grid trade.

Side    | Executed Quantity   | Price         | Cumulative Quote Qty    | Created Time  |   Updated Time                 |
---     | ---                 | ---           |    ---                  | ---           |   ---                          |
BUY     | 100.00000000        | 1.18940000    | 118.45400000            | Fri 24 Sep 2021 00:49:10 UTC  |   Fri 24 Sep 2021 00:51:48 UTC |
SELL    | 100.00000000        | 1.00960000    | 101.63000000            | Tue 28 Sep 2021 16:16:06 UTC  |   Tue 28 Sep 2021 16:16:06 UTC |
BUY     | 19.00000000         | 1.01210000    |  19.22610000            | Tue 28 Sep 2021 17:17:19 UTC  |   Tue 28 Sep 2021 17:18:14 UTC |
BUY     | 19.00000000         | 1.00820000    |  19.15200000            |   |   Tue 28 Sep 2021 17:55:53 UTC |
BUY     | 19.00000000         | 1.00680000    |  19.12920000            |   |   Tue 28 Sep 2021 18:19:22 UTC |
BUY     | 19.00000000         | 1.01120000    |  19.21280000            |   |   Tue 28 Sep 2021 18:33:13 UTC |
BUY     | 19.00000000         | 1.01530000    |  19.29070000            |   |   Tue 28 Sep 2021 18:48:13 UTC |
BUY     | 19.00000000         | 1.01590000    |  19.30210000            |   |   Tue 28 Sep 2021 19:08:56 UTC |
BUY     | 19.00000000         | 1.01450000    |  19.26980000            |   |   Tue 28 Sep 2021 19:57:31 UTC |


It looks like 1st grid trade bought 100, and sold 100.
Then it should've removed the last buy price, but it didn't.

It looks like some nasty bug that cannot find the exact reason.

Maybe because of the last change I made. 

I suggest going back to version 0.0.79 until I find the exact reason. And let me know whether it's having the same issue.
For ONGUSDT, reset grid trade and put the recalculated last buy price.

```
133 quantity * total purchase after 1st sell 134.5827 = recalculated last buy price 1.0119
```

**Comment by ilbuonmarcio** [comment]
I'll try and let you know, thanks!

**Comment by chrisleekr** [comment]
Wait, this doesn't explain this.

So at the moment, you have `153.25495` ONG. However, grid buy 2-8, which purchased 19 each, must be `133`ONG.

Where is `20.2549` coming from? Did you manually purchased after?

```
    {
        "asset": "ONG",
        "free": "153.25495000",
        "locked": "0.00000000",
        "total": 153.25495
    },
```

**Comment by chrisleekr** [comment]
You will need him to take a screenshot of Binance transaction.

Clearly, there are missing transactions that the bot didn't catch. 

Go to Binance and get the transaction from Thu 23 Sep 2021 UTC ~ Tue 29 Sep 2021 UTC.

Note that period may need to convert to your timezone.

**Comment by chrisleekr** [comment]
Another strange thing is, it triggered sell when the sell trigger price is not reached. In fact, it's much less than the sell trigger price.

Side    | Executed Quantity   | Price         | Cumulative Quote Qty    | Created Time                  |   Updated Time                 |  Next Check
---     | ---                 | ---           |    ---                  | ---                           |   ---                          |  -- 
BUY     | 100.00000000        | 1.18940000    | 118.45400000            | Fri 24 Sep 2021 00:49:10 UTC  |   Fri 24 Sep 2021 00:51:48 UTC |  2021-09-24T00:51:50+00:00
SELL    | 100.00000000        | 1.00960000    | 101.63000000            | Tue 28 Sep 2021 16:16:06 UTC  |   Tue 28 Sep 2021 16:16:06 UTC |  2021-09-28T16:42:43+00:00
BUY     | 19.00000000         | 1.01210000    |  19.22610000            | Tue 28 Sep 2021 17:17:19 UTC  |   Tue 28 Sep 2021 17:18:14 UTC |  2021-09-28T17:18:19+00:00

If you see the last buy price for 1st grid buy is `1.1894`. It should trigger sell when the price reached `1.1894 * 1.02 = 1.213188`.
but the sell is triggered when the price is `1.0209` based on the calculation of limit price `1.0096`.

That is why quote qty is less than buy. 

Can you check the slack message whether he manually triggered sell? You should look for around this time `Tue 28 Sep 2021 16:16:06 UTC`. 

If he triggered sell manually, the message would be as below. 
```
ONGUSDT Action: Queued action: sell
- Message: The sell order received by the bot. Wait for placing the order.
```

**Comment by ilbuonmarcio** [comment]
I just wrote him to give me screenshots of the transactions on Binance as per your request, I'll let you know once I got those.

Unfortunately I don't think he set up Slack integration for his bot, so I'm not sure I can provide you the information you asked

**Comment by chrisleekr** [comment]
As you can see from my previous message, the timing is not making sense.
If there were any open orders buy or sell, then the bot will not remove the last buy price.
https://github.com/chrisleekr/binance-trading-bot/blob/master/app/cronjob/trailingTrade/step/remove-last-buy-price.js#L170

My assumption is, for some reason, he triggered buy/sell orders and there were open orders.

This scenario is making sense. We can verify by checking Binance transactions.
The screenshot must include cancelled orders.
In this case, I probably need to see only Tue 28 Sep 2021 *UTC* transactions for ONGUSDT.

**Comment by chrisleekr** [comment]
Hey @ilbuonmarcio 
Can you confirm the issue still exists?

**Comment by ilbuonmarcio** [comment]
I'm still waiting for the screenshots but yeah, it's still here

**Comment by ilbuonmarcio** [comment]
I figured out that there was effectively a race condition between configuration saves, and indeed the configuration was updated half with the first save and half with the second save.

I can't be sure about how it could happen, but the only thing I know is that there were 10 buy grid trades in both configs and there were coin pairs already purchased with a single grid trade as the previous configuration and others still free, probably that's why they bugged out like that.

My friend just resetted the bot so I can't go back and check, but thanks for your help, I'll be in touch with you again if it arises again for sure!
Of the 7 bots I see this is the only one with this problem, so that could be surely not a bug in the code, but a mere race condition between applying configs.

**Comment by ilbuonmarcio** [comment]
I'll close it for now, so you can focus on more urgent requests.
If it comes up again I'll get in touch asap

Thanks again for the time provided!

**Comment by ilbuonmarcio** [comment]
@chrisleekr is it normal that if I save buy grid trades on global configuration (10 grid trades), and there are coins which are already some of the grids triggered (3 out of 10), if I save and apply changes to all coins via global configuration, only the remaining 7 will be updated and the other initial 3 will remain stuck with the old config?

**Comment by chrisleekr** [comment]
So let me sum up:

- There are 3 open orders out of 10.
  - Are they customised configurations?
- Updated global configurations for all coins.
- 3 coins are still old config?

The change of configuration wouldn't cancel open orders. If open orders are cancelled, it will use an updated configuration for the next order.

**Comment by ilbuonmarcio** [comment]
No, I mispelled here.
Example: there is a single coin, which has 3 already completed buy grid trades out of his 10, with global configuration applied, so no custom values provided.
If I edit and apply global settings to all coin pairs, like I edit all 10 grid trades, only the last 7 gets applied and the remaining first 3 grid trades won't be updated, thus being "half updated" with first 3 with the old status and latest 7 with new status.

Is this a feature or a bug? 
I just encountered that today after a bot virtual machine complete redo, and cannot understand if that's the one or the other...

**Comment by chrisleekr** [comment]
> Example: there is a single coin, which has 3 already completed buy grid trades out of his 10, with global configuration applied, so no custom values provided.

So 3 out of 10 buy grid trades are executed. Then even if you update the global configuration, it won't update executed orders.
It makes sense to not update those values because those 3 buy orders are already executed.
The same rule applies when you try to update the symbol configuration which already has executed orders. You will see them as greyed out because it's already executed.

That is the expected flow.

Did I understand your problem correctly?

**Comment by ilbuonmarcio** [comment]
Yeah, but that makes me think, if I need to update every coin with that new configuration, and some are already in open trades, then I need to know what are the ones who differ from global configuration, because even after applying the global settings, in the GUI it remains set as the while "Global" settings tag is applied for each coin, and not the yellow one, even if effectively they are differing from the global configuration.

**Comment by chrisleekr** [comment]
> the bot will update also grid 1 and 2 after the coin is sold with the new configuration?

Yes. After the coin is sold, the grid trade will be completely reset and start using a new configuration.

**Comment by chrisleekr** [comment]
@ilbuonmarcio This issue can be closed?
