### ISSUE TITLE
Bot keeps buying instantly at some point

### ISSUE THREAD

**Issue by eth-man** [chrisleekr/binance-trading-bot#342]
## Version
 * x86 pc  :
 v0.0.79
(244734f)

* rpi4 arm 
v0.0.79
(244734f)

## Description
bot start buying coins at really high prices it seems like the 2 bot's i have ignores my trigger percentage and start buying coins immediately after auto trigger buy timeout . 

## To Reproduce
i realized the reason for this is the Close trade section getting filled out 
deleting the trade history at one of the bots and now first grid buy looks normal again

**Comment by eth-man** [comment]
"gridTrade": [
            {
              "triggerPercentage": 1,
              "stopPercentage": 1.003,
              "limitPercentage": 1.0037,
              "minPurchaseAmount": 10,
              "maxPurchaseAmount": 300,
              "executed": false,
              "executedOrder": null
            },
    
    
    
    
      "buy": {
        "currentPrice": 1.5065,
        "limitPrice": 1.51207405,
        "highestPrice": 1.51,
        "lowestPrice": 1.4541,
        "athPrice": 1.94,
        "athRestrictionPrice": 1.8042,
        "triggerPrice": 1.4541,
        "difference": 3.603603603603611,
        "openOrders": [
          {
            "symbol": "FTMUSDT",
            "orderId": 628596342,
            "orderListId": -1,
            "clientOrderId": "YcvNwydc3saAkcxY6zPHyJ",
            "price": "1.51200000",
            "origQty": "198.00000000",
            "executedQty": "0.00000000",
            "cummulativeQuoteQty": "0.00000000",
            "status": "NEW",
            "timeInForce": "GTC",
            "type": "STOP_LOSS_LIMIT",
            "side": "BUY",
            "stopPrice": "1.51100000",
            "icebergQty": "0.00000000",
            "time": 1633266752991,
            "updateTime": 1633266752991,
            "isWorking": false,
            "origQuoteOrderQty": "0.00000000"
          }

**Comment by ilbuonmarcio** [comment]
Wait, are you running two bots with the same account simultaneously?
If so, it's not a supported architecture and can produce inconsistencies and race conditions and make them both unusable.

**Comment by eth-man** [comment]
You sure? 
I'm using different coins for each bot

**Comment by eth-man** [comment]
Hi , 
i'm now sending the bot logs to my ELK  :)
Here logs before and after the order was filled

https://gist.github.com/eth-man/ce0d309a31e6239affceaed11acb6c80

thanks

**Comment by chrisleekr** [comment]
Ok, I can see you are using latest version v0.0.79.

And I also can see from the log that you are enabled the auto-trigger buy feature.

```
            "autoTriggerBuy": {
              "enabled": true,
              "triggerAfter": 55
            },
```

With the latest released version, the bot will ignore the ATH restrictions. 

However, I have merged new changes to cover the following changes:
- Auto trigger buy can be able to reschedule if the price is over the ATH.
- Auto trigger buy can be able to reschedule if the action is disabled by stop-loss or other actions.

Refer https://github.com/chrisleekr/binance-trading-bot/pull/330

Once I release the new version, you will have an option like this 
![image](https://user-images.githubusercontent.com/5715919/136770898-a82c2efd-087d-4078-b353-b4b36436f6b2.png)

Then it will automatically reschedule auto-trigger buy if the current price is under the ATH price.
