### ISSUE TITLE
ATH ignored 

### ISSUE THREAD

**Issue by eth-man** [chrisleekr/binance-trading-bot#350]
Guys,  what's going up with my bot 
Please help 

![Screenshot_20211007-145719_Chrome](https://user-images.githubusercontent.com/8633885/136379969-4e3dc8da-d4aa-4d8b-a9ed-c8c8079605de.jpg)

**Comment by chrisleekr** [comment]
@eth-man 

First of all, please use a bug template. 

Was it triggered by an auto-trigger?

What are the slack messages saying?
