### ISSUE TITLE
How open in VPS.   0.0.0.0:8080 Error

### ISSUE THREAD

**Issue by kleverant** [chrisleekr/binance-trading-bot#356]
Hi. can you help me?
I try to start in my vps. but can't

after .   docker-compose -f docker-compose.server.yml up -d
Error starting userland proxy: listen tcp4 0.0.0.0:8080: bind: address already in use
ERROR: for binance-bot  Cannot start service binance-bot: driver failed programming external connectivity on endpoint binance-bot
Error starting userland proxy: listen tcp4 0.0.0.0:8080: bind: address already in use
ERROR: Encountered errors while bringing up the project.

**Comment by chopeta** [comment]
You can also just edit your `docker-compose.server.yml` and replace the "8080" in the ports section of the 'binance-bot' service for a port that is not currently in use on your server.

**Comment by ilbuonmarcio** [comment]
If you set it from 8080:80 to 8085:80 and access it from http://{yourVPSpublicIPaddress}:8085, it should pop up if configured correcly.

**Comment by kleverant** [comment]
Exactly what is needed . 
Big tnx!
