### ISSUE TITLE
What do I have to do to see the Frontend in Mobile?

### ISSUE THREAD

**Issue by thesam1545** [chrisleekr/binance-trading-bot#367]
I am using Docker and so Frontend Desktop.
I am a bit new in this...
How can I see the bot in my Android Phone?

**Comment by chrisleekr** [comment]
@thesam1545 If your question is answered, please close the issue

@atol71 

Please try to follow the steps on the release page
https://github.com/chrisleekr/binance-trading-bot/releases/tag/v0.0.83

**Comment by thesam1545** [comment]
> @thesam1545 If your question is answered, please close the issue
> 
> @atol71
> 
> Please try to follow the steps on the release page https://github.com/chrisleekr/binance-trading-bot/releases/tag/v0.0.83

Ok.
