### ISSUE TITLE
TrandingView signals do not updating

### ISSUE THREAD

**Issue by thesam1545** [chrisleekr/binance-trading-bot#368]
I just want to see if someone else here has TV signals not updating...
![Capturar](https://user-images.githubusercontent.com/90088866/138572321-48cc916d-1d0d-4622-82f1-3c3a13bf3562.PNG)

I am on Windows using docker to deploy the bot.
Things already done to try to solve.
-> Delete all containers and Bot files and freshly download all files and deploy them im Docker:
-> Restarting TV every 20 minutes, and hourly;
-> Restarting all the containers every 20 minutes, and hourly.

I am Running Version: v0.0.83 (366761b) Latest Version: v0.0.83
I hope this commit is the official. I did not change any file in the bot. Only created the .env file!
Thank you @chrisleekr, I know you have made efforts to correct this, but still not sucessfully.

**Comment by chrisleekr** [comment]
Hey @thesam1545 

I have released v0.0.84 which retrieves tradingview recommendations for all symbols per tick.

Please test and let me know if it's happening again.
If not, please close the issue.

**Comment by thesam1545** [comment]
> Hey @thesam1545 
> 
> I have released v0.0.84 which retrieves tradingview recommendations for all symbols per tick.
> 
> Please test and let me know if it's happening again.
> If not, please close the issue.
> 

I installed v0.0.83 last Thursday in ubuntu and I was evaluating the bot before giving feedback. 
I noticed that with 2 or 3 symbols, the bot refresh TV signals quickly for at least 1 day straight... then it starts not updating quickly... and I made the cronjob trick.

With several symbols, signals get delayed from the moment the bot starts.

The best solution I found is to restart the TV container every minute with cronjob... however, if controling 30+ symbols, 1 or 2 have signals not updated. 

I will install this update and see what happens.
Thank you @chrisleekr

**Comment by chrisleekr** [comment]
@thesam1545 

Just note, if one or two symbols' signal is not updating, then it may not an issue with the bot.

TradingView may not have the signal for specific symbols.

If you use the latest version, then it will be easily noticed.

Let me know.

**Comment by thesam1545** [comment]
> @thesam1545
> 
> Just note, if one or two symbols' signal is not updating, then it may not an issue with the bot.
> 
> TradingView may not have the signal for specific symbols.
> 
> If you use the latest version, then it will be easily noticed.
> 
> Let me know.

I installed the latest version and it looks like that with few symbols added to the bot, it has signals always updated...
Then, I added a few more symbols:
![image](https://user-images.githubusercontent.com/90088866/139541695-39a901ed-535d-4bcb-b9cb-bce0d6ba6ec9.png)

And this happenned:
![image](https://user-images.githubusercontent.com/90088866/139541645-4a949d0a-f992-4c76-8166-25b009e7bedd.png)

**Comment by Rayn0r** [comment]
After upgrading to v0.0.84 and pulling all docker images, I see the same problem.
It seems to happen to all the coins...
The logs says:

> Error occurred while retrieving TradingView technical analysis...

and
>    "err": {
>      "message": "socket hang up",
>      "name": "Error",
>      "stack": "Error: socket hang up\n    at connResetException (internal/errors.js:639:14)\n    at Socket.socketOnEnd >(_http_client.js:499:23)\n    at Socket.emit (events.js:412:35)\n    at endReadableNT (internal/streams/readable.js:1334:12)\n    >at processTicksAndRejections (internal/process/task_queues.js:82:21)",
>      "code": "ECONNRESET"
>    }

I reverted back to v0.0.83 using:
```
git checkout v0.0.83
```
, changed the docker-compose.server.yml file to this:
```
diff --git a/docker-compose.server.yml b/docker-compose.server.yml
index 2ae550d..36013af 100644
--- a/docker-compose.server.yml
+++ b/docker-compose.server.yml
@@ -3,7 +3,7 @@ version: '3.7'
 services:
   binance-bot:
     container_name: binance-bot
-    image: chrisleekr/binance-trading-bot:latest
+    image: chrisleekr/binance-trading-bot:0.0.83
     networks:
       - internal
     env_file:
@@ -24,7 +24,7 @@ services:

   tradingview:
     container_name: tradingview
-    image: chrisleekr/binance-trading-bot:tradingview
+    image: chrisleekr/binance-trading-bot:tradingview-0.0.83
     networks:
       - internal
     restart: unless-stopped
```
and deleted the new images locally:
```
docker rmi 656139d5e10b
docker rmi a29ceddde096
```
Now it is working as before.

**Comment by Rayn0r** [comment]
I should mention, that I'm running this under Ubuntu 18.04 and therefore had to change the first line in the `docker-compose.server.yml` to:
```
diff --git a/docker-compose.server.yml b/docker-compose.server.yml
index 2ae550d..05a08ca 100644
--- a/docker-compose.server.yml
+++ b/docker-compose.server.yml
@@ -1,9 +1,9 @@
-version: '3.7'
+version: '3.3'

 services:
   binance-bot:
     container_name: binance-bot
```

**Comment by chrisleekr** [comment]
@Rayn0r 

Thanks for providing logs. I found an issue from your log.

```

Exception occurred during processing of request from ('172.18.0.4', 48660)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/lib/python3.9/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.9/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.9/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/local/lib/python3.9/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.9/http/server.py", line 415, in handle_one_request
    method()
  File "/app/main.py", line 72, in do_GET
    self._handle_symbols(qParsed)
  File "/app/main.py", line 51, in _handle_symbols
    'summary': symbolAnalyse.summary, 'time': symbolAnalyse.time.isoformat(), 'oscillators': symbolAnalyse.oscillators, 'moving_averages': symbolAnalyse.moving_averages, 'indicators': symbolAnalyse.indicators}
AttributeError: 'NoneType' object has no attribute 'summary'
----------------------------------------
```

It must be one of the symbol didn't return TradingView result.

Let me dig further.

**Comment by Rayn0r** [comment]
The symbols between v0.0.83 and v0.0.84 did not change. 
They are:
```
ALGOBTC
BCHUSDT
C98BNB
FTMBUSD
NANOUSDT
ONEBNB
SHIBBUSD
YFIUSDT 
```

**Comment by chrisleekr** [comment]
From @thesam1545 log, I can see the error if you add `NPXSUSDT`, which TradingView does not support.

I think there are multiple issues here.

1. TradingView takes more than 5 seconds to retrieve the result, which causes timeout. 
2. Current TradingView container is very simple web server. And if the bot timeout the request, TradingView container throws an exception as well.
3. TradingView should handle None result.

To fix this issue, I will need to rewrite TradingView container and give more timeout seconds in case the network is slow.

**Comment by thesam1545** [comment]
> From @thesam1545 log, I can see the error if you add `NPXSUSDT`, which TradingView does not support.
> 
> I think there are multiple issues here.
> 
> 1. TradingView takes more than 5 seconds to retrieve the result, which causes timeout.
> 2. Current TradingView container is very simple web server. And if the bot timeout the request, TradingView container throws an exception as well.
> 3. TradingView should handle None result.
> 
> To fix this issue, I will need to rewrite TradingView container and give more timeout seconds in case the network is slow.

Difficult job?

**Comment by chrisleekr** [comment]
Guys, I have refactored TradingView with Flask.

Please see the PR and test please - https://github.com/chrisleekr/binance-trading-bot/pull/383
