### ISSUE TITLE
STRONG BUY priority

### ISSUE THREAD

**Issue by bangbaew** [chrisleekr/binance-trading-bot#369]
I'm currently configure my monitoring for 1m/15 candles and TradingView summary of 1h (I'm not sure if this is the best configuration for making profits), when it bought something in STRONG BUY, I really gained the profit in short period, but TV would give STONG BUY signals once in a while, if I only check for buy STRONG BUY only, it will need to wait until a STRONG BUY appears, so I think there should be a priority feature, if there are some STRONG BUY signals, wait for their price to reach the the trigger price first and buy them, then buy the normal BUY signals when there are no STRONG BUY left.

**Comment by chrisleekr** [comment]
@bangbaew 
If your issue is answered, please close the issue.
