### ISSUE TITLE
Adjustment in trade calculation

### ISSUE THREAD

**Issue by philippirsl** [chrisleekr/binance-trading-bot#374]
We can verify that the sales calculations on trades are not performed correctly.

Since a smaller number is sold than the buy, I believe it should be calculated on the basis of the sale. Furthermore, in the case of manual sales, it is calculated as 100% loss, which is also considered wrong, as sometimes the sale is made at a profit.

**Comment by chrisleekr** [comment]
@chopeta 
Please open a new issue with your suggestion. It's hard to catch up if you put in another issue.

@philippirsl 
If you don't explain further, I will close the issue.

**Comment by chopeta** [comment]
> @chopeta
> Please open a new issue with your suggestion. It's hard to catch up if you put in another issue.

Done!

**Comment by chrisleekr** [comment]
@philippirsl Since I don't have any further infromation from you, I will close the issue.
