### ISSUE TITLE
SHIBEURO isn't triggering sell grid

### ISSUE THREAD

**Issue by bassel-desoky** [chrisleekr/binance-trading-bot#377]
Running Version:
v0.0.83
(366761b)
Latest Version:
v0.0.83

The action for SHIBEURO is locked and no sell orders being placed although it should be triggered
also it doesn't trigger manually and in the log it is showing that it is trying to

## Expected Behaviours

place stop sell order

![image](https://user-images.githubusercontent.com/81150093/139128424-b2098e16-5cd0-4a5c-9c02-4f01fb1939b0.png)
![image](https://user-images.githubusercontent.com/81150093/139128437-bfa8e879-25e1-4178-98c3-fe8279340aef.png)

**Comment by chrisleekr** [comment]
Hi @bassel-desoky 

In the logs, you can click the data icon to view the parameters.

Can you provide that? So I can test it out?

**Comment by chrisleekr** [comment]
@bassel-desoky Since I didn't get more information from you, I will close the issue.
Please open a new issue if you have the same issue. And provide me with exported logs.
