### ISSUE TITLE
current price not updating after a while

### ISSUE THREAD

**Issue by Rayn0r** [chrisleekr/binance-trading-bot#382]
I'm running v0.0.83 under Ubuntu 18.04. (I reverted back, since TV is not working under v0.0.84. See #368)

After the trading bot has run for several hours, the current price does not update anymore. The time that passes before a failure occurs varies. It can be 5 hours, but also 15 or more, before it stops updating the price.
The spinner at the top still "signals" the trading for the coin being active, but in fact it isn't. It does not occur to all the coins at once. And it is not limited to a specific set of coins. All seem to be affected from time to time.

What can I do to help find the cause?
Should there be something in the docker logs, or should something be missing from them?

I little notch into the direction of where to search is greatly appreciated.

**Comment by chrisleekr** [comment]
@Rayn0r 

You mentioned only some coins are not updating the price. That is pretty odd.

If it's not gonna work, it shouldn't work for all coins.

When it happens, what you can do is, check the log for Binance WebSocket.
Try to execute the below command and see whether there are new candle data coming from Binance.
```
docker logs binance-bot -f --tail=100| bunyan -c 'this.server === "binance"'
```

**Comment by Rayn0r** [comment]
I ran the following command for a bout a minute to see if the amount of queries for each coin is the same:
```
docker logs binance-bot -f | bunyan -c 'this.server === "binance"'|grep -v INFO|sed 's/candle://g'|jq -r '.symbol' > docker-symbols.lo
```
After that I did:

**Comment by chrisleekr** [comment]
So you are getting the data. That means all working as expected.

The way working is, the bot subscribes Binance WebSocket which sends the transaction data if occurs.

C98BNB may not have frequent transactions as SHIBBUSD, hence the data is not updating frequently.

Hope it makes sense.
If your question is answered, please close the issue.

**Comment by Rayn0r** [comment]
It happend again... 
For some reason SHIBBUSD is not updating right now. Looking at the log I see only 7 out of my 8 current coins. SHIBBUSD is not in the list...

And the screenshot shows Binance trade for SHIBBUSD in a second tab with a different price:
![SHIB-not-updating copy](https://user-images.githubusercontent.com/4147858/139601197-74ad94e0-cca4-4770-80ef-50c63e4d06e3.jpg)

**Comment by chrisleekr** [comment]
@Rayn0r 

The price between the bot and Binance cannot be 100% synchronised. 
The bot relies on Binance sending the bot with the latest transaction.

All the bot does is waiting for Binance to send indicators to the bot and cache it. 
- See this code https://github.com/chrisleekr/binance-trading-bot/blob/master/app/server-binance.js#L76

The cached indicator will be used in the next tick.
- See this code https://github.com/chrisleekr/binance-trading-bot/blob/master/app/cronjob/trailingTrade/step/get-indicators.js#L50

So the delay is expected.

Please close the issue if your question is answered.

**Comment by Rayn0r** [comment]
@chrisleekr 
I had been looking at the web frontend for quite a while (15mins), before I decided to restart the docker images. After restarting, the current price was in sync again with the Binance trade page
I caught an error in the logs yesterday, but don't know whether or not it is related to the things I see.
```
(node:46) UnhandledPromiseRejectionWarning: LockError: Exceeded 1 attempts to lock the resource "redlock:trailing-trade-symbols:FTMBUSD-symbol-info".
    at /srv/node_modules/redlock/redlock.js:431:20
    at tryCatcher (/srv/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.errorAdapter [as _rejectionHandler0] (/srv/node_modules/bluebird/js/release/nodeify.js:35:34)
    at Promise._settlePromise (/srv/node_modules/bluebird/js/release/promise.js:601:21)
    at Promise._settlePromise0 (/srv/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/srv/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/srv/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/srv/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/srv/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/srv/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:464:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:46) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:46) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
I'm also writing docker logs to a file right now. I'm curious whether or not I'll find something when/if it happens again. There are 84GB free space left on the disk right now.

**Comment by Rayn0r** [comment]
@chrisleekr
It happened again after about 14 hours of uptime.
The log is about 134GB. Thanks to zfs' lz4 it all fit on the 84GB of free space :-)

I saved the logs by running:
```
docker logs binance-bot -f 2>&1 | bunyan > docker-symbols_3.log 2>&1
```

This is the last candle that arrived:
```
[2021-11-01T20:00:26.538Z]  INFO: binance-api/46 on de99be40ce37: Received new candle (version=0.0.84, gitHash=b62200c, server=binance)
    candle: {
      "eventType": "kline",
      "eventTime": 1635796826411,
      "symbol": "SHIBBUSD",
      "startTime": 1635796800000,
      "closeTime": 1635796859999,
      "firstTradeId": 38338490,
      "lastTradeId": 38338602,
      "open": "0.00007135",
      "high": "0.00007135",
      "low": "0.00007113",
      "close": "0.00007124",
      "volume": "1063076253.00",
      "trades": 113,
      "interval": "1m",
      "isFinal": false,
      "quoteVolume": "75704.14676359",
      "buyVolume": "404991538.00",
      "quoteBuyVolume": "28826.83355942"
    
```

From what I can tell, there is nothing suspicious before or after this entry. But then this is my fist time dealing with a log of this kind.
 
The log ends at `2021-11-01T21:32:52.138Z` 
So there's plenty of log before and after the last candle for SHIBBUSD.

**Comment by chrisleekr** [comment]
@Rayn0r 

> (node:46) UnhandledPromiseRejectionWarning: LockError: Exceeded 1 attempts to lock the resource "redlock:trailing-trade-symbols:FTMBUSD-symbol-info".

This error can be ignored as it will attempt to get the lock in the next tick.

I have no idea what is happening with yours.

Mine is running for over 45 hours and does not have any issue.

![image](https://user-images.githubusercontent.com/5715919/139820702-c6b9a227-f0cf-4854-a31d-25840a5c3d70.png)
![image](https://user-images.githubusercontent.com/5715919/139820813-14532bab-811e-43e1-822a-4e097d762c07.png)

My only suggestion is, make the bot restart every hour if restarting fixes the issue.

Refer https://github.com/chrisleekr/binance-trading-bot/wiki/Troubleshooting#setup-cronjob-or-scheduled-task-to-restart-the-bot-periodically

**Comment by lfpcorreia** [comment]
I'm having the same issue.. it's been either over ~3.5 hours or a lot more since the `current price` in the bot is the actual current price:

<img width="1328" alt="image" src="https://user-images.githubusercontent.com/411650/140096468-ee1558da-fdab-4892-802a-f8cc28fcdcd5.png">

This is happening for all symbols atm..

**Comment by chrisleekr** [comment]
@lfpcorreia I don't think your issue is same as @Rayn0r. From your screenshot, I can see TradingView is not updated for 10 hours as well. You need to check your internet or Binance API connection.

@Rayn0r If your issue is resolved, please close the issue.

**Comment by Rayn0r** [comment]
@chrisleekr 
I can work around the problem using cron. I have set it to restart after 2 hours currently. If things remain stable, then this is fine with me.

**Comment by lfpcorreia** [comment]
> @lfpcorreia I don't think your issue is same as @Rayn0r. From your screenshot, I can see TradingView is not updated for 10 hours as well. You need to check your internet or Binance API connection.
> 
> @Rayn0r If your issue is resolved, please close the issue.

I have the tradingview updates disabled. I don’t use their signals :)
