### ISSUE TITLE
Delay getting Lowest price data

### ISSUE THREAD

**Issue by thesam1545** [chrisleekr/binance-trading-bot#384]
I am running Version: v0.0.84 (aa9e9ff).

I am monitoring SHIBAEUR.
I was looking at the Binance chart live for 15 min candles:
![vv](https://user-images.githubusercontent.com/90088866/139588985-8e8e1e72-343b-4202-99af-5c3749b6fb9b.PNG)

And I was looking to SHIBAEUR in the bot at the same time. The bot said the lowest price like this... and got me confused because the lowest price was not that in the settings I have, that is 15min candles and history of 15 candles.
![aa](https://user-images.githubusercontent.com/90088866/139589026-391e5df7-31e4-4fd8-aef0-c7389d3c5910.PNG)

Suddenly, the bot updated the lowest price to the correct one... but this action took 4 or 5 minutes to happen. I was able to take a snapshot at the time that the update happenned...
![b](https://user-images.githubusercontent.com/90088866/139589089-e27c5bbb-ddf5-492e-9766-e231cde4ac89.PNG)

I am monitoring about 40 symbols... can that be cause? I am on Windows.

**Comment by chrisleekr** [comment]
@thesam1545 
I understand you feel everything is a bug, but it's not.
Please make sure it's a real bug when you label it.

If you see the code - https://github.com/chrisleekr/binance-trading-bot/blob/master/app/cronjob/trailingTradeIndicator/step/get-indicators.js#L67 - it retrieves the lowest price in the TrailingTradeIndicator, which runs each symbol per tick.

If you have 40 symbols, it may takes 40 * 1- 3 seconds = 40 secs - 120 secs.

Please close the issue if your question is answered.

**Comment by thesam1545** [comment]
> estion is answ

ok
