### ISSUE TITLE
for testnet API invalid highest/lowest/ATH prices depending of number of candlesticks

### ISSUE THREAD

**Issue by marekorok** [chrisleekr/binance-trading-bot#387]
## Version
v0.0.85(55d7027)
RPi version installed on ARM VPS (Oracle)

## Description
using testnet api binance notice problem with highest, lowest and ATH values
the larger number of candlesticks the value is growing completely out of the sky, like cumulating some calculation error
for example for pair BTCUSDT (Interval/Limit)
1h/100, highest price: 150535.61, lowest price: 20000.00
1h/30, highest price: 100000.00, lowest price: 20000.00
1h/15, highest price: 75308.67, lowest price: 52607.35
1h/5, highest price: 64685.51, lowest price: 58754.41
1h/1 highest price: 62839.21, lowest price: 61807.95

behavior the same for other pairs, although different values correspnding to the pair

## To Reproduce
using Binance testnet API with RPi version
it's fresh installation without any tweaks, only added testnet API keys to the .env file

docker-compose -f docker-compose.rpi.yml up -d --build

## Expected Behaviours
proper highest/lowest/ATH values

## Screenshots
![image](https://user-images.githubusercontent.com/28598034/140337918-3b9878cd-5118-4779-9090-c84bdeb5606b.png)

## Additional context
not sure if it's only testnet API bug and/or RPi version

**Comment by caebwallace** [comment]
Testnet prices are different than "real market" and transactions are scoped to that testing environment.
As users have a big amount of assets on test account creation and volume are very low for each pairs, it's easy for anyone to pump and dump BTC.
You can check on testnet graphs directly.

**Comment by marekorok** [comment]
yeah, tested installation of the bot on different platforms, same behavior everywhere.
yeah, checked they have no mercy :-(
![image](https://user-images.githubusercontent.com/28598034/140502165-71dd8539-9318-4f99-a7e5-16d8f9837b7c.png)

Thank you for help
At least got some practise with docker :-)
