### ISSUE TITLE
Tv Force sell 

### ISSUE THREAD

**Issue by eth-man** [chrisleekr/binance-trading-bot#388]
Hello friends,
Any idea why this feature can't use limit order instead market order?

"Force sell at the market price when recommendation is Strong sell and the profit is between 0 to trigger price "

**Comment by chrisleekr** [comment]
It is because if you are selling with the limit order, the order may not be executed.

The feature ""Force sell at the market price when recommendation is Strong sell and the profit is between 0 to trigger price " is for minimising the lose.
