### ISSUE TITLE
How do i start the bot in test mode?

### ISSUE THREAD

**Issue by Jbizl** [chrisleekr/binance-trading-bot#395]
Hi, I have installed the bot and got it up and running, no issues here, just wondering how to enable test mode on the bot because I've changed the setting in docker-stack.yml from BINANCE_MODE: 'live' to BINANCE_MODE: 'test', however, the bot is running in live mode and placing orders on the exchange. Also I'd like to ask if there is a way to add multiple symbols at once either through the web-ui or via a config file as i have a large list of coins that id like to test the bot with?

Thanks in advance.

**Comment by Subfortytwo** [comment]
Change it in the docker-compose*.yml that you use, you'll find a line commented:

```
    environment:
      # - BINANCE_MODE=test
      - BINANCE_MODE=live

```
