### ISSUE TITLE
TradingView does not want to update

### ISSUE THREAD

**Issue by Astate** [chrisleekr/binance-trading-bot#396]
## Version
0.0.85

## Description
TradingView does not want to update.
I have message **"The data is older than 5 minute(s). This data will not be used until it is updated."**

`"name":"binance-api","version":"0.0.85","hostname":"63f370a3c502","pid":47,"gitHash":"52d7022","server":"cronjob","job":"trailingTradeIndicator","uuid":"11227205-e229-422e-a22e-ca9e229111ae","level":50,"symbol":"ETHUSDT","err":{"message":"Timestamp for this request is outside of the recvWindow.","name":"Error","stack":"Error: Timestamp for this request is outside of the recvWindow.\n    at /srv/node_modules/binance-api-node/dist/http-client.js:93:17\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async g (/srv/dist/server.js:1:49917)\n    at async execute (/srv/dist/server.js:1:72092)\n    at async execute (/srv/dist/server.js:1:69835)\n    at async /srv/dist/server.js:1:111689\n    at async CronJob.<anonymous> (/srv/dist/server.js:1:111527)","code":-1021},"debug":true,"msg":"⚠ Execution failed.","time":"2021-11-30T13:21:35.192Z","v":0}`

I use docker on linux system. I restart docker without succes

**Comment by audioteka-mobile** [comment]
Anyone else has a similar problem? I'm considering redeploying but do not want to drop database.

**Comment by Rayn0r** [comment]
Just a shot in the dark, but is your machine's clock in sync with a time server?

**Comment by dtila** [comment]
Hi Rayn, 

I have the same issue, when I start the bot on my computer (not updating). I am not raising another issue, but write here instead.

So, I am using the docker-compose.server.yaml file to run and I have the same error on my Windows and Linux machine, and I am highly think is not a bug, since I have just synced my clock.

Maybe it's not considering the TimeZone?


```
node:45) UnhandledPromiseRejectionWarning: Error: Timestamp for this request is outside of the recvWindow.
binance-bot      |     at /srv/node_modules/binance-api-node/dist/http-client.js:93:17
binance-bot      |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
binance-bot      |     at async g (/srv/dist/server.js:1:49917)
binance-bot      |     at async b (/srv/dist/server.js:1:109394)
binance-bot      |     at async p (/srv/dist/server.js:1:109847)
binance-bot      |     at async runBinance (/srv/dist/server.js:1:110795)
binance-bot      |     at async /srv/dist/server.js:1:118906
```

**Comment by caebwallace** [comment]
Nope, your computer clock is not sync with atomic time, or you've latency.
Go to the doc API and search for recWindow : https://binance-docs.github.io/apidocs/voptions/en/#change-log
