### ISSUE TITLE
bot Not buying

### ISSUE THREAD

**Issue by abuvanth** [chrisleekr/binance-trading-bot#4]
{"name":"binance-api","version":"0.0.12","hostname":"5771f48662d2","pid":18,"job":"simpleStopChaser","uuid":"f0fca491-05a2-4546-a723-fa520a25a391","symbol":"BTCUSDT","symbolUuid":"ce0fba82-60dc-4bd3-8c0b-73603670cedf","level":50,"quantity":0,"msg":"Order quantity is less or equal than minimum quantity - 0.00000100.","time":"2021-01-18T15:34:45.412Z","v":0}

**Comment by abuvanth** [comment]
my balance in binance is 53USDT

**Comment by chrisleekr** [comment]
Hey @abuvanth 

I suggest you read the code and make sure you understand how it works. 
I won't support your case nor provide any tips as this is simply testing my code.
It is your responsibility to use it as it's your money.
Sorry for not being helpful.

**Comment by bavinsCo** [comment]
Guys, join the Telegram group to solve problems with each other ..

https://t.me/joinchat/z3cKyYFcx0NiOTA8
