### ISSUE TITLE
TradingView 500 Error

### ISSUE THREAD

**Issue by kucukaslancan** [chrisleekr/binance-trading-bot#400]
I'm getting this error and I haven't been able to find the cause even though I've searched

`{
  "_id": "61abeb82f6d7cc3200504d9d",
  "symbol": "BTCUSDT",
  "msg": "Error occurred while retrieving TradingView technical analysis...",
  "loggedAt": "2021-12-04T22:28:18.804Z",
  "data": {
    "uuid": "5ea96ab2-823e-4f49-a17d-30d080c120dd",
    "stepName": "get-tradingview",
    "err": {
      "message": "Request failed with status code 500",
      "name": "Error",
      "stack": "Error: Request failed with status code 500\n    at createError (/srv/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/srv/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/srv/node_modules/axios/lib/adapters/http.js:260:11)\n    at IncomingMessage.emit (events.js:412:35)\n    at endReadableNT (internal/streams/readable.js:1334:12)\n    at processTicksAndRejections (internal/process/task_queues.js:82:21)"
    }
  }
}`

**Comment by ersineser** [comment]
same for me. 👍

**Comment by chrisleekr** [comment]
Sorry for the late reply.

It looks like your tradingview container was not running.

I will close the issue. If you still have an issue, please open a new issue.
