### ISSUE TITLE
Can someone please tell me what can cause this error?

### ISSUE THREAD

**Issue by thesam1545** [chrisleekr/binance-trading-bot#412]
![image](https://user-images.githubusercontent.com/90088866/149622923-6ff8d676-6bf8-4b46-a2fc-6f918ef8e4ad.png)

![image](https://user-images.githubusercontent.com/90088866/149622926-532be8a3-675b-40ca-a4a2-12ac36a1adce.png)

I already changed my DNS to 1.1.1.1, because I searched it could be that, but it keeps happening and causing me losses... also, sometimes bot makes a buy and records last buy price but does not care about selling

**Comment by ilbuonmarcio** [comment]
Check your grid trade configuration, maybe it's corrupted for this coin pair, or even globally
