### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by korus93** [chrisleekr/binance-trading-bot#422]
[+] Running 0/4rading-bot-master> docker-compose -f docker-compose.server.yml pu
 - binance-redis Error                                                    11.1s
 - binance-bot Error                                                      11.1s
 - tradingview Error                                                      11.1s
 - binance-mongo Error                                                    11.1s
Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: TLS handshake timeout
[+] Running 0/4
 - binance-redis Error                                                    10.9s
 - tradingview Error                                                      10.9s
 - binance-mongo Error                                                    10.9s
 - binance-bot Error                                                      10.9s
Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: TLS handshake timeout

**Comment by chrisleekr** [comment]
This is nothing to do with the bot.

I will close the issue.
