### ISSUE TITLE
Stop-loss not execute

### ISSUE THREAD

**Issue by eth-man** [chrisleekr/binance-trading-bot#424]
## Version
v0.0.85

## Description
Stop loss not working 

## Expected Behaviours
Execute stop loss at the specified percentage

## Screenshots

![image](https://user-images.githubusercontent.com/8633885/167661947-372ea0b0-baf6-4ae0-9e04-eea948bb6c4c.png)

**Comment by hugoleosp** [comment]
Did you check if the coin had a value higher than the minimum for the trading pair? If the pair is */USDT, the minimum value for the coin has to be USDT 10, or the trade is not possible, otherwise the stop-loss won't trigger.

**Comment by chrisleekr** [comment]
Sorry for the late reply. 

You could check the log why the order is not executed. 

I will close the issue. If the issue continues, please open new issue.
