### ISSUE TITLE
Binance.US (Old issue already posted)

### ISSUE THREAD

**Issue by coltac** [chrisleekr/binance-trading-bot#425]
I am curious if this works with binance.us?  I saw the old issue, but not too much was said there.
I do have the bot installed ect, but am getting an invalid API key error (im guessing to do with it being the wrong exchange technically)
Just asking if there is a reasonable way to get this to work with binance.us, and have the WebSocket functionality.

**Comment by chrisleekr** [comment]
At this point, I don't have time to integrate with Binance.us. 
I will close the issue.
