### ISSUE TITLE
Is it possible to support later mongo version?

### ISSUE THREAD

**Issue by bobwng** [chrisleekr/binance-trading-bot#432]
Is it possible to upgrade mongo to some versions later?

I'm using arm64v8, but there is no v3.2 image: https://hub.docker.com/r/arm64v8/mongo , the earliest version is v4.0.28.

Not sure if anyone meet same problem to me.

**Comment by bobwng** [comment]
I changed the mongo image to arm64v8/mongo:3.4, and looks like good to me.

Maybe we can close this issue :)

**Comment by chrisleekr** [comment]
Hi @bobwng 

Thank you for your comment. 
I will close the issue.
