### ISSUE TITLE
No indication of the buy order has been rejected on Binance

### ISSUE THREAD

**Issue by uhliksk** [chrisleekr/binance-trading-bot#463]
## Version

v0.0.88 (unspecified)

## Description

Bot tried to put buy orders which has been rejected from Binance without the notice. User just see symbols with the trigger price clearly reached but no buy action is indicated.

## To Reproduce

It has happened while market was rapidly raising. Is it possible in time between bot measured the price for buy order and placed the buy order on the Binance the price just raised so much it was not possible to put this buy order with calculated price anymore?

Edit: see Additional context

## Expected Behaviours

There should be warning about the bot tried to put buy order and the buy order has been rejected on the Binance.

## Screenshots

There are only the log records indicating the buy action but no rejections logged:

![image](https://user-images.githubusercontent.com/37454226/183912027-e54f653d-3a19-41e4-8842-1999ebc196e8.png)

## Additional context

Example of log record:

`{"name":"binance-api","version":"0.0.88","hostname":"73b0809731b1","pid":45,"gitHash":"unspecified","server":"binance","jobName":"trailingTrade","correlationId":"e96b2362-794a-4315-8ace-953726201893","level":50,"err":{"message":"Stop price would trigger immediately.","name":"Error","stack":"Error: Stop price would trigger immediately.\n    at /srv/node_modules/binance-api-node/dist/http-client.js:100:17\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async execute (/srv/dist/server.js:1:38463)\n    at async /srv/dist/server.js:1:8847\n    at async errorHandlerWrapper (/srv/dist/server.js:1:87322)\n    at async P (/srv/dist/server.js:1:7295)","code":-2010},"errorCode":-2010,"debug":true,"msg":"⚠ Execution failed.","time":"2022-08-10T13:00:49.789Z","v":0}`

HBARBUSD was actually not raising at the time this issue occured:

![image](https://user-images.githubusercontent.com/37454226/183912684-669d87e8-00a3-46c9-8e36-13f290fccfbd.png)

**Comment by habibalkhabbaz** [comment]
Hello @uhliksk 
I am going to solve this in the coming PR
