### ISSUE TITLE
Too much empty space in Closed Trades

### ISSUE THREAD

**Issue by uhliksk** [chrisleekr/binance-trading-bot#475]
### Is your proposal related to a problem?

Closed Trades report is very ineffective taking too much space to show nothing.

### Describe the solution you'd like

Detailed information about `buy via` and `sell via` should be embedded as buy/sell amount tooltip thus there should be much more rows per page displayed.

### Describe alternatives you've considered

As an alternative there should be an option to collapse/expand detail section.

### Additional context

![image](https://user-images.githubusercontent.com/37454226/185083767-a29b2c4a-df36-4cda-bd9c-bbf8d7074740.png)

**Comment by chrisleekr** [comment]
100% agree.

**Comment by habibalkhabbaz** [comment]
I agree too :)

**Comment by uhliksk** [comment]
@chrisleekr @habibalkhabbaz 
OK. I'm already doing some UI improvements. I'll create PR for all of them.
