### ISSUE TITLE
Why the price is not change when in test mode

### ISSUE THREAD

**Issue by ienthach** [chrisleekr/binance-trading-bot#48]
i provide live and test api key and secret in .env file. And BINANCE_MODE = test in docker-compose.yml but the price is not tik tik.

But when mode = live the price change tik tik happen

**Comment by chrisleekr** [comment]
Because the test server for Binance does not have any transactions. :)

**Comment by ienthach** [comment]
so can we get transactions info from live then place order in test network?

**Comment by chrisleekr** [comment]
No

**Comment by chrisleekr** [comment]
If you want to use testnet, try with BNBUSDT in the testnet. And set candles to be 1m/5 something. BNBUSDT in the testnet moves a bit.

**Comment by ienthach** [comment]
:) thank you for your bot.
