### ISSUE TITLE
Has TV always been active for grid trades > 1?

### ISSUE THREAD

**Issue by Rayn0r** [chrisleekr/binance-trading-bot#482]
I upgraded to the latest version v0.0.89 (165d110) and noticed that grid trades >1 are also affected by the TradingView setting. In my case I had set it to: `Allow buy trigger when recommendation is Buy `.
If this affects grid trades as well, then grid trades are basically in-effective as long as the coin drops.
But from my understanding, grid trades should help counter the effect of the coin dropping.

Can someone please clarify this?

**Comment by chrisleekr** [comment]
Yes, the TradingView was applying to all grid trades. 

Please close the issue if your question is answered. :)

**Comment by Rayn0r** [comment]
The issue is still bugging me...
Why should TV be used for any Trade >1?
Then percentage set for each grid Trade to fire would be of no use. 
From my understanding, the right percentage is required in order to maintain the same percentage to break-even...
Here is an example, where we start at 50USDT at Grid Trad 1:

No| USDT | Grid % | Break Even %
-- | -- | -- | --
0 | 50.0000 | 1.0000 |  
1 | 10.0000 | 0.9809 | 0.8811
2 | 10.0000 | 0.9733 | 1.6664
3 | 25.3187 | 0.9701 | 2.0000
4 | 49.9498 | 0.9701 | 2.0000
5 | 76.1484 | 0.9701 | 1.9998
6 | 116.0669 | 0.9701 | 1.9997
7 | 176.7615 | 0.9701 | 2.0001
8 | 269.5341 | 0.9701 | 2.0000
9 | 410.7260 | 0.9701 | 2.0000
10 | 625.9767 | 0.9701 | 2.0000
This already requires 1820.48 USDT in order to maintain a break even of 2%. (And if I you are working with stop loss, then 96.9 will be your minimum here, right?)

If the percentage deviates from the given setup (because TV needs to approve the grid trade), then the break-even will shift, most likely to a higher value. This will break the entire calculation for the grid trades.
In my understanding only the 1st grid trade would benefit from TV.
@uhliksk @habibalkhabbaz @chrisleekr 
What is your opinion here?

And I noticed that checking the box `Allow buy trigger when recommendation is Buy` also seems to bypass the ATH setting. So if it is checked, it will buy even though the Restriction price percentage for ATH is not met. This is also not helpful in many situations.

**Comment by uhliksk** [comment]
@Rayn0r In my opinion TV needs to be applied to all trades because you always want to buy at the lowest price possible. When the market is going down it's sometimes oscilating with big amplitude which will cause you'll buy even when it's not neccessary and then it'll be harder to compensate the loss. It's better to skip falling market and buy the dip directly.

**Comment by chrisleekr** [comment]
@Rayn0r Right, so that is your strategy.

I think the solution is, simply to add a new option to apply TradingView to the first grid trade.
If anyone wants to apply to all grid trade, then uncheck the option.

When I get time (which I cannot guarantee when), I will add the option in.

**Comment by Rayn0r** [comment]
> It's better to skip falling market and buy the dip directly.

I never thought of it this way.
Let me do some calculations, on what happens to the break-even if you skip a few a grids on the way down and they all fire at one point(more or less).

**Comment by Rayn0r** [comment]
Contrary to what I thought, it even pays to use TV for grid trades.
I did a quick test on sequence of 7 additional grid trades with a break even of 1%. If TV does not allow to buy for 3 grids, and those 3 are all fired at once it is back to Buy/Strong Buy, then your break-even is down to 0.676164104%

@chrisleekr 
Thanks for the offer, but I think it is not necessary to implement TV for just Trade 1.
