### ISSUE TITLE
Grid Trade #1 Trigger price is not correct.

### ISSUE THREAD

**Issue by peweb** [chrisleekr/binance-trading-bot#485]
## Version
0.0.89

## Description
How is this price calculated to be $105 with my current settings 1m/30?

![image](https://user-images.githubusercontent.com/36623351/185924296-740f5914-66a5-4c31-b5ac-58c3cc2627d4.png)

**Comment by chrisleekr** [comment]
You are in TestNet. It's possible in TestNet.

If it's answered, please close the issue.

![image](https://user-images.githubusercontent.com/5715919/185924893-455a4fb0-ac47-42b1-a9bd-a3676401e50d.png)
