### ISSUE TITLE
Sort by Sell - Profit not working as expected

### ISSUE THREAD

**Issue by uhliksk** [chrisleekr/binance-trading-bot#491]
## Version

v0.0.89(165d110)

## Description

There are some symbols with not open trades on multiple pages while other are missing completely.

## To Reproduce

1. Add multiple symbol.
2. Sort by Sell - Profit (desc)
3. See some not traded symbols are listed on multiple pages, some symbols are not listed at all

## Expected Behaviours

There should be no duplicates or missing symbols when sorting is applied.

## Screenshots

Not traded symbols XMRBUSD, ATOMBUSD, EOSBUSD and ZECBUSD listed on page 5, 6 and 7 at once.

Page 5:
![image](https://user-images.githubusercontent.com/37454226/186359542-5d197236-773d-4c60-b3e5-d79ca6be4a20.png)

Page 6:
![image](https://user-images.githubusercontent.com/37454226/186359675-aa50eb65-16d9-4413-9b97-72aa413f9636.png)

Page 7:
![image](https://user-images.githubusercontent.com/37454226/186359804-f3e38170-2089-43eb-9dec-df53884b91bb.png)

## Additional context

Not traded symbol I mean symbol with trading enabled but no buy orders executed yet. There is no sell profit calculated for those symbols affected which is probably causing a confusion for the sorting algorithm.

**Comment by habibalkhabbaz** [comment]
Hello @uhliksk 

I think this will be solved by changing the following line to `'$symbol'` instead of assigning big numbers because all symbols will have the same number and cannot be sorted properly:

https://github.com/chrisleekr/binance-trading-bot/blob/5daea007cd5a1a30e3b911653f0b6e1f6b448b2a/app/cronjob/trailingTradeHelper/common.js#L981

**Comment by uhliksk** [comment]
Hello @habibalkhabbaz 

Thank you for the suggestion. I'm little bit busy those days so I'm just accumulating the issues. :) You can create PR if you wish or I can fix with other issues over the weekend.

**Comment by habibalkhabbaz** [comment]
Hi @uhliksk 
It is solved in #496 and it is merged by @chrisleekr

**Comment by uhliksk** [comment]
Hi @habibalkhabbaz 
Nice. I'm still busy a little bit. Thank you.
