### ISSUE TITLE
Updated order status causes mutliple grid trade execution 

### ISSUE THREAD

**Issue by chrisleekr** [chrisleekr/binance-trading-bot#494]
## Version

v0.0.89 (5daea00)
It's master version.

## Description

I had a coin that executed 1st grid trade and then the bot executed 2nd immediately after the filled order.

## To Reproduce

This cannot be reproduced unless meeting very specific conditions.

## Expected Behaviours

No 2nd grid trade execution

## Screenshots

Instead of the screenshot, I attached redacted archive order.

<details>
<summary>Click to see archived order JSON</summary>
{
  "_id": "63072e2a3e904d1fbad86ce9",
  "key": "STGBUSD-2022-08-25T08:09:14.419Z",
  "symbol": "STGBUSD",
  "baseAsset": "STG",
  "quoteAsset": "BUSD",
  "buyGridTradeExecuted": true,
  "sellGridTradeExecuted": true,
  "allExecuted": false,
  "totalBuyQuoteQty": 39.952299999999994,
  "totalSellQuoteQty": 41.28435,
  "buyGridTradeQuoteQty": 39.952299999999994,
  "buyManualQuoteQty": 0,
  "sellGridTradeQuoteQty": 41.28435,
  "sellManualQuoteQty": 0,
  "stopLossQuoteQty": 0,
  "profit": 1.3320500000000095,
  "profitPercentage": 3.3341009153415686,
  "buy": [
      {
          "triggerPercentage": 1,
          "stopPercentage": 1.02,
          "limitPercentage": 1.021,
          "maxPurchaseAmount": 10,
          "minPurchaseAmount": 10,
          "executed": true,
          "executedOrder": {
              "symbol": "STGBUSD",
              "orderId": 10735152,
              "orderListId": -1,
              "transactTime": 1661401488355,
              "currentGridTradeIndex": 0,
              "status": "FILLED",
              "type": "STOP_LOSS_LIMIT",
              "side": "BUY",
              "stopPrice": "0.84010000",
              "price": "0.84090000",
              "origQty": "12.00000000",
              "cummulativeQuoteQty": "10.08360000",
              "executedQty": "12.00000000",
              "isWorking": false,
              "updateTime": 1661401488356,
              "updateTimeHuman": "Thu 25 Aug 2022 04:24:48 UTC"
          }
      },
      {
          "triggerPercentage": 0.9,
          "stopPercentage": 1.001,
          "limitPercentage": 1.002,
          "maxPurchaseAmount": 15,
          "minPurchaseAmount": 15,
          "executed": true,
          "executedOrder": {
              "symbol": "STGBUSD",
              "orderId": 10739122,
              "orderListId": -1,
              "transactTime": 1661401493089,
              "currentGridTradeIndex": 1,
              "status": "FILLED",
              "type": "STOP_LOSS_LIMIT",
              "side": "BUY",
              "stopPrice": "0.83870000",
              "price": "0.83950000",
              "origQty": "17.80000000",
              "cummulativeQuoteQty": "14.94310000",
              "executedQty": "17.80000000",
              "isWorking": false,
              "updateTime": 1661401493089,
              "updatedTimeHuman": "Thu 25 Aug 2022 04:24:53 UTC"
          }
      },
      {
          "triggerPercentage": 0.9,
          "stopPercentage": 1.001,
          "limitPercentage": 1.002,
          "maxPurchaseAmount": 15,
          "minPurchaseAmount": 15,
          "executed": true,
          "executedOrder": {
              "symbol": "STGBUSD",
              "orderId": 10740407,
              "orderListId": -1,
              "transactTime": 1661401509139,
              "currentGridTradeIndex": 2,
              "status": "FILLED",
              "type": "STOP_LOSS_LIMIT",
              "side": "BUY",
              "stopPrice": "0.82840000",
              "price": "0.82920000",
              "origQty": "18.00000000",
              "cummulativeQuoteQty": "14.92560000",
              "executedQty": "18.00000000",
              "isWorking": false,
              "updateTime": 1661401509140,
              "updateTimeHuman": "Thu 25 Aug 2022 04:25:09 UTC"
          }
      },
      {
          "triggerPercentage": 0.9,
          "stopPercentage": 1.001,
          "limitPercentage": 1.002,
          "maxPurchaseAmount": 15,
          "minPurchaseAmount": 15,
          "executed": false,
          "executedOrder": null
      },
      {
          "triggerPercentage": 0.9,
          "stopPercentage": 1.001,
          "limitPercentage": 1.002,
          "maxPurchaseAmount": 15,
          "minPurchaseAmount": 15,
          "executed": false,
          "executedOrder": null
      },
      {
          "triggerPercentage": 0.9,
          "stopPercentage": 1.001,
          "limitPercentage": 1.002,
          "maxPurchaseAmount": 15,
          "minPurchaseAmount": 15,
          "executed": false,
          "executedOrder": null
      },
      {
          "triggerPercentage": 0.9,
          "stopPercentage": 1.001,
          "limitPercentage": 1.002,
          "maxPurchaseAmount": 15,
          "minPurchaseAmount": 15,
          "executed": false,
          "executedOrder": null
      },
      {
          "triggerPercentage": 0.9,
          "stopPercentage": 1.001,
          "limitPercentage": 1.002,
          "maxPurchaseAmount": 15,
          "minPurchaseAmount": 15,
          "executed": false,
          "executedOrder": null
      },
      {
          "triggerPercentage": 0.9,
          "stopPercentage": 1.001,
          "limitPercentage": 1.002,
          "maxPurchaseAmount": 15,
          "minPurchaseAmount": 15,
          "executed": false,
          "executedOrder": null
      },
      {
          "triggerPercentage": 0.9,
          "stopPercentage": 1.001,
          "limitPercentage": 1.002,
          "maxPurchaseAmount": 15,
          "minPurchaseAmount": 15,
          "executed": false,
          "executedOrder": null
      }
  ],
  "sell": [
      {
          "triggerPercentage": 1.04,
          "stopPercentage": 0.99,
          "limitPercentage": 0.985,
          "quantityPercentage": 1,
          "executed": true,
          "executedOrder": {
              "symbol": "STGBUSD",
              "orderId": 10972528,
              "orderListId": -1,
              "transactTime": 1661414917406,
              "currentGridTradeIndex": 0,
              "status": "FILLED",
              "type": "STOP_LOSS_LIMIT",
              "side": "SELL",
              "stopPrice": "0.86620000",
              "price": "0.86180000",
              "origQty": "47.70000000",
              "cummulativeQuoteQty": "41.28435000",
              "executedQty": "47.70000000",
              "isWorking": false,
              "updateTime": 1661414917407
          }
      }
  ],
  "archivedAt": "2022-08-25T08:09:14.419Z"
}

</details>

## Additional context

To find out what happened, I exported the log and traced what happened.

CorrelationId | Time | Job Name | Step Name | OrderId | Message | Comment
-- | -- | -- | -- | -- | -- | --
  | 2022-08-25T04:23:27.618Z | binance | executionReport | 10731333 | There is a new update in order. 10731333 - BUY - CANCELED |  
  | 2022-08-25T04:23:27.625Z | binance | executionReport | 10731333 | The last order has been updated. |  
8edc799a-165f-45d6-bf84-ba7fc0c70d67 | 2022-08-25T04:23:27.720Z | trailingTrade | place-buy-order | 10735152 | The grid trade #1 buy order has been placed. |  
  | 2022-08-25T04:23:27.802Z | binance | executionReport | 10735152 | There is a new update in order. 10735152 - BUY - NEW |  
  | 2022-08-25T04:23:27.806Z | binance | executionReport | 10735152 | The last order has been updated. |  
8edc799a-165f-45d6-bf84-ba7fc0c70d67 | 2022-08-25T04:23:27.920Z | trailingTrade | place-buy-order | 10735152 | Placed new stop loss limit order for buying of grid trade #1. |  
  | 2022-08-25T04:24:48.503Z | binance | executionReport | 10735152 | There is a new update in order. 10735152 - BUY - NEW |  OrderTime: 1661401488355
  | 2022-08-25T04:24:48.506Z | binance | executionReport | 10735152 | There is a new update in order. 10735152 - BUY - FILLED |  OrderTime: 1661401488355
  | 2022-08-25T04:24:48.507Z | binance | executionReport | 10735152 | The last order has been updated. | status is NEW
d59fadc2-a591-4dd3-815b-42790e91fbfe | 2022-08-25T04:24:48.514Z | trailingTrade | ensure-grid-trade-order-executed | 10735152 | The grid trade order has filled. Calculating last buy price... |  
d59fadc2-a591-4dd3-815b-42790e91fbfe | 2022-08-25T04:24:48.515Z | trailingTrade | ensure-grid-trade-order-executed |   | The last buy price will be saved. New last buy price: 0.8403 |  
d59fadc2-a591-4dd3-815b-42790e91fbfe | 2022-08-25T04:24:48.515Z | trailingTrade | ensure-grid-trade-order-executed |   | The last buy price has been saved. |  
d59fadc2-a591-4dd3-815b-42790e91fbfe | 2022-08-25T04:24:48.522Z | trailingTrade | ensure-grid-trade-order-executed | 10735152 | The grid trade has been updated. | buy grid trade #1 is executed
d59fadc2-a591-4dd3-815b-42790e91fbfe | 2022-08-25T04:24:48.534Z | trailingTrade | ensure-grid-trade-order-executed | 10735152 | The buy order of the grid trade #1 for STGBUSD has been executed successfully. |  
d59fadc2-a591-4dd3-815b-42790e91fbfe | 2022-08-25T04:24:48.535Z | trailingTrade | ensure-grid-trade-order-executed |   | The action is disabled. Reason: Disabled action after confirming filled grid trade order. |  
77bd129e-320a-4ee6-a789-e596eb4ec428 | 2022-08-25T04:24:48.665Z | trailingTrade | handle-open-orders |   | Stop price is higher than buy limit price, cancel current buy order |  
77bd129e-320a-4ee6-a789-e596eb4ec428 | 2022-08-25T04:24:48.665Z | trailingTrade | handle-open-orders | 10735152 | The BUY order will be cancelled. |  
77bd129e-320a-4ee6-a789-e596eb4ec428 | 2022-08-25T04:24:49.305Z | trailingTrade | handle-open-orders |   | Order cancellation failed, but it is ok. The order may already be cancelled or executed. The bot will check in the next tick. |  
77bd129e-320a-4ee6-a789-e596eb4ec428 | 2022-08-25T04:24:49.909Z | trailingTrade | handle-open-orders |   | The override action is saved. Reason: The bot will place a buy order in the next tick because could not retrieve the cancelled order result. |  
e9a8895d-b472-4791-bc4b-91ec3d365685 | 2022-08-25T04:24:49.936Z | trailingTrade | get-override-action |   | The override data is removed. |  
e9a8895d-b472-4791-bc4b-91ec3d365685 | 2022-08-25T04:24:49.942Z | trailingTrade | place-buy-order |   | The grid trade #2 buy order will be placed. |  
e9a8895d-b472-4791-bc4b-91ec3d365685 | 2022-08-25T04:24:50.498Z | trailingTrade | place-buy-order | 10739122 | The grid trade #2 buy order has been placed. |  

The key issue is this log.

CorrelationId | Time | Job Name | Step Name | OrderId | Message | Comment
-- | -- | -- | -- | -- | -- | --
8edc799a-165f-45d6-bf84-ba7fc0c70d67 | 2022-08-25T04:23:27.920Z | trailingTrade | place-buy-order | 10735152 | Placed new stop loss limit order for buying of grid trade #1. |  
  | 2022-08-25T04:24:48.503Z | binance | executionReport | 10735152 | There is a new update in order. 10735152 - BUY - NEW |  OrderTime: 1661401488355
  | 2022-08-25T04:24:48.506Z | binance | executionReport | 10735152 | There is a new update in order. 10735152 - BUY - FILLED |  OrderTime: 1661401488355
  | 2022-08-25T04:24:48.507Z | binance | executionReport | 10735152 | The last order has been updated. | status is NEW
d59fadc2-a591-4dd3-815b-42790e91fbfe | 2022-08-25T04:24:48.514Z | trailingTrade | ensure-grid-trade-order-executed | 10735152 | The grid trade order has filled. Calculating last buy price... |  

As you can see, the `executionReport` received `new` buy order at `2022-08-25T04:24:48.503Z`.
003 ms later, it received `filled` buy order at `2022-08-25T04:24:48.506Z`.
001 ms later, it updated the last order for the `new` buy order.
But there is no saving action for `filled` buy order.

As a result, in the next tick, it attempts to cancel `filled` buy order and fails, which is expected because the order is already filled.

CorrelationId | Time | Job Name | Step Name | OrderId | Message | Comment
-- | -- | -- | -- | -- | -- | --
77bd129e-320a-4ee6-a789-e596eb4ec428 | 2022-08-25T04:24:48.665Z | trailingTrade | handle-open-orders |   | Stop price is higher than buy limit price, cancel current buy order
77bd129e-320a-4ee6-a789-e596eb4ec428 | 2022-08-25T04:24:48.665Z | trailingTrade | handle-open-orders | 10735152 | The BUY order will be cancelled.
77bd129e-320a-4ee6-a789-e596eb4ec428 | 2022-08-25T04:24:49.305Z | trailingTrade | handle-open-orders |   | Order cancellation failed, but it is ok. The order may already be cancelled or executed. The bot will check in the next tick.
77bd129e-320a-4ee6-a789-e596eb4ec428 | 2022-08-25T04:24:49.909Z | trailingTrade | handle-open-orders |   | The override action is saved. Reason: The bot will place a buy order in the next tick because could not retrieve the cancelled order result.

And it saves the override data to execute `buy` in the next tick.

CorrelationId | Time | Job Name | Step Name | OrderId | Message | Comment
-- | -- | -- | -- | -- | -- | --
e9a8895d-b472-4791-bc4b-91ec3d365685 | 2022-08-25T04:24:49.936Z | trailingTrade | get-override-action |   | The override data is removed.
e9a8895d-b472-4791-bc4b-91ec3d365685 | 2022-08-25T04:24:49.942Z | trailingTrade | place-buy-order |   | The grid trade #2 buy order will be placed.
e9a8895d-b472-4791-bc4b-91ec3d365685 | 2022-08-25T04:24:50.498Z | trailingTrade | place-buy-order | 10739122 | The grid trade #2 buy order has been placed.

I checked the code block in `app/binance/user.js`

```
if (
  orderId !== lastOrder.orderId ||
  transactTime < lastOrder.transactTime
) {
  return;
}
```

I think `FILLED` order update is skipped because the last buy order's `orderId` is different. 

I suggest we update the code block as the below:

```
if (
  transactTime < lastOrder.transactTime
) {
  return;
}
```

We don't need to check `orderId` as we want to have the latest order status.
What do you think @habibalkhabbaz ?

**Comment by chrisleekr** [comment]
Hm, no. If we remove the orderId check, then it would cause the original issue. What would be better solution? Implementing queue for updating order status update?

**Comment by habibalkhabbaz** [comment]
Hello @chrisleekr 

The ideal solution is to implement queue for orders but let's dig deep into this for a simpler solution.

I will assume the following scenario happened to you.

> Another scenario is

1. Order A - New
2. Order B - New
3. Order B - Filled

However, in fact, the `orderId` should not be changed unless it was canceled and I see two updates for `NEW` status from the log.

So, here is the updated scenario:

1. Order A - New
2. Order A - Canceled
3. Order B - New
4. Order B - New
5. Order B - Filled

Step 4 and 5 almost reported at the same time, so the filled order is skipped and stuck on step 3.

Based on that, if that is correct, then the issue is not with the orderId.

Also, I see from the log that the `ensure-grid-trade-order-executed` step found the order is FILLED that means the grid trade is updated with the latest status and here I get confused.
Maybe something is missed in the log.

**Comment by chrisleekr** [comment]
You are right. Maybe something else is going on.

Here are more logs.

Time | Job Name | Step Name | OrderId | Message | Comment
-- | -- | -- | -- | -- | --
2022-08-25T04:23:27.802Z | binance | executionReport | 10735152 | There is a new update in order. 10735152 - BUY - NEW | OrderTime: 1661401407655
2022-08-25T04:23:27.806Z | binance | executionReport | 10735152 | The last order has been updated. | No status
2022-08-25T04:24:48.503Z | binance | executionReport | 10735152 | There is a new update in order. 10735152 - BUY - NEW | OrderTime: 1661401488355
2022-08-25T04:24:48.506Z | binance | executionReport | 10735152 | There is a new update in order. 10735152 - BUY - FILLED | OrderTime: 1661401488355
2022-08-25T04:24:48.507Z | binance | executionReport | 10735152 | The last order has been updated. | status is NEW


These are individual logs.

Time | Job Name | Step Name | OrderId | Message | Comment
-- | -- | -- | -- | -- | --
2022-08-25T04:23:27.802Z | binance | executionReport | 10735152 | There is a new update in order. 10735152 - BUY - NEW | OrderTime: 1661401407655

```
{
        "eventType": "executionReport",
        "eventTime": 1661401407655,
        "symbol": "STGBUSD",
        "originalClientOrderId": "",
        "side": "BUY",
        "orderType": "STOP_LOSS_LIMIT",
        "timeInForce": "GTC",
        "quantity": "12.00000000",
        "price": "0.84090000",
        "executionType": "NEW",
        "stopPrice": "0.84010000",
        "icebergQuantity": "0.00000000",
        "orderStatus": "NEW",
        "orderRejectReason": "NONE",
        "orderId": 10735152,
        "orderTime": 1661401407655,
        "lastTradeQuantity": "0.00000000",
        "totalTradeQuantity": "0.00000000",
        "priceLastTrade": "0.00000000",
        "commission": "0",
        "commissionAsset": null,
        "tradeId": -1,
        "isOrderWorking": false,
        "isBuyerMaker": false,
        "creationTime": 1661401407655,
        "totalQuoteTradeQuantity": "0.00000000",
        "orderListId": -1,
        "quoteOrderQuantity": "0.00000000",
        "lastQuoteTransacted": "0.00000000"
      }
```

Time | Job Name | Step Name | OrderId | Message | Comment
-- | -- | -- | -- | -- | --
2022-08-25T04:23:27.806Z | binance | executionReport | 10735152 | The last order has been updated. |  

```
{
      "lastOrder": {
        "symbol": "STGBUSD",
        "orderId": 10735152,
        "orderListId": -1,
        "clientOrderId": "rB1JjP00vKb0HBrdXKm1Ia",
        "transactTime": 1661401407655,
        "currentGridTradeIndex": 0
      }
    }
```

It found the last order `10735152` and updated it. So it means, `orderId` and `transacTime` are valid.

Time | Job Name | Step Name | OrderId | Message | Comment
-- | -- | -- | -- | -- | --
2022-08-25T04:24:48.503Z | binance | executionReport | 10735152 | There is a new update in order. 10735152 - BUY - NEW | OrderTime: 1661401488355


```
{
        "eventType": "executionReport",
        "eventTime": 1661401488356,
        "symbol": "STGBUSD",
        "originalClientOrderId": "",
        "side": "BUY",
        "orderType": "STOP_LOSS_LIMIT",
        "timeInForce": "GTC",
        "quantity": "12.00000000",
        "price": "0.84090000",
        "executionType": "NEW",
        "stopPrice": "0.84010000",
        "icebergQuantity": "0.00000000",
        "orderStatus": "NEW",
        "orderRejectReason": "NONE",
        "orderId": 10735152,
        "orderTime": 1661401488355,
        "lastTradeQuantity": "0.00000000",
        "totalTradeQuantity": "0.00000000",
        "priceLastTrade": "0.00000000",
        "commission": "0",
        "commissionAsset": null,
        "tradeId": -1,
        "isOrderWorking": true,
        "isBuyerMaker": false,
        "creationTime": 1661401407655,
        "totalQuoteTradeQuantity": "0.00000000",
        "orderListId": -1,
        "quoteOrderQuantity": "0.00000000",
        "lastQuoteTransacted": "0.00000000"
      }
```

After 1 min 21 secs later, received a new execution report. 

Time | Job Name | Step Name | OrderId | Message | Comment
-- | -- | -- | -- | -- | --
2022-08-25T04:24:48.506Z | binance | executionReport | 10735152 | There is a new update in order. 10735152 - BUY - FILLED | OrderTime: 1661401488355

```
{
        "eventType": "executionReport",
        "eventTime": 1661401488356,
        "symbol": "STGBUSD",
        "originalClientOrderId": "",
        "side": "BUY",
        "orderType": "STOP_LOSS_LIMIT",
        "timeInForce": "GTC",
        "quantity": "12.00000000",
        "price": "0.84090000",
        "executionType": "TRADE",
        "stopPrice": "0.84010000",
        "icebergQuantity": "0.00000000",
        "orderStatus": "FILLED",
        "orderRejectReason": "NONE",
        "orderId": 10735152,
        "orderTime": 1661401488355,
        "lastTradeQuantity": "12.00000000",
        "totalTradeQuantity": "12.00000000",
        "priceLastTrade": "0.84030000",
        "commission": "0.00002519",
        "commissionAsset": "BNB",
        "tradeId": 829958,
        "isOrderWorking": false,
        "isBuyerMaker": false,
        "creationTime": 1661401407655,
        "totalQuoteTradeQuantity": "10.08360000",
        "orderListId": -1,
        "quoteOrderQuantity": "0.00000000",
        "lastQuoteTransacted": "10.08360000"
      }
```

Time | Job Name | Step Name | OrderId | Message | Comment
-- | -- | -- | -- | -- | --
2022-08-25T04:24:48.507Z | binance | executionReport | 10735152 | The last order has been updated. | status is NEW

```
{
      "lastOrder": {
        "symbol": "STGBUSD",
        "orderId": 10735152,
        "orderListId": -1,
        "transactTime": 1661401407655,
        "currentGridTradeIndex": 0,
        "status": "NEW",
        "type": "STOP_LOSS_LIMIT",
        "side": "BUY",
        "stopPrice": "0.84010000",
        "price": "0.84090000",
        "origQty": "12.00000000",
        "cummulativeQuoteQty": "0.00000000",
        "executedQty": "0.00000000",
        "isWorking": false,
        "updateTime": 1661401407655
      }
    }
```

As we only logged `lastOrder`, we don't know the final order status saved in the database. The last order was `isWorking` false. It means the last order was step 3, not step 4. It makes sense as the event occurred within 3ms. 

I've uploaded the full log file - https://gist.github.com/chrisleekr/1bce1b162652b6197d76b17f963aa95e

Are you able to see any strange issues?

**Comment by habibalkhabbaz** [comment]
Hello @chrisleekr 

I think I found the issue.
From what I see, the issue somehow is related to the open orders.
Because the grid trade order is updated successfully without an issue and it is reached this line:

https://github.com/chrisleekr/binance-trading-bot/blob/5daea007cd5a1a30e3b911653f0b6e1f6b448b2a/app/cronjob/trailingTrade/step/ensure-grid-trade-order-executed.js#L216

So, no issue with updating the grid trade order.
However, the open orders is not updated directly.
Hence, the bot will do the following because it was failed to cancel the filled order:

https://github.com/chrisleekr/binance-trading-bot/blob/5daea007cd5a1a30e3b911653f0b6e1f6b448b2a/app/cronjob/trailingTrade/step/handle-open-orders.js#L169

With this, the bot will try to put another buy order!
 
Based on that, I think we have to call `getAndCacheOpenOrdersForSymbol` immediately after an order is filled inside `ensure-grid-trade-order-executed.js` so that the bot will not try to cancel the already filled order and will not place another buy order.

**Comment by chrisleekr** [comment]
Ahh.... right.
After `ensure-grid-trade-order-executed` it didn't update open orders, so it was executing `handle-open-orders`.
Good find.

Let me update PR with the fix.

**Comment by chrisleekr** [comment]
@habibalkhabbaz 

It's updated. Could you review it, please? 
https://github.com/chrisleekr/binance-trading-bot/pull/495

**Comment by habibalkhabbaz** [comment]
Hello @chrisleekr 

Thanks for the update.
I just posted there. I see it's very good.
