### ISSUE TITLE
how to properly upgrade a live bot?

### ISSUE THREAD

**Issue by rando128** [chrisleekr/binance-trading-bot#497]
I'm running version v0.0.89 (165d110) and I would like to upgrade to the next available version (v0.0.90). As I didn't find specific documentation for upgrading, and since I have active trades, I want to make sure I don't mess up.

Can someone confirm that the following commands sequence is correct to upgrade a running bot:

```
git pull
docker-compose -f docker-compose.server.yml pull
docker restart binance-bot
```

**Comment by Rayn0r** [comment]
I usually do:
```
git pull
docker-compose -f docker-compose.server.yml pull
docker-compose -f docker-compose.server.yml down && sleep 5 && docker-compose -f docker-compose.server.yml up -d
```
just in case the docker images for the other components have changed as well.

**Comment by rando128** [comment]
Thx @Rayn0r. I’ll do a PR to update the doc accordingly.
