### ISSUE TITLE
3rd grid trade bought above last buy price

### ISSUE THREAD

**Issue by Rayn0r** [chrisleekr/binance-trading-bot#504]
## Version

Version: v0.0.90 (48865a0)
Latest Version:
[v0.0.90](https://github.com/chrisleekr/binance-trading-bot/releases)

## Description

I have set up 6 grid trades for CHZUSDT that are only supposed to be executed when TV is Strong Buy.
Today a spike caused the grid trade to fire above the last buy price. Which caused the last buy price to rise as well.
```
{
  "orgLastBuyPrice": 0.19279549839228294,
  "orgQuantity": 311,
  "orgTotalAmount": 59.959399999999995,
  "newLastBuyPrice": 0.19326044905008632,
  "newQuantity": 579,
  "newTotalAmount": 111.89779999999999
}
```

## Expected Behaviours

Would it be possible not to order additional coins, once the current price is above last buy price?
I do not see any advantage in doing so, other than to wait for the coin to climb some additional points...

**Comment by chrisleekr** [comment]
Hi @Rayn0r 

Sorry for the late reply.
Can you provide the log when it's happening?
