### ISSUE TITLE
Uncaught Exception:

### ISSUE THREAD

**Issue by peweb** [chrisleekr/binance-trading-bot#505]
## Version
v0.0.90 (48865a0)

## Description
I got a series of the same error on Slack::

 Uncaught Exception:
If you see this, kindly report it ...
Code: undefined
Message:
WebSocket was closed before the connection was established
- Current API Usage: 11

it was like about 30 messages like the above in a row and then got this as the last message on Slack:

Execution failed:
Job: Orders
Code: EAI_AGAIN
Message:
request to https://api.binance.com/api/v3/openOrders?recvWindow=10000&timestamp=1663246202302&signature=xxx failed, reason: getaddrinfo EAI_AGAIN [api.binance.com](http://api.binance.com/)
- Current API Usage: 41

## To Reproduce

Bot was started today in live mode.

**Comment by rando128** [comment]
This is due to a DNS issue on your infrastructure. Your server is unable to resolve the api.binance.com address. It's not a bug, simply an operational issue on your side. Try to restart your server.

**Comment by peweb** [comment]
> This is due to a DNS issue on your infrastructure. Your server is unable to resolve the api.binance.com address. It's not a bug, simply an operational issue on your side. Try to restart your server.

Thank you!
Did you refer the second error - Code: EAI_AGAIN or the first one with Uncaught Exception?

**Comment by rando128** [comment]
The 2 errors are related and the consequence of the DNS issue.

**Comment by peweb** [comment]
> The 2 errors are related and the consequence of the DNS issue.

Okay, thanks!

Can I fix this maybe by implementing a DNS cache?

**Comment by rando128** [comment]
Are you saying you still have the issue? 

If the output of the command `nslookup api.binance.com`, gives you an error like server `can't find api.binance.com: NXDOMAIN,` then your DNS config is not correct.

**Comment by peweb** [comment]
> Are you saying you still have the issue?
> 
> If the output of the command `nslookup api.binance.com`, gives you an error like server `can't find api.binance.com: NXDOMAIN,` then your DNS config is not correct.

I get this error several times per day, every day.  When this happens I get 10-15 messages on Slack all within a minute or less. Then it works fine and the issue repeats on the next day at a different time again 10-15 messages on Slack within a minute.

**Comment by rando128** [comment]
Then it's worth enabling DNS cache on your OS.

**Comment by peweb** [comment]
@rando128 Thank you for your support!
I set up the VPS DNS to OpenDNS servers and it works like a charm.
