### ISSUE TITLE
I can not understand if the bot works?

### ISSUE THREAD

**Issue by prada96prada** [chrisleekr/binance-trading-bot#507]
I can not understand if the bot works?

Hello, I'm sorry, my English may not be perfect. I'm using Mac!

The problem is that I connected my API and everything is displayed in the bot, I work through Docker.

However, the bot does not buy or sell anything, maybe I did something wrong? What is my mistake?

Before that, I also bought BTC on Binance, and for some reason the bot did not react in any way to my commands to sell, neither manually, nor by Trigger! What could be the problem?

Maybe there is something wrong with the config?

I am attaching screenshots, I ask for help, because this program looks very interesting!

Thank you!

![image](https://user-images.githubusercontent.com/114038177/191393220-e706953f-bdcf-4ead-9baa-ed2b513f3a79.png)

<img width="1127" alt="image" src="https://user-images.githubusercontent.com/114038177/191393593-4f5f6d40-e1ec-4ea2-8c94-c47837afa200.png">

**Comment by prada96prada** [comment]
<img width="363" alt="image" src="https://user-images.githubusercontent.com/114038177/191393890-2c0a55e8-07b8-42e4-840d-041622351efc.png">

And even when I see "Action buy will be executed in a minute, triggered by buy-order-trading-view." message - nothing happens (((

**Comment by Rayn0r** [comment]
You probably set TV to only buy when recommendation is "Strong Buy". That's why it will wait until the order is executed:
![image](https://user-images.githubusercontent.com/4147858/191469331-779b9a4f-9009-49be-9e1f-7bbd3797e315.png)

**Comment by prada96prada** [comment]
Would you recommend enabling both? Or disable both?

> You probably set TV to only buy when recommendation is "Strong Buy". That's why it will wait until the order is executed: ![image](https://user-images.githubusercontent.com/4147858/191469331-779b9a4f-9009-49be-9e1f-7bbd3797e315.png)

**Comment by prada96prada** [comment]
Oh it's works! Here is the problem, in my API Binance key was out of dated permissions! I'm sorry that disturbed you! Thanks!!!!

**Comment by Rayn0r** [comment]
That question cannot be answered with a simple "yes" or "no", since it depends on your strategy and the coin you are trading.

**Comment by Rayn0r** [comment]
Because you set it up under Grid Trades. The higher you set Stop Price and Limit Price percentage, the higher you buy the coin:
![image](https://user-images.githubusercontent.com/4147858/191591455-ad7b4190-9f6e-4d87-9f59-138247d7d4fe.png)
