### ISSUE TITLE
Frontent does not open

### ISSUE THREAD

**Issue by antoniocmoura** [chrisleekr/binance-trading-bot#508]
Hello, I'm trying to use the bot, but I can't access the frontend, the screen is locked after authentication.
I checked the containers and they are all running and I didn't find any error logs, could someone help me?

![docker](https://user-images.githubusercontent.com/8505899/191949697-4d158032-8498-41cd-a785-e0b0585ddade.png)
![auth](https://user-images.githubusercontent.com/8505899/191949738-21aa2881-5742-461d-b5df-a8fa6250bab6.png)
![home](https://user-images.githubusercontent.com/8505899/191949751-2ad0e20f-d6d7-41c7-ae94-28b00a807cec.png)

**Comment by anasschbani20** [comment]
Same here

**Comment by peweb** [comment]
Just happened to my bot today. It was working fine for 2 weeks now. 
It doesnt send anyting to Slack anymore and I cant login. 
How to troubleshoot this?
Restart didnt help.

**Comment by chrisleekr** [comment]
@peweb This issue is nothing to do with what you are experiencing. 
Refer #520 and update your bot.

**Comment by chrisleekr** [comment]
@antoniocmoura 

You will need to check the bot container log and see any error message.

**Comment by habibalkhabbaz** [comment]
Hello @antoniocmoura 

As @chrisleekr said, you have to check the container logs or slack notifications for any error message.

Also, the latest version `v0.0.93` may help here. Try it.

**Comment by antoniocmoura** [comment]
I managed to run it by changing the target and BINANCE_MODE lines in the docker-compose.yml file for production.
Thanks.
