### ISSUE TITLE
Newbie question

### ISSUE THREAD

**Issue by eppenga** [chrisleekr/binance-trading-bot#510]
Thank you very much for this great application. I have it running now for half a year and it is my only profitable bot :)

**Could I please ask a few questions:**
- What is the reason behind a MINIMUM and a MAXIMUM purchase amount? Why not a single purchase amount? What does the difference between minimum and maximum do? Is it sensible to set it to just 20 and 20 BUSD or does 20 and 50 make a difference or does it just choose closest to 50 then?
- Does the *"Force sell at the market price when recommendation is Neutral/Sell/Strong Sell and the profit is between 0 to trigger price"* still work when you are using multiple grids for sell and it has already gone through the first grid of sell? I seem to get a message then that it needs to wait for a grid sell that already occurred?
-  Am I correct to assume that the TRAILING of buy/sell does not work when then stop/limit percentage is higher than the trigger percentage?

Thank you so much!

**Comment by chrisleekr** [comment]
Sorry for the late reply.

> What is the reason behind a MINIMUM and a MAXIMUM purchase amount? Why not a single purchase amount? What does the difference between minimum and maximum do? Is it sensible to set it to just 20 and 20 BUSD or does 20 and 50 make a difference or does it just choose closest to 50 then?

If you set the minimum/maximum purchase amount, then the bot will place an order with an amount between 20 and 50. 
For example, if your quote asset balance is less than 20, then it won't place an order.
Or if your quote asset balance is more than 50, then it will only place 50.

> Does the "Force sell at the market price when recommendation is Neutral/Sell/Strong Sell and the profit is between 0 to trigger price" still work when you are using multiple grids for sell and it has already gone through the first grid of sell? I seem to get a message then that it needs to wait for a grid sell that already occurred?

If your grid sell is executed, then your balance will be close to 0, if your sell grid is configured to sell 100%. Then the bot will try to remove the last buy price.
What do you mean by `I seem to get a message then that it needs to wait for a grid sell that already occurred?` Can you give a more detailed scenario?

> Am I correct to assume that the TRAILING of buy/sell does not work when then stop/limit percentage is higher than the trigger percentage?

Sorry, hard to understand your question. What exact scenario are you talking about?
