### ISSUE TITLE
How to access the bot interface on secure connection :443?

### ISSUE THREAD

**Issue by peweb** [chrisleekr/binance-trading-bot#513]
## Version
v0.0.90 (48865a0)

## Description
Currently the bot inteface is accessable via unsequre connection on port 8080

How can I access the bot interface via https?

I have SSL enabled VPS with http rediretced to https

Thanks!

**Comment by rando128** [comment]
HTTPS is supported via localtunnel. Please refer to https://github.com/chrisleekr/binance-trading-bot/issues/112

**Comment by peweb** [comment]
> HTTPS can be easily supported via localtunnel. Please refer to #112

Can I access it wihtout localtunnel at IP:8443 secuqre connection?

**Comment by rando128** [comment]
Yes, it's a matter of setting up your infra to enable SSL at your load-balancer level (to handle :443) and then to route the unencrypted traffic to port 8080. This is obviously not really related to the bot itself but rather to devops work.

**Comment by chrisleekr** [comment]
I assume the question is answered. I close the issue.
