### ISSUE TITLE
Slack Log Levels?

### ISSUE THREAD

**Issue by peweb** [chrisleekr/binance-trading-bot#515]
## Version
0.90

## Description
The bot is connected to Slack and reports all events. Can I limit what bot sends to Slack and filter out all trailing messages?

**Comment by habibalkhabbaz** [comment]
Hello @peweb 
It is not possible right now but you can submit a PR if you like

**Comment by chrisleekr** [comment]
The PR has been merged.
Close the issue.

**Comment by peweb** [comment]
@chrisleekr 
@rando128 

How can I set notifyOrderConfirm notifyDebug to false?

**Comment by habibalkhabbaz** [comment]
Hello @peweb 

Add these lines to your `.env` file:

```
BINANCE_FEATURE_TOGGLE_NOTIFY_DEBUG=false
BINANCE_FEATURE_TOGGLE_NOTIFY_ORDER_CONFIRM=false
```
