### ISSUE TITLE
axios.post is not a function

### ISSUE THREAD

**Issue by antoniocmoura** [chrisleekr/binance-trading-bot#520]
Hello, I'm trying to run the bot but when logging in it's showing this error message on the console. Could anyone tell me how I can solve it?

I'm running the following commands to run the bot:

git pull
docker-compose -f docker-compose.server.yml pull
docker-compose -f docker-compose.server.yml up -d

![Captura de tela 2022-10-06 191007](https://user-images.githubusercontent.com/8505899/194428047-ba57e90e-2934-4e86-a07e-2a9228aada35.png)

**Comment by antoniocmoura** [comment]
I think the problem is in the new version of Axios, changing the axios import in index.html to version 0.27.2 worked again:

"https://unpkg.com/axios@0.27.2/dist/axios.js"

**Comment by habibalkhabbaz** [comment]
Hello @antoniocmoura 

Yes, you are right, it is pointing to the latest version (v1.0) which is released 2 days ago.
We have to choose a specific version in the CDN to solve the problem.
I am going to submit a PR for this.

**Comment by chrisleekr** [comment]
Sorry guys for the late reply.

I will merge in and release soon.

**Comment by chrisleekr** [comment]
merged.
