### ISSUE TITLE
How to backup data base and bot settings

### ISSUE THREAD

**Issue by peweb** [chrisleekr/binance-trading-bot#523]
## Version

Last 0.93

## Description

How can I backup bot settings and database with a cron job?
I think this will be usefull when bot is trading live and we need to recover data in case of issue.

**Comment by habibalkhabbaz** [comment]
Hello @peweb 

I think you can simply do:

```sh
cd /path/to/your/binance-bot && ./scripts/backup.sh binance-mongo 27017 binance-bot /tmp/backup-20220828.archive
```

I didn't check the command but I think it will work like that.
Please note that you have to change the path and the parameters based on your configurations

Close the issue if I answer your question :)

**Comment by peweb** [comment]
> 

Thanks! 

I dont have backup.sh and restore.sh in scripts even after

  docker-compose -f docker-compose.server.yml pull
  docker-compose -f docker-compose.server.yml up -d

P.S. What is 27017 ?

**Comment by habibalkhabbaz** [comment]
`27017` the default port number for mongo db connection.
`scripts` folder should be located in your binance bot main directory .

Try to do `git pull` in your binance bot directory.

**Comment by chrisleekr** [comment]
Hello 

you should be able to download backup from front end.

![](https://user-images.githubusercontent.com/5715919/189330938-6cf5f573-2ecb-49d9-8f34-7d1513b57b5c.png)

**Comment by peweb** [comment]
> Hello @peweb
> 
> I think you can simply do:
> 
> ```shell
> cd /path/to/your/binance-bot && ./scripts/backup.sh binance-mongo 27017 binance-bot /tmp/backup-20220828.archive
> ```
> 
> I didn't check the command but I think it will work like that. Please note that you have to change the path and the parameters based on your configurations
> 
> Close the issue if I answer your question :)

I get this error

 Failed: error connecting to db server: no reachable servers

I had to install mongo-tools first with
 sudo apt-get install -y mongo-tools

**Comment by chrisleekr** [comment]
@peweb wait wait.

Don't try to use the script. 
In the frontend, simply go to settings and scroll down, and then you will see the backup button.

**Comment by peweb** [comment]
> @peweb wait wait.
> 
> Don't try to use the script. In the frontend, simply go to settings and scroll down, and then you will see the backup button. You do not need to install mongo-tools. It's already in the container.

Yes, the backup in the fromtend works fine but I want to backup via cron jobs every hour or so. It can help in a case of major issue when you need to reinstall the bot and lose config.

**Comment by habibalkhabbaz** [comment]
@peweb 
Sorry, you have to run the command from the Docker.
To do so, try the following:

```sh
docker exec container-name ./scripts/backup.sh binance-mongo 27017 binance-bot /tmp/backup-20220828.archive
```

Change `container-name` with your bot container name and note that the backup file will be located in the container.

@chrisleekr I think he is trying to do automated backups using a cron job

**Comment by chrisleekr** [comment]
Ah... that is what you try to do. Interesting approach.

Yes, @habibalkhabbaz's command is correct.

**Comment by peweb** [comment]
Thanks.
