### ISSUE TITLE
Raspberry Pi 3: binance-bot restarting

### ISSUE THREAD

**Issue by ComradeSerg** [chrisleekr/binance-trading-bot#534]
Hello,
I installed biance-trading-bot on Raspberry Pi 3 Model B Rev 1.2
OS:
cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

but binance-bot constantly trying to restart, I attaced container log (something about "unreachable code"). Other containers are ok.
Can anything be fixed here?

![image](https://user-images.githubusercontent.com/68647213/199326349-77caf4ce-735a-4b08-a49f-ddf80d9218b8.png)

[log.txt](https://github.com/chrisleekr/binance-trading-bot/files/9913592/log.txt)

**Comment by chrisleekr** [comment]
@ComradeSerg Yeah, I don't think you can run in RPi3. Too low spec.
Not a bug as I specifically said, it's tested from RPi4.
