### ISSUE TITLE
Configure all symbols except ...

### ISSUE THREAD

**Issue by dasbts** [chrisleekr/binance-trading-bot#536]
### Is your proposal related to a problem?
I would like to configure all coins except one.

Right now I have one holding from before, which I let the bot buy in more on. The issue is I would like to change my spending limits, and all the other holdings have more grids than the one I don't want to change. Is it possible to allow excluding changing the config in specific positions? The current situation would lead to another grid being added to this one symbol, and thus make it buy in pretty much instantly. Or well, I guess it will do it within one minute, but that's quite short time to go in the symbol and remove the new grid. 

### Describe the solution you'd like
Right now this exists for either global config or for all symbols that is currently used. I would like to extend this with a button to apply to all except, and then let the user choose which active symbols to not update.

**Comment by chrisleekr** [comment]
@dasbts 

I am not sure I understood what you want.

So you want to customise the single coin's configuration, is it correct?
Then it's already provided feature.

**Comment by dasbts** [comment]
Alright, I found out that somehow my BTC positions had a custom config even tho they were the same as the global config, so I just reset all those to global and have the only custom one left, and then adjusting the global one. I guess it's more not so intuitive, and this works as long as you don't have like 20 custom configs where you want to edit parts of the config for all except one.
