### ISSUE TITLE
Can't export pair trading logs

### ISSUE THREAD

**Issue by peweb** [chrisleekr/binance-trading-bot#537]
## Version
Last 0.93

## Description
Can not export trading logs.

## To Reproduce

1. Go to any trading pairs
2. Click on the log icon
3. Scroll down to Export Logs button
4. Nothing happens when you click Export Logs

![image](https://user-images.githubusercontent.com/36623351/199983693-a66d651b-1e17-410e-a920-91b336af11ad.png)

## Expected Behaviours

We should be able to save the log exported.

## Screenshots

![image](https://user-images.githubusercontent.com/36623351/199982833-89428bf1-5b16-4864-b585-6af0da45c5c4.png)

Looks like the log is too long and there is an error in the console.

**Comment by eppenga** [comment]
Can confirm this, my log export functionality also doesn't work.

**Comment by chrisleekr** [comment]
I am aware of the issue, I will fix it when I get time.
