### ISSUE TITLE
Bot stuck on loading

### ISSUE THREAD

**Issue by Adasqu** [chrisleekr/binance-trading-bot#538]
Hi,
After install I can't login to frontend and stuck on loading page.
In ws I have:
![obraz](https://user-images.githubusercontent.com/24990743/200385318-a20e3d55-7ce9-462b-9554-cc28981c557e.png)
On browser:
{"command":"latest","authToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoZW50aWNhdGVkQXQiOiIyMDIyLTExLTA3VDE3OjMxOjI4LjI1MVoiLCJpYXQiOjE2Njc4NDIyODgsImV4cCI6MTY2Nzg0OTQ4Ok0.OXr3Ke4OKk95zeUF3DDKcem2HaBH_ZFJiqS1D5QK6N4","data":{"page":1,"searchKeyword":"","sortBy":"default","sortByDesc":false}}
On docker:
{"name":"binance-api","version":"0.0.93","hostname":"dd1f1cef3a7c","pid":46,"gitHash":"26a1edc","server":"websocket","payload":{"command":"latest","authToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoZW50aWNhdGVkQXQiOiIyMDIyLTExLTA3VDE5OjAyOjE4LjUwMVoiLCJpYXQiOjE2Njc4NDc3MzgsImV4cCI6MTY2Nzg1NDkzOH0.vENNQ_OEw9Q1Uw0n6EaR2VNA4k_pSqB9vY4kv3OFunc","data":{"page":1,"searchKeyword":"","sortBy":"default","sortByDesc":false},"isAuthenticated":true},"level":50,"err":{"message":"Unexpected token u in JSON at position 0","name":"SyntaxError","stack":"SyntaxError: Unexpected token u in JSON at position 0\n    at JSON.parse (<anonymous>)\n    at Object.handleLatest [as latest] (/srv/dist/server.js:1:119233)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async WebSocket.<anonymous> (/srv/dist/server.js:1:114883)"},"msg":"Something wrong with trailing-trade-common cache","time":"2022-11-07T19:05:11.986Z","v":0}

**Comment by gufei** [comment]
same problem

**Comment by topdollar3** [comment]
Same here, using binance testnet key and test mode in the bot env. Stuck on loading after entering the password

**Comment by FernandoHiagon** [comment]
same here with latest release

**Comment by chrisleekr** [comment]
Hi guys, 

Sorry for the late reply. 

Please refer Troubleshooting wiki page and get the error log.

https://github.com/chrisleekr/binance-trading-bot/wiki/Troubleshooting

Without an error log, I won't be able to find out what is happening.

And please make sure your key and BINANCE_MODE are correct.

**Comment by ArcousSoftware** [comment]
The same problem continues

**Comment by smalik003** [comment]
{"name":"binance-api","version":"0.0.94","hostname":"38825bfcaef1","pid":46,"gitHash":"29944c1","server":"websocket","payload":{"command":"latest","authToken":"","data":{"page":1,"searchKeyword":"","sortBy":"buy-difference","sortByDesc":false},"isAuthenticated":true},"level":50,"err":{"message":"Unexpected token u in JSON at position 0","name":"SyntaxError","stack":"SyntaxError: Unexpected token u in JSON at position 0\n    at JSON.parse (<anonymous>)\n    at Object.handleLatest [as latest] (/srv/dist/server.js:1:119454)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async WebSocket.<anonymous> (/srv/dist/server.js:1:115058)"},"msg":"Something wrong with trailing-trade-common cache","time":"2022-11-30T09:23:35.176Z","v":0}

**Comment by smalik003** [comment]
{"name":"binance-api","version":"0.0.94","hostname":"fc64d7b7c46a","pid":46,"gitHash":"29944c1","server":"websocket","payload":{"command":"latest","authToken":"","data":{"page":1,"searchKeyword":"","sortBy":"buy-difference","sortByDesc":false},"isAuthenticated":true},"level":50,"err":{"message":"Unexpected token u in JSON at position 0","name":"SyntaxError","stack":"SyntaxError: Unexpected token u in JSON at position 0\n    at JSON.parse (<anonymous>)\n    at Object.handleLatest [as latest] (/srv/dist/server.js:1:119454)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async WebSocket.<anonymous> (/srv/dist/server.js:1:115058)"},"msg":"Something wrong with trailing-trade-common cache","time":"2022-11-30T10:19:32.158Z","v":0}

**Comment by chrisleekr** [comment]
Guys,

I've added the error message. 
In my experience, most of your issues are caused by using the wrong API key/secret.

This fix will show the possible scenario of errors.

![image](https://user-images.githubusercontent.com/5715919/204788123-a1fd07ec-3f11-404c-8851-6bf1e8659209.png)

**Comment by smalik003** [comment]
<img width="931" alt="Screenshot 2022-11-30 145407" src="https://user-images.githubusercontent.com/72207319/204789822-026f2d45-8762-4071-8e3c-7d26fab9196a.png">
Issue still persists

**Comment by RealAyyo** [comment]
@chrisleekr json for account-info not parsing
bad json in response
https://github.com/chrisleekr/binance-trading-bot/blob/49271ef5993a2c9c579d54bff1d9d81780b99a2f/app/frontend/websocket/handlers/latest.js#L117
