### ISSUE TITLE
Pause trading pair

### ISSUE THREAD

**Issue by peweb** [chrisleekr/binance-trading-bot#542]
### Is your proposal related to a problem?

Somethines I just want to pause trading of a pair. 

### Describe the solution you'd like

It would be helpful if we have pause button for each pair. 

![image](https://user-images.githubusercontent.com/36623351/204756619-3e84a9a0-2843-4ae8-bdb6-bc329b485fda.png)

### Describe alternatives you've considered

I can remove the symbol but it says:

![image](https://user-images.githubusercontent.com/36623351/204756695-4c69fc4c-3e3d-443f-a9aa-fa40c0a6e436.png)

I dont want to stop monitoring it. Just want to pause it for a while

When we set up several pairs like BTCUSDT ETHUSDT LTCUSDT and have USDT balance, the bot monitors all pairs and trades that meet the trade requirements. In a dynamic market, it might be useful to be able to pause a symbol.

**Comment by chrisleekr** [comment]
Oh, is it different from unchecking buy/sell in the symbol configuration?

**Comment by peweb** [comment]
Well, the bot is so advanced that I missed this setting! Thank you!
