### ISSUE TITLE
Bot Stuck on loading

### ISSUE THREAD

**Issue by smalik003** [chrisleekr/binance-trading-bot#545]
Refering to issue #538  

The issue still persists.
<img width="944" alt="Screenshot 2022-11-30 145852" src="https://user-images.githubusercontent.com/72207319/204790661-9afbd1a5-6927-44c9-a98b-3d6952f2a7b4.png">

**Comment by smalik003** [comment]
attaching logs
[bot logs.txt](https://github.com/chrisleekr/binance-trading-bot/files/10125771/bot.logs.txt)

**Comment by chrisleekr** [comment]
@smalik003 Your issue is caused by 
```
Error: Timestamp for this request is outside of the recvWindow.
```

You can refer https://github.com/chrisleekr/binance-trading-bot/wiki/Troubleshooting#how-to-fix-clock-desync
If you are using Linux, please use NTP to set the time correct.

**Comment by smalik003** [comment]
Working now, Thanks a lot :)
