### ISSUE TITLE
error connection to redis/mongo

### ISSUE THREAD

**Issue by RealAyyo** [chrisleekr/binance-trading-bot#547]
<img width="1526" alt="Снимок экрана 2022-12-01 в 11 17 09" src="https://user-images.githubusercontent.com/61937107/204957797-02f63c0d-f6c0-454f-b6cd-11b227f18788.png">

whats wrong?

**Comment by chrisleekr** [comment]
It's exactly what the error said. 

Please read the installation guide - https://github.com/chrisleekr/binance-trading-bot/wiki/Install

And could you please follow the question template.
If you have further issues, please open a new issue.
