### ISSUE TITLE
503 Service Temporarily Unavailable
nginx

### ISSUE THREAD

**Issue by kiongosss** [chrisleekr/binance-trading-bot#553]

**Comment by kiongosss** [comment]
![Screenshot_20221210-125846_Chrome.jpg](https://user-images.githubusercontent.com/80756727/206848933-ca9fc847-23f2-4e66-9b0e-84173af7dd03.jpg)

Frontend unaccessible

**Comment by chrisleekr** [comment]
Um... I am testing something and it caused that.
It's a demo website, so please don't expect it's always working.
