### ISSUE TITLE
Buy order is not cancelled when current price is higher than limit price

### ISSUE THREAD

**Issue by uhliksk** [chrisleekr/binance-trading-bot#566]
## Version

v0.0.96

## Description

Buy order is not executed when current price raise rapidly over the limit price. This will cause buy order is stuck and not even sell order is processed.

## To Reproduce

1. Set buy order with very tight stop and limit percentage to reproduce faster
2. Wait until market trigger the buy order
3. When price reached stop limit it is not executed as it also raised over limit price

## Expected Behaviours

It should cancel buy order when current price is higher than limit price,

## Screenshots

![image](https://user-images.githubusercontent.com/37454226/210218540-996ec986-61c6-4348-a1fd-85cf466bfdcc.png)

## Additional context

It should be implemented same way as "Difference to cancel" just from opposite side. If price is higher than limit price the buy order will not be executed anyway and thus it is safe to cancel this buy order.

**Comment by uhliksk** [comment]
The worst thing with this bug is the buy order will also block the bot to put sell order when price reached sell trigger price. This way you can skip sudden spike in market. Some altcoins can raise more rapidly than expected which will cause the issue to be triggered. Raising the `Limit price percentage` is not the solution as this will also lower `Difference to cancel` to useless levels.

**Comment by chrisleekr** [comment]
@uhliksk Thanks for finding/fixing all these bugs.
