### ISSUE TITLE
Reset to Global Settings not working???

### ISSUE THREAD

**Issue by chopeta** [chrisleekr/binance-trading-bot#57]
I think this could be a bug, but since am not 100% sure I am reporting it as a question.

It's possible that Reset do Global Settings (on a individual pair GUI settings page) is not working properly? Or maybe I don't know how to use it properly.

I am assuming that if you want a pair to be back to use global settings you must to the paid settings and click on the red button "Reset to Global Settings" and then click on the "Save" button. Is that assumption correct?

Assuming yes, what's happening is, after you reset a specific pair back to global settings, the pair goes back to "Customised" mode every time you made any change on the Global Settings.

Here's some screenshots:

![image](https://user-images.githubusercontent.com/7503721/112547110-51a88780-8d88-11eb-8896-e9f1a832c6d2.png)
Currently only 2 "customised" pairs in my setup.

![image](https://user-images.githubusercontent.com/7503721/112547486-d09dc000-8d88-11eb-9be2-aecfc495d8ff.png)
11 "customised" pairs a few mins after changing my "Buy: Trigger %" in the Global Settings.

You can see by the timestamp from the Buy Signal that the bot already "processed" both coins and SOLUSDT is now in "customised" mode when it should be in "Global Settings" like BELUSDT. 

I think this is happening to all pairs that I already adjusted individual settings before, so basically I can't or don't know how to actually reset a pair back to global settings.

Do you think you can try to reproduce this on your end?

Appreciate your help!

**Comment by chrisleekr** [comment]
I think this is somewhat related to issue #52 

If you change global settings and symbols had their own settings same as the global settings, then the bot will not update symbol settings to the global setting, but showing as customised.

When I get time, I will add an option to update all symbol configuration when you update the global configuration.

**Comment by chopeta** [comment]
I don't think it's related to #52 

Because I am using ""Reset to Global Settings" red button before I do this... so I am assuming the symbol is getting back to global with no "previous configuration"... again, maybe I am misunderstanding this functionality... for me it was like getting back to factory defaults which means, no previous configuration. But that's not happening here, looks like it is just copying global settings and saving them as individual setting in the symbol, hence why it goes to Customized after changing global settings later on.

I will try to check the code to see if I can understand it better and maybe propose some solution...

#52 seems to me like another feature, intended for when users want to clear all previous individual settings from all symbols at once. So, goes factory reset for all symbols and not just a single one like the "Reset to Global Settings".

**Comment by chrisleekr** [comment]
In the symbol configuration, the button "Reset to Global Settings" will be effective in the next tick. 
How many coins were you monitoring? If you had 10 coins, then you may see the UI changes 10 seconds later. But in the backend, the bot should already have reset to the global configuration.

Yeah, I may not understand what the exact problem is as well. Checkout the code and let me know if you find any bug.
Thanks.

**Comment by chopeta** [comment]
I knew you would say that, that's why I've made the screenshot so you could see the timestamps :-D

In the screenshot you can see BELUSDT buy signal timestamp is "16:38:20" while SOLUSDT was last updated on "16:39:26", so after BEL.

Both should be using Global but only SOLUSDT was set to "customised" which at that point in time was already updated just like BELUSDT (which is correctly using Global)

The real problem here is that I think I've eddited SOLUSDT params. a few days before... and never touched BELUSDT, but even after using "Reset to Global Settings" the bot still think that SOLUSDT symbol has "modified" and hence considering it "customised"...

So, I insist that "Reset do Global Settings" is not working as intended.

But will try checking the code...

**Comment by chopeta** [comment]
OK, please bear with me since I am JavaScript expert...

But I think the problem in is this line:

https://github.com/chrisleekr/binance-trading-bot/blob/1a308bbb00441e5ee0297e4cd80b437bc5b8920f/public/js/SymbolSettingIcon.js#L86

It seems to be just creating a copy of the global setting into a symbol setting instead of completely removing symbol setting to be like in a new and fresh installation where the symbol was never previously modified.

Not sure if my explanation makes sense for you.

**Comment by chrisleekr** [comment]
It does make sense and I was planning to update the code to remove the symbol configuration instead of copying the global configuration. 

When I get time, I will work on this configuration issue and release in next.

**Comment by chopeta** [comment]
Thanks Chris.
I wish I knew how to code to be able to assist you.
Really appreciate your time and effort here.

**Comment by chopeta** [comment]
I think I would not consider this a bug or even a question, if the button was labeled "Copy from Global Settings" instead of "Reset to Global Setting".

**Comment by chrisleekr** [comment]
You are right. What I will do is, I will make the button working as expected.

**Comment by chopeta** [comment]
Maybe both features could exists (copy and reset)... 
I don't know. That's up to you. 
For me only reset is really important, specially when you start using the bot and have no idea of what works and what no in terms of params.

**Comment by chrisleekr** [comment]
> For me only reset is really important, specially when you start using the bot and have no idea of what works and what no in terms of params.

I guess this is something that should be improved by showing a validation message or warning message in the frontend.
I thought I explain pretty in detail in the README.md. Looks like that is not enough.

**Comment by chopeta** [comment]
It is very well explained indeed... both in the README and in the GUI Setting screen.
But yes, is definitely not enough for end users... you know how this goes... They have a thing for causing problems and always blame the software for it hahahaha

**Comment by chrisleekr** [comment]
@chopeta I have released version 0.0.65, which has a fix with reset to the global configuration for the symbol configuration.

https://github.com/chrisleekr/binance-trading-bot/releases/tag/v0.0.65

If you find any issue, please let me know. 
If you think it's fixed, please close the isuse.

**Comment by chopeta** [comment]
Testing now...

**Comment by chopeta** [comment]
It seems to be working perfectly. Thanks for the fixes!!!!

**Comment by Mahniex** [comment]
@chrisleekr can we reopen this issue please?

I'm having the same problem, even on the latest version. Essentially when I reset a configuration to global settings, it still stays marked as "customized" and the configuration is not reset (it stays the same). I am resetting using the red button here:
![image](https://user-images.githubusercontent.com/47572920/113351474-38c94480-933b-11eb-87fd-cc105e9cd33a.png)


After a bit of digging, I found that when the FE sends the reset request, the BE responds with;

```
{"result":false,"type":"error","message":"Command is not recognised."}
```

even though the original request has a payload command.

![image](https://user-images.githubusercontent.com/47572920/113350449-c3a93f80-9339-11eb-9539-b485b566a854.png)

Here's the full payload that's being sent (I was trying to reset BTCEUR):
```
{ "command": "symbol-setting-delete", "data": { "globalConfiguration": { "_id": "REDACTED", "key": "configuration", "enabled": true, "cronTime": "* * * * * *", "symbols": [ "ETHEUR", "ADAEUR", "XLMEUR", "BNBEUR", "XRPEUR", "DOTEUR", "BCHEUR", "LTCEUR", "LINKEUR", "UNIEUR", "EOSEUR", "DOGEEUR", "BTCEUR" ], "supportFIATs": [ "EUR" ], "candles": { "interval": "1h", "limit": 84 }, "buy": { "enabled": true, "maxPurchaseAmount": 600, "triggerPercentage": 1.01, "stopPercentage": 1.012, "limitPercentage": 1.0121 }, "sell": { "enabled": true, "triggerPercentage": 1.075, "stopPercentage": 0.99, "limitPercentage": 0.989 } }, "symbol": "BTCEUR", "symbolConfiguration": { "_id": "REDACTED", "key": "BTCEUR-configuration", "candles": { "interval": "1h", "limit": 84 }, "buy": { "enabled": true, "maxPurchaseAmount": 600, "triggerPercentage": 1, "stopPercentage": 1.012, "limitPercentage": 1.0121 }, "sell": { "enabled": true, "triggerPercentage": 1.075, "stopPercentage": 0.99, "limitPercentage": 0.989 }, "enabled": true, "cronTime": "* * * * * *", "symbols": [ "ETHEUR", "ADAEUR", "XLMEUR", "BNBEUR", "XRPEUR", "DOTEUR", "BCHEUR", "LTCEUR", "LINKEUR", "UNIEUR", "EOSEUR", "DOGEEUR", "BTCEUR" ], "supportFIATs": [ "EUR" ] }, "accountInfo": { "makerCommission": 10, "takerCommission": 10, "buyerCommission": 0, "sellerCommission": 0, "canTrade": true, "canWithdraw": true, "canDeposit": true, "updateTime": 1617307167218, "accountType": "SPOT", "balances": [ { "asset": "BNB", "free": "0.00834594", "locked": "0.00000000" }, { "asset": "DOGE", "free": "13.00000000", "locked": "0.00000000" }, { "asset": "EUR", "free": "REDACTED", "locked": "REDACTED" }, { "asset": "LDBTC", "free": "0.01655636", "locked": "0.00000000" }, { "asset": "LDETH", "free": "0.09303796", "locked": "0.00000000" }, { "asset": "LDXRP", "free": "REDACTED", "locked": "0.00000000" }, { "asset": "LDXLM", "free": "39.00000000", "locked": "0.00000000" }, { "asset": "LDADA", "free": "REDACTED", "locked": "0.00000000" }, { "asset": "DOT", "free": "0.01200000", "locked": "0.00000000" }, { "asset": "DODO", "free": "0.00075022", "locked": "0.00000000" }, { "asset": "ALICE", "free": "0.42660155", "locked": "0.00000000" } ], "permissions": [ "SPOT" ] }, "refreshAccountInfo": false, "indicators": { "lowestPrice": 48332.85, "lastCandle": { "openTime": 1617307200000, "open": "50070.24000000", "high": "50115.42000000", "low": "50029.98000000", "close": "50100.00000000", "volume": "14.60996000", "closeTime": 1617310799999, "quoteVolume": "731519.60714565", "trades": 1555, "baseAssetVolume": "8.99293200", "quoteAssetVolume": "450346.04185438" } }, "symbolInfo": { "symbol": "BTCEUR", "status": "TRADING", "baseAsset": "BTC", "baseAssetPrecision": 8, "quoteAsset": "EUR", "quotePrecision": 8, "filterLotSize": { "filterType": "LOT_SIZE", "minQty": "0.00000100", "maxQty": "9000.00000000", "stepSize": "0.00000100" }, "filterPrice": { "filterType": "PRICE_FILTER", "minPrice": "0.01000000", "maxPrice": "1000000.00000000", "tickSize": "0.01000000" }, "filterMinNotional": { "filterType": "MIN_NOTIONAL", "minNotional": "10.00000000", "applyToMarket": true, "avgPriceMins": 5 } }, "openOrders": [], "action": "not-determined", "baseAssetBalance": { "asset": "BTC", "free": 0, "locked": 0, "total": 0, "estimatedValue": 0, "updatedAt": "2021-04-01T19:59:27.218Z" }, "quoteAssetBalance": { "asset": "EUR", "free": "REDACTED", "locked": "REDACTED" }, "buy": { "currentPrice": 50100, "limitPrice": 50706.21, "lowestPrice": 48332.85, "triggerPrice": 48332.85, "difference": 3.6562089758828575, "openOrders": [], "processMesage": "", "updatedAt": "2021-04-01T20:15:50.759Z" }, "sell": { "currentPrice": 50100, "limitPrice": 49548.9, "lastBuyPrice": null, "triggerPrice": null, "difference": null, "currentProfit": null, "currentProfitPercentage": null, "openOrders": [], "processMessage": "", "updatedAt": "2021-04-01T20:15:50.759Z" } } }
```

If I update the configuration manually, it still gets applied correctly. Anything I should check for you?

**Comment by chopeta** [comment]
Just FYI 
I don't have such problem.
I've tested this many times with different symbols. 
It's working fine for me here.
