### ISSUE TITLE
Partial fill is not processed correctly when multiple sell orders are made

### ISSUE THREAD

**Issue by uhliksk** [chrisleekr/binance-trading-bot#574]
## Version

v0.0.96

## Description

Bot is counting just last sell when volatile market cause partially filled sell is cancelled and new sell is created.

## To Reproduce

1. Make higher value order to not be processed at once.
2. Make market close order with multiple partial sells.
3. There is a chance sell will be cancelled after partially sold and new sell order will be created to be filled.

## Expected Behaviours

All sells on order created by bot have to be counted.

## Screenshots

Trade history on Binance:
![image](https://user-images.githubusercontent.com/37454226/210628312-398680bd-f5ed-49a9-90da-006befffac37.png)

Trade history recorder by bot:
![image](https://user-images.githubusercontent.com/37454226/210622209-deacbecb-b72d-49d8-861d-48177018e103.png)

## Additional context

There were two sell orders created. One 459,6317236 BUSD at 19:07:14 as partially filled as `maker` and then cancelled and one 544.8021018 BUSD at 19:07:20 filled as `taker`. Both made by bot automatically.

**Comment by chrisleekr** [comment]
Hmm, I am not sure I can understand what exactly happened here.

So the 1st sell order is partially filled, but the bot archived the trade? Is that why showing -45.73%?

If the 2nd sell order is placed by the bot, then the bot still thinks the trade is opened. So I expect not to archive the trade.

Any log?

**Comment by uhliksk** [comment]
I don't have a log as I noticed it too late but what I think happend is because 1st sell order has been cancelled bot started counting sum of sale again when 2nd sell order has been created because there were just 544.80210 BUSD left when it created 2nd sell order. If you sum sales made at 19:07:21 that's exactly 544.8021018 BUSD.

I've seen few times same thing in buy orders when too big profit was calculated because only second buy order part was counted to buy side but this was not locking issue as bot just then sold available amount of asset so I didn't paid attention to this.
