### ISSUE TITLE
Failed to load your account information

### ISSUE THREAD

**Issue by gdlt88** [chrisleekr/binance-trading-bot#586]
## Version
DockerHub Image latest(I downloaded it today 2023-01-12)

## Description
 I'm getting the error `Failed to load your account information.` when trying to run the dev env. I've recreated the keys several times and I still get the error

## To Reproduce
- Generate a new pair of api_key and secret_key on the testnet account
- put it on the .env file
- launch container with the following command `docker-compose -f docker-compose.server.yml up -d`

## Expected Behaviours
Can login and see the different pages and dashboard of the app

## Screenshots

![image](https://user-images.githubusercontent.com/7811830/212150075-57746a06-732f-4d42-b8ee-02b76e15526b.png)

**Comment by chrisleekr** [comment]
@gdlt88 

The file `docker-compose.server.yaml` is for production API key/secret.
You can change the BINANCE_MODE to test in the `docker-compose.server.yaml`.
Or simply use `docker-compose.yml` 

Please close the issue if your issue is resolved. Thank you.
