### ISSUE TITLE
Display release version on the web GUI

### ISSUE THREAD

**Issue by chopeta** [chrisleekr/binance-trading-bot#59]
### Is your proposal related to a problem?

There's no way to know on the GUI, which version of the bot you currently running.

### Describe the solution you'd like

Display the release version number somewhere in the GUI screen.

**Comment by chrisleekr** [comment]
Sounds good. I will add it.

**Comment by chopeta** [comment]
I saw this on #77 
My only note would be use the link for the releases pages instead of github project home (this link is already present in the page header)
Other that we can close this once PR gets released.
