### ISSUE TITLE
Are commissions supported

### ISSUE THREAD

**Issue by rando128** [chrisleekr/binance-trading-bot#598]
I'm wondering if the profit calculations displayed in the dashboard take into account Binance fees.

Looking at the grid trade logs, I see mentions to the commissions (this is on Testnet):
```
fills: [
                {
                    price: '0.39590000',
                    qty: '50.20000000',
                    commission: '0.00000000',
                    commissionAsset: 'USDT',
                    tradeId: 28324
                }
            ],
```

Nevertheless, I can't find any reference to it in the code base.

Can anyone shade some light?

**Comment by chrisleekr** [comment]
@rando128 The profit is determined here https://github.com/chrisleekr/binance-trading-bot/blob/master/app/cronjob/trailingTradeHelper/configuration.js#L337

Binance returns the quote quantity. The bot will sum up quote quantity from buy/sell orders and simply minus.
In my understanding, the quote quantity will already take an account the commission. 

Correct me if I am wrong.
