### ISSUE TITLE
Can't stop a symbol from showing up on the GUI

### ISSUE THREAD

**Issue by chopeta** [chrisleekr/binance-trading-bot#60]
### Is your proposal related to a problem?

Once I remove a symbol from the Global Setting page the symbol still shows up on the GUI but with a "remove" button for you to remove it manually if you want it.

Unfortunately that button doesn't show up for symbol where you have some balance left, is this on purpose?

Can't we enable the remove button for these symbols as sell? For me they just take space from screen since they are not even getting updated (which is correct since is not in the monitoring list any longer)

Here's a screenshot where you can notice that I can't remove the symbol BTCUSDT.

![image](https://user-images.githubusercontent.com/7503721/112712278-7726b580-8e9c-11eb-88a4-3707ef91bf5e.png)

### Describe the solution you'd like

Enable the remove button in a symbol on the main screen, for any symbol that is already removed from "Symbols" list in the Global Settings page.

**Comment by chrisleekr** [comment]
Oh, that is intended. As you have the last buy price recorded for the BTCUSDT, the bot does not allow to remove in case you lose the record.

Simply update your last buy price to 0, then remove button will be displayed.

**Comment by chopeta** [comment]
You're absolutely right. Thanks!
