### ISSUE TITLE
Break-even still buggy + GUI Feature request

### ISSUE THREAD

**Issue by dasbts** [chrisleekr/binance-trading-bot#600]
## Version
Running Version: v0.0.96 (209d2e0)
Latest Version:
[v0.0.96](https://github.com/chrisleekr/binance-trading-bot/releases)

## Description
It seems like the break-even calculator is still a bit buggy. Almost as if it is suggesting that the value where it becomes pointless to reinvest (a feature which I suggest allowing turning off, as it makes no sense to show that text even if the proposed value is ridiculously high) is seen as the break-even level as it becomes closer to zero as the suggested value to add to the position the closer this "pointless" marker is. 

I have made a calculation spreadsheet which you can see in the link in additional context below, it is downloadable if you want to play around with it and then you can change the green-marked cells which are the inputs. There are also some extra info and percentages that might be of help for other GUI things (such as a feature request to show initial value). **Note that there are two ways to calculate this, one with the initial investment in mind at row 5, and another on row 9 which cares for the rebound increase on both initial investment and break-even investment. I kept the first one to illustrate what happens if you forget to care for initial investment increase. EDIT: There's also a third one now that shows if you want a desired chosen profit for example your set global config profit based on the initial investment.** 

## To Reproduce
Get a trade which is in such a loss that it's not worth reinvesting such as -60% on the trade position (and like 140% decrease in price), click the break-even calculator icon. Change the "Buy trigger percentage based on last buy price" until it doesn't say that it's pointless any longer and then change the value up and down and it should behave as in my description above. 

If you want to simulate the trade I am looking at by adding a non-real DB entry and test it, then add a current price of 21 and last buy price of 57, that should be enough information for you to simulate this as any quantity will allow you to calculate the rest, but otherwise, try the example values in my spreadsheet. 

## Expected Behaviours
Showing an actual break-even value required to spend, not just saying that it requires something like $2 to break-even a $1,181 position on an expected 5% rebound which is obviously incorrect since in my spreadsheet it is actually $14,418. 

## Screenshots
![image](https://user-images.githubusercontent.com/40334665/218254073-e6337783-f952-416d-8aef-e2c9ddb1c68c.png)
![image](https://user-images.githubusercontent.com/40334665/218254183-fdf01511-54bb-4aba-89ad-3f74b2d34e0f.png)

## Additional context
https://docs.google.com/spreadsheets/d/1x-tWUL03Z1TAwTmP65OobGjRRKCmnBPClYEJi-FKrQs/edit?usp=sharing

This spreadsheet is downloadable if you want to play around with it, and then you can change the green-marked cells which are the inputs. 
The "Planned buy-in value (i.e. next grid)" I added just for the context of the results if we buy in on another grid instead of the recommended break-even.

You might have thought differently than me as well. So for explanation, this approach means that if we think the price rebounds i.e. 5% up from the **current price**, then we make back our money that was lost in the decline (which hopefully is still unrealized PnL and an open position) if we bought in as seen in the spreadsheet example $14,418 extra at the current price and it in fact rebounds 5% up from there. It's a bit of a ridiculous example since the initial investment would have been $1,181, but it works.

**Comment by rando128** [comment]
@dasbts, thanks for the thorough analysis. At first, it is true the implemented approach considers the price rebounds from the `next buy trigger` and not the current price, but I'll look into your spreadsheet calculations.

@chrisleekr, you might want to put on hold PR #601, as this thread might trigger further improvements.

**Comment by dasbts** [comment]
The first table marked in yellow/orange in the table can be ignored I think. The second would allow a complete break even, and the third one would give a profit depending on the percentage you desire as chosen in the green cells. 

However, I still get a bit (ca $1) higher value in the third one when comparing the difference in column M, but I sadly have higher prior things this weekend and spent way too much time on this already haha. 

@rando128 alright, maybe it would be interesting to have both approaches in mind. I think there might be some interest in both break even from the current price, and from the next grid.

**Comment by rando128** [comment]
Thx @dasbts. Can you please post a new screenshot of the calculator and provide the following information:
- currentPrice (at the time of the screenshot)
- lastBuyPrice
- sell triggerPercentage
- total quantity of coin bought (in volume)
- total amount of coin bought (in USDT)
- number of executed buy orders (i.e. current depth of the grid)

This will help me to better troubleshoot.

**Comment by dasbts** [comment]
I'm not completely sure about column L either. Like that column I guess works, but I don't know if it's the appropriate approach. 

@rando128 The values in the green cells at the spreadsheet are the values that represent (with some slight rounding) the images in the first post I made, but I can make some new notes in a bit if you want a fresh one and even more exact. 

Current price: 21.31
Last buy price: 56.56
Sell trigger percentage: 1.05
Limit price percentage: 0.98
Stop price percentage: 0.985
Total quantity: 20.89
Total amount bought I don't know completely but I think it is the calculated "Total value" in the spreadsheet, $1181.
Number of executed buy orders: 4 and also previous manual trades where I added the last buy price manually to the GUI. 

From GUI: Suggested breakeven amount 1968.66 USDT, however, it is different when I click into the GUI calculator as you could see on the screenshots previously sent.

**Comment by rando128** [comment]
>previous manual trades where I added the last buy price manually to the GUI.

This is the reason why the calculator gives you weird results. Currently the calculator doesn't support grids containing manual trades. This is because the bot doesn't know the original bought amount. 

Also there was some inconsistency in the calculation between the grid GUI and the calculator GUI. This has been addressed in PR #601. 

For the time being, I'll add a warning message when using the calculator with manual grids. I'll think of a way to improve it and support this scenario.

I'll keep looking at your spreadsheet to see if we can come up with better breakeven strategies.

**Comment by dasbts** [comment]
Awesome, but shouldn't it just be possible to look at the last buy price? If you want it to use break-even from the next grid you have to cache something like "upcoming_last_buy_price". The original bought amount I agree with you, but at the same time, if we're always selling 100% (since that's how the bot is made which I don't really agree with but I see why it's the case), then why wouldn't we assume that this is the quantity for the recorded last buy price? If there's no last buy price available at all then I don't know if it's even possible to show the break-even calculator. 

Regarding the spreadsheet: 
I figured it out with the column that I was not sure about, now it adds up. 

As can be seen in the first yellow/orange table, the "Required increase to reach break-even" is 4.86% if you don't care about the increased rebound of what you had already invested from before leading to incorrect result as it will go to the break-even but then about 0.14% extra (if my logic is correct, but this scenario is likely useless anyway so I don't know why I kept it). 

The second table remains the same for total break-even. 

The third table now shows that if you want let's say 2.5% profit on the initial trade (if that's i.e. your global config profit %), then you will break-even at a even lower value 4.81%, but those few remaining percentages 0.19% extra will be sufficient to give that same 2.5% profit you would have wanted from the beginning. 

Column L-M can be compared with column C to see that we actually made back the difference after reaching the break-even. Column C is the loss we have so far, column L and M are what we get for reaching the rebound from the price we buy in at. 

For the percentages only I put one in negative as it is before the break-even investment was made, and the other in plus, which makes it a bit clearer to compare with the initial loss which we see in percentages at F3 or D3. However, I saw in the code is a bit of a struggle anyway, like in accounting the difference would likely be negative as we are at loss, but it's easier to calculate if we see it as positive as this is what we want to earn back with the break-even investment. This way we can also see that the difference between L15 and M15 is indeed 2.5% which I set as the desired profit.

**Comment by rando128** [comment]
@dasbts, I've improved the calculator to support manual trades scenarios in PR #601. It allows to use the lastBuyPrice (indirectly as you still need to provide the original purchased amount and quantities).

For your information, the calculator currently uses the following formula:
``` 
    const breakevenAmount =
      (totalBoughtAmount -
        totalBoughtQty * buyTrigger * lastBuyPrice * sellTrigger) /
      (sellTrigger - 1);
```
I'll keep trying to understand your spreadsheet when I get a chance 😉. I suggest we close the issue in the meantime.

<img width="490" alt="Screenshot 2023-02-12 at 15 22 36" src="https://user-images.githubusercontent.com/1491835/218318632-7e779c5f-3d4a-4594-bdc3-e4556b1d9d37.png">
