### ISSUE TITLE
Symbol not trading,    Execution failed -> "Stop price would trigger immediately."

### ISSUE THREAD

**Issue by CurseStaff** [chrisleekr/binance-trading-bot#604]
Hello @chrisleekr ,

thank you for this awesome software,

## Version
FROM RELEASE
v0.0.96   commit 209d2e081ec63259c0c0b6fc1eb3606d13bd8786
 AND 
FROM BRANCH MASTER (actual used for screenshot)
Running Version:
v0.0.96
(209d2e0)
Latest Version:
[v0.0.96](https://github.com/chrisleekr/binance-trading-bot/releases)

## Description

for a few days, my bot no longer executes a transaction, I tried to switch from the latest release to the MASTER, but the result is the same, in the logs, we can say "Execution failed" (see screenshots)

a reboot of the bot does not change the problem, the bot works on 3 symbols, and the problem is generalized on all.

## Expected Behaviours

a reboot of the bot does not change the problem, the bot works on 3 symbols, and the problem is generalized on all.

## Screenshots

![image](https://user-images.githubusercontent.com/11999989/219432648-a4ccd3a0-4659-4cfd-91d0-fa46470ed5b0.png)

![image](https://user-images.githubusercontent.com/11999989/219435568-dacaaa60-1770-4a8b-a730-ac93ae871f29.png)

its show opentrades: 
![image](https://user-images.githubusercontent.com/11999989/219433697-1151cc0d-0a61-43bd-8b0c-7d96af64059c.png)

but nothing from 11-02-2023
![image](https://user-images.githubusercontent.com/11999989/219433817-f587db0d-bac8-475b-949d-e6860b863ec1.png)

Configuration
![image](https://user-images.githubusercontent.com/11999989/219434033-522ec45f-d6f3-4b2c-a299-3db4f0dad7f2.png)

![image](https://user-images.githubusercontent.com/11999989/219434135-2c54aca3-bc51-4f68-8da5-103704467675.png)

I don't know if you need any other information, tell me what I can give you and how, 

thank you for your help!

**Comment by rando128** [comment]
@CurseStaff, I'm seeing this too. What values did you set on your grid buy "stop Price Percentage" and "limit Price Percentage"?

**Comment by leductai** [comment]
I think you should place purchase min and max is 11 USDT

**Comment by chrisleekr** [comment]
@CurseStaff 
The error message is valid. Try to adjust your settings.
