### ISSUE TITLE
Available coins

### ISSUE THREAD

**Issue by garyfisher** [chrisleekr/binance-trading-bot#613]
I'm a beginner in topic, what does it depend on which coins are available in the bot? For example, there is no option for me to set DOT/USDT.

Version: v0.0.96 (209d2e0)

Binance: test api

**Comment by rando128** [comment]
@garyfisher, I guess you're running in test mode. DOT/USDT is not available on the testnet. You will see it when running in live mode.

**Comment by garyfisher** [comment]
> @garyfisher, I guess you're running in test mode. DOT/USDT is not available on the testnet. You will see it when running in live mode.

Oki, all clear. Thank you for information.
