### ISSUE TITLE
Timestamp for this request was 1000ms ahead of the server's time.

### ISSUE THREAD

**Issue by Parad0X-py** [chrisleekr/binance-trading-bot#614]
Binance logo Binance Trading Bot
Failed to load your account information.

You are seeing this error message because of one of the following situations:

    You are using TestNet API/Secret for Live Binance.
    You are using Live API/Secret for TestNet Binance.
    Your API key is revoked/deleted.
    Your API key is not permitted to "Enable Reading" and "Enable Spot & Margin Trading".
    Your API key is restricted to trusted IP, and your bot is located not in trusted IP.

Please read the following document carefully, update your configuration. And then try to launch the bot again.
https://github.com/chrisleekr/binance-trading-bot/wiki/Install#how-to-install

If the issue persists after confirming the API key/secret, please open a new issue in Github.

**Comment by chrisleekr** [comment]
@Parad0X-py 

This is not a bug.
It means your server is not synced.
Try to sync your server time and try again.
