### ISSUE TITLE
Data empty after few seconds

### ISSUE THREAD

**Issue by florent6001** [chrisleekr/binance-trading-bot#63]
Hi,

I got a problem on Windows with WSL. I got docker, the application was running fine but only few minutes. I tryied reinstall all (docker, binance-trading-bot). And now the application is completely empty. I just get the header.

When i check the WebSocker tab in chrome i got this : 
{command: "latest", data: {}}
command: "latest"
data: {}

I found a really similar issue here : 

https://github.com/chrisleekr/binance-trading-bot/issues/31

But the issue is closed and he don't have solution. 

Do you have an idea please ?

**Comment by chopeta** [comment]
I think Windows is a no go so far... 
A friend had similar issues just like you. 
Try with Ubuntu Server or Debian, even if it's in a VM inside your Win10 machine. Docker setup and pretty simple and straight forward.
I am using it on docker inside a Ubuntu Server KVM and it's working great.

**Comment by chrisleekr** [comment]
Hi @florent6001

Have you checked the log for websocket?

Try to install `bunyan` and run following command to see the log:

```
docker logs binance-bot  -f --tail=100 | bunyan -c 'this.server == "websocket"'
```

**Comment by chrisleekr** [comment]
Hey @florent6001 if your issue has been resolved, please close the issue.
