### ISSUE TITLE
Stuck on Failed to load account information, how it`s fix

### ISSUE THREAD

**Issue by Superzirochka** [chrisleekr/binance-trading-bot#636]
## Version
latest

## Description

Stuck on Failed to load account information, I checked and confirmed the API key/secret for binance testnet, but still get "Failed to load account information"
at accountInfo i see only this
{balances: Array(0)}
please, help to fix this

**Comment by rando128** [comment]
@Superzirochka did you check issue #586?

**Comment by Superzirochka** [comment]
Thanks, it worked
