### ISSUE TITLE
I can't run it on Mac without Docker

### ISSUE THREAD

**Issue by eyass445** [chrisleekr/binance-trading-bot#64]
I can't run it on Mac without Docker

<img width="1440" alt="Screen Shot 2021-03-29 at 12 59 30 AM" src="https://user-images.githubusercontent.com/43729214/112769523-41173c00-902a-11eb-9e41-ab858beadeea.png">

<img width="1440" alt="Screen Shot 2021-03-29 at 12 59 18 AM" src="https://user-images.githubusercontent.com/43729214/112769538-51c7b200-902a-11eb-9f70-398b2dd887f6.png">

**Comment by chrisleekr** [comment]
Hi @eyass445 if you are just running the bot in the command line, it won't work unless you launch redis and mongo and set hosts file to point them. It will be complex to do.

If you want to launch development mode, then simply run:

```
$ docker-compose up -d --build
```

If you want to launch production mode, then run:

```
$ docker-compose -f docker-compose.server.yml pull
$ docker-compose -f docker-compose.server.yml up -d
```

Please read README.md - https://github.com/chrisleekr/binance-trading-bot#how-to-use

Close the issue if it is resolved.

**Comment by eyass445** [comment]
do you mean ioredis ?


<img width="441" alt="Screen Shot 2021-03-29 at 1 49 26 PM" src="https://user-images.githubusercontent.com/43729214/112826448-a8b6a100-9095-11eb-8e5b-27e9dc4534eb.png">

**Comment by eyass445** [comment]
I uploaded the bot to heroku servers ... But it didn't work

**Comment by chrisleekr** [comment]
@eyass445 the bot is not designed to run without docker or heroku.

**Comment by chrisleekr** [comment]
Hey @eyass445 if you don't have more query, please close the issue.
