### ISSUE TITLE
ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/usr/local/lib/python3.9/site-packages/werkzeug/urls.py)

### ISSUE THREAD

**Issue by nsrajeshprabhu** [chrisleekr/binance-trading-bot#648]
## Version
Latest Code

## Description
ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/usr/local/lib/python3.9/site-packages/werkzeug/urls.py)

## To Reproduce

When we run the "docker-compose up -d --build" command we are getting this error in the container

## Additional context

In the tradingview/requirements.txt document add the below line and it will solve the problem

Werkzeug==2.3.6

**Comment by chrisleekr** [comment]
Hi @nsrajeshprabhu 

The fix has been merged into the master branch.

I close the issue.
