### ISSUE TITLE
Stop Loss

### ISSUE THREAD

**Issue by bummar** [chrisleekr/binance-trading-bot#66]
I do a little naive query, positions does not have a defined stop loss, only one is executed when it reaches profit?

**Comment by chrisleekr** [comment]
I am not sure I understand your question. Can you give me more explanation?

**Comment by bummar** [comment]
I already understood that it does not use a stop loss, would it not be nice to incorporate it?

**Comment by bummar** [comment]
Sorry for the English, but yes, what I mean is if the incorporation of a stop is in the plans, example: you buy a currency in $ 100, this currency breaks the support and falls to $ 80, you could add an option to put a sell order if the percentage is very negative.

**Comment by chrisleekr** [comment]
Oh @chopeta made me realise what you are asking. 

Now I understand what you are trying to say. 

As mentioned in #72, I won't add that feature.

**Comment by chrisleekr** [comment]
I assuem your question is answered, I close the issue. Please open a new issue if you have a new question.
