### ISSUE TITLE
Installation steps (Windows)

### ISSUE THREAD

**Issue by ggloveswp** [chrisleekr/binance-trading-bot#68]
Hello.

Congrats for the long-awaited bot.
Can you please provide more detailed installation instructions for your project, under Docker running through Windows OS ?

Im not really familiar with it - and would like to have some advise.

Steps I took so far:

-Installed Docker through Windows Store
-Created a portrainer server/agent using instructions from here: https://documentation.portainer.io/v2.0/deploy/ceinstalldocker/

But im really unsure about the next step.
-Where should I clone the github repo? 
-How do I fire up the app?

Thanks in advance,

**Comment by chrisleekr** [comment]
Hi @ggloveswp 

Unfortunately, I do not possess Windows machine. Hence I cannot provide detailed instructions.
And I have seen some people saying it does not work very well with Windows.

All I can say is, if you have a Docker and install [docker-compose](https://docs.docker.com/compose/install/), then you should be able to clone the repo and follow how to use - https://github.com/chrisleekr/binance-trading-bot#how-to-use

For cloning the repo, please google it.

**Comment by ggloveswp** [comment]
Thanks for the prompt answer.

Well, Im confortable using Docker in Linux, but not at Windows-based machines.

I guess i'll just avoid it.

**Comment by chrisleekr** [comment]
Ok, @ggloveswp 

I hope you succeed with the installation.

Please close the issue if you resolve the issue.

**Comment by ggloveswp** [comment]
Sure thing, thanks for your support @chrisleekr
