### ISSUE TITLE
Last Buy price doesn't match with graphic arts of binance

### ISSUE THREAD

**Issue by BramFr** [chrisleekr/binance-trading-bot#69]
## Description

The Last Buy price doesn't match with the graphic arts value of binance. Its seems a bug ?

## Screenshots
Here can you see that the boy have bought this coin with the price of 1.216
![2021-03-31_13-15](https://user-images.githubusercontent.com/16082279/113136805-14c70f80-9224-11eb-9fed-87e8ad95b2e2.png)

Within the Binance app i`ll can see the buy moment in time. Thats today at 8:42
![Screenshot_20210331-131724](https://user-images.githubusercontent.com/16082279/113137285-a6368180-9224-11eb-988c-48802fbc027e.png)

But when i`ll look at this screenshot. The current time 8:42 doesnt match the buy value of 1.216?
![2021-03-31_13-19](https://user-images.githubusercontent.com/16082279/113136812-1690d300-9224-11eb-81ee-b13e8af377fa.png)

This seems a bug

**Comment by chrisleekr** [comment]
Something must be wrong.

Let me share my latest trading.

XRPDOWNUSDT buy order was placed at 30/Mar 15:17:13 and executed at 30/Mar 15:17:56
![image](https://user-images.githubusercontent.com/5715919/113146500-7a92b600-927b-11eb-8159-3a651ec60987.png)

And my candle configuration was 2h/80
![image](https://user-images.githubusercontent.com/5715919/113146660-a9109100-927b-11eb-8783-69a85c21efa1.png)

And the chart is showing the correct timestamp with the order
![image](https://user-images.githubusercontent.com/5715919/113146931-fab91b80-927b-11eb-8e09-7911bc7e0a89.png)

**Comment by BramFr** [comment]
> Something must be wrong (not with the bot)
> 
> What was your setting for candles?
1h with 100 candles.
But that doesn't match with the buy moment. The current value at that time seems around +/-1.165 not 1.216

**Comment by chrisleekr** [comment]
@BramFr 
If you click the arrow, then you can see trade details.

What time is that transaction filled?

![image](https://user-images.githubusercontent.com/5715919/113275871-f7c93400-932a-11eb-8d17-f630d565094c.png)

**Comment by BramFr** [comment]
![image](https://user-images.githubusercontent.com/16082279/113391190-6f32ae00-9393-11eb-9b5f-1278aef508fb.png)
Indeed looks like a valid buy...
Didn't know the arrow (trade details) function :)
