### ISSUE TITLE
Password protected interface

### ISSUE THREAD

**Issue by ggloveswp** [chrisleekr/binance-trading-bot#70]
Is there a way to protect the interface from unauthorized use, like setting a password in settings or the complete view?

**Comment by chrisleekr** [comment]
There is a pull request - https://github.com/chrisleekr/binance-trading-bot/pull/50
Just waiting feedback from @zanaca

**Comment by ggloveswp** [comment]
Thanks for it.

**Comment by ggloveswp** [comment]
Duplicate: #50
