### ISSUE TITLE
i cant run the bot

### ISSUE THREAD

**Issue by allaf2** [chrisleekr/binance-trading-bot#71]
> binance-trading-bot@0.0.64 start /srv
> node dist/server.js

{"name":"binance-api","version":"0.0.64","hostname":"34db31900293","pid":19,"level":30,"NODE_ENV":"production","msg":"API logger loaded","time":"2021-03-31T08:41:58.466Z","v":0}
{"name":"binance-api","version":"0.0.64","hostname":"34db31900293","pid":19,"helper":"mongo","level":30,"uri":"mongodb://binance-mongo:27017/?poolSize=20&retryWrites=true&writeConcern=majority","msg":"Connecting mongodb","time":"2021-03-31T08:42:02.352Z","v":0}
[ioredis] Unhandled error event: Error: getaddrinfo EAI_AGAIN binance-redis
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
[ioredis] Unhandled error event: Error: getaddrinfo EAI_AGAIN binance-redis
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
[ioredis] Unhandled error event: Error: getaddrinfo EAI_AGAIN binance-redis
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
[ioredis] Unhandled error event: Error: getaddrinfo EAI_AGAIN binance-redis
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
[ioredis] Unhandled error event: Error: getaddrinfo EAI_AGAIN binance-redis
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
{"name":"binance-api","version":"0.0.64","hostname":"34db31900293","pid":19,"helper":"mongo","level":50,"e":{"name":"MongoServerSelectionError","reason":{"type":"Unknown","setName":null,"maxSetVersion":null,"maxElectionId":null,"servers":{},"stale":false,"compatible":true,"compatibilityError":null,"logicalSessionTimeoutMinutes":null,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"commonWireVersion":null}},"msg":"Error on connecting to mongodb","time":"2021-03-31T08:42:32.491Z","v":0}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! binance-trading-bot@0.0.64 start: `node dist/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the binance-trading-bot@0.0.64 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-31T08_42_35_384Z-debug.log

what should i do?

i am very new in docker. your installation guide is so complicated for me

i tried on windows local and centos dedicated server.
the problem is same.

**Comment by chrisleekr** [comment]
Hi @allaf2 

I won't teach you how to use Docker. Please find a lot of resources in Google.

Please close the issue if you resolve it.

**Comment by chrisleekr** [comment]
As I didn't hear anything from you, let me close the issue. 
If you have another issue, please open a new issue.
