### ISSUE TITLE
Sell Order when loss 

### ISSUE THREAD

**Issue by Obi49** [chrisleekr/binance-trading-bot#72]
Hello,

Is it possible, with actual available settings, to set an automatic sell when the current price comes lower than the last buy price ?

Thanks.

**Comment by chopeta** [comment]
It looks like a duplicate
Please check #66

**Comment by chrisleekr** [comment]
Hey @Obi49 

I can, but I would rather not add that feature as I prefer to wait until it recovers. 

You can still do it manually. :shrug:

**Comment by Obi49** [comment]
Ok thanks for the answer @chrisleekr
