### ISSUE TITLE
Can we add a wiki to the project? 

### ISSUE THREAD

**Issue by chopeta** [chrisleekr/binance-trading-bot#73]
Hi C, I was thinking about adding a wiki to the project here on github. What do you think? 

That could help reduce README size and organize things a little bit better for new users... Including a FAQ.

If you're OK with it, I could do it on my free time if you allow me to.

I would be more than glad to help.

**Comment by chrisleekr** [comment]
That is a pretty good idea.

I was thinking about what to do with a long README.md.

I opened Wiki to the public. 

Thanks for helping!

**Comment by chopeta** [comment]
Nice! 
Already added a few pages.
Still a working progress...
Will keep adding it in my free time.
