### ISSUE TITLE
Email notifications

### ISSUE THREAD

**Issue by ggloveswp** [chrisleekr/binance-trading-bot#79]
According to my specific requirements for trading in auto pilot, I would like to see the following specific feature implementation:

**_Email notifications for orders/sells._**

//

**Expected Behavior:**
- When an order or sell is placed, php mail() or alternative should be fired and email the person in charge for auditing the specific coin. This can be a global setting, or a specific individual coin one.

**Wireframe:**

![image](https://user-images.githubusercontent.com/18418930/113863712-a994b480-97b2-11eb-94b2-d93932106ade.png)

**Alternatives:**

- Push notifications for the same actions, through PushBullet API: https://docs.pushbullet.com/ and/or Pushover API: https://pushover.net/api

**Comment by chrisleekr** [comment]
Good suggestion, but why would you want an email for any action?

And pushbullet has API limit for free account
```
Push limit
Free accounts (without a Pro subscription) are limited to 500 pushes per month. Going over will result in an error when sending a Push
```

If you use Slack, which is free, then you can get notifications without limit (ok, there is a limit but you would keep the latest message anyway.)

**Comment by ggloveswp** [comment]
Well, thats a service-agnostic request. 
If slack works best for the purpose, lets go for it.

**Comment by chrisleekr** [comment]
:) I think Slack works ok for now and I don't want to make the bot feature creep. 

I do appreciate your suggestion. :+1:

**Comment by ggloveswp** [comment]
An alternative already exists: Slack
