### ISSUE TITLE
Slack configuration

### ISSUE THREAD

**Issue by ggloveswp** [chrisleekr/binance-trading-bot#80]
Based on this readme file's sentence: When launching the application, it will notify public URL to the Slack.
Im expecting the Slack bot to drop a line in the channel, once bot is restarted.

Is my assumption a wrong one?
This is not happening for me, while at the same time, using curl, I was able to send out messags to the channel, which means my webhooks are working.

Grepping logs for *slack*, returns nothing.

My config syntax values (.env) regarding Slack, are as follows (I spooed the id of the channel - just to showcase the format and make sure that is the correct one):

```
## Slack
BINANCE_SLACK_WEBHOOK_URL=https://hooks.slack.com/services/T01TEVPF/B01TV2A/8LajzeAP4K79iGZi4D
BINANCE_SLACK_CHANNEL="#general"
BINANCE_SLACK_USERNAME=bot
```

Please advise.

**Comment by chrisleekr** [comment]
FYI, remove your slack address as anyone can send message

**Comment by ggloveswp** [comment]
I've spoofed it by removing characters from the original URL.

**Comment by chrisleekr** [comment]
I just tested your slack webhook url.
```
curl -X POST -H 'Content-type: application/json' --data '{"text":"Hello, World!"}' https://hooks.slack.com/services/T01TEVPF/B01TV2A/8LajzeAP4K79iGZi4D                             
no_team⏎                         
```

Error `no_team`  https://api.slack.com/messaging/webhooks#:~:text=no_team%20means%20the%20Slack%20workspace,was%20either%20invalid%20or%20missing.
```
no_team means the Slack workspace was either missing or invalid.
```

**Comment by chrisleekr** [comment]
> I've spoofed it by removing characters from the original URL.

Oh good well done.

Try to test with 
```
curl -X POST -H 'Content-type: application/json' --data '{"text":"Hello, World!"}' <Webhook URL>                             

```

**Comment by chrisleekr** [comment]
And if the public URL is the same, then the bot won't send you a message as it assumes already notified.

Try to change the public URL and restart it.

**Comment by ggloveswp** [comment]
That happens because I removed characters from the URL, in order to post it here publicly.

Here are my tests:

![image](https://user-images.githubusercontent.com/18418930/113870291-59215500-97ba-11eb-81ae-169ec031f2c1.png)


![image](https://user-images.githubusercontent.com/18418930/113870433-81a94f00-97ba-11eb-8dae-6d33c79ca88d.png)

**Comment by ggloveswp** [comment]
Changed workspace URL didnt help. No other messages except my curl post arrive at the channel.

**Comment by chrisleekr** [comment]
Is it possible slack configuration disabled?

By default, it is disabled - https://github.com/chrisleekr/binance-trading-bot/blob/master/config/default.json#L25

```
"slack": {
    "enabled": {
     "__name": "BINANCE_SLACK_ENABLED",
      "__format": "boolean"
    },
    "webhookUrl": "BINANCE_SLACK_WEBHOOK_URL",
    "channel": "BINANCE_SLACK_CHANNEL",
    "username": "BINANCE_SLACK_USERNAME"
  },
```

Try to add the below configuration into the docker compose file.

`BINANCE_SLACK_ENABLED=true`

**Comment by ggloveswp** [comment]
Seems on: 

![image](https://user-images.githubusercontent.com/18418930/113871444-963a1700-97bb-11eb-9d6f-a925b2f3b737.png)

**Comment by chrisleekr** [comment]
Ok let's do hardcore way.

```bash
$ docker exec -it binance-bot /bin/ash                                                                                                                                            
/srv # node ./app/scripts/slack-test.js 
```

Check the log message whether it throws any notable error.

**Comment by ggloveswp** [comment]
Hmm..

Looks that it ignores my config: 

`{"name":"binance-api","version":"0.0.65","hostname":"XXXXXXXXXXX","pid":52,"level":30,"slackConfig":{**"enabled":false,"webhookUrl":"","channel":"","username":""**},"msg":"Slack config","time":"2021-04-07T13:19:35.348Z","v":0}
`

**Comment by chrisleekr** [comment]
Errr.... when you set below, which file did you put?
```
## Slack
BINANCE_SLACK_WEBHOOK_URL=https://hooks.slack.com/services/T01TEVPF/B01TV2A/8LajzeAP4K79iGZi4D
BINANCE_SLACK_CHANNEL="#general"
BINANCE_SLACK_USERNAME=bot
```

**Comment by ggloveswp** [comment]
In both .env and .env.dist 
I've now added them at config.json inside /config/ folder and restarted the bot - still no luck.

**Comment by ggloveswp** [comment]
Its now shown as enabled, however, no notifications are coming:

```
root@binancebot:~/binance-trading-bot# docker exec -it binance-bot /bin/ash
/srv # node ./app/scripts/slack-test.js
{"name":"binance-api","version":"0.0.65","hostname":"26300d5eda08","pid":52,"level":30,"msg":"API logger loaded","time":"2021-04-07T13:26:54.628Z","v":0}
{"name":"binance-api","version":"0.0.65","hostname":"26300d5eda08","pid":52,"level":30,"slackConfig":{"enabled":true,"webhookUrl":"","channel":"","username":""},"msg":"Slack config","time":"2021-04-07T13:26:55.218Z","v":0}
(node:52) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'replace' of null
    at dispatchHttpRequest (/srv/node_modules/axios/lib/adapters/http.js:109:74)
    at new Promise (<anonymous>)
    at httpAdapter (/srv/node_modules/axios/lib/adapters/http.js:46:10)
    at dispatchRequest (/srv/node_modules/axios/lib/core/dispatchRequest.js:52:10)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /srv/app/scripts/slack-test.js:10:18
(Use `node --trace-warnings ...` to show where the warning was created)
(node:52) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:52) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by chrisleekr** [comment]
Doesn't make any sense. Something must be misconfigured. 

```"webhookUrl":"","channel":"","username":""```

Webhook URL and other configurations are not configured correctly.

You don't need to put in `.env.dist` as it is just a skeleton environment parameter.
You don't need to put in `config.json` as it will be overridden by the environment parameter defined in [custom-environment-variables.json](https://github.com/chrisleekr/binance-trading-bot/blob/master/config/custom-environment-variables.json)

Assuming you are using `docker-compose.server.yml` file as instructed, 

https://github.com/chrisleekr/binance-trading-bot/blob/master/docker-compose.server.yml#L12

Is there duplicated environment parameter specified under binance-bot environment section?

**Comment by ggloveswp** [comment]
I've reverted both .env.dist and default.json inside /config/ folder (previously mentioned wrongly as config.json).

Im not using docker-compose.server.yml (Im not really sure how to change the monitoring yml file in the app) - but I've edited docker-compose.yml , placing the contents of docker-compose.server.yml in it.

**Comment by ggloveswp** [comment]
After the last modifications, the error dissappeared, however, values are still blank:

`/srv # node ./app/scripts/slack-test.js
{"name":"binance-api","version":"0.0.65","hostname":"26300d5eda08","pid":52,"level":30,"msg":"API logger loaded","time":"2021-04-07T13:35:32.700Z","v":0}
{"name":"binance-api","version":"0.0.65","hostname":"26300d5eda08","pid":52,"level":30,"slackConfig":{"enabled":false,"webhookUrl":"","channel":"","username":""},"msg":"Slack config","time":"2021-04-07T13:35:32.966Z","v":0}
{"name":"binance-api","version":"0.0.65","hostname":"26300d5eda08","pid":52,"level":30,"result":{},"msg":"Slack result","time":"2021-04-07T13:35:32.975Z","v":0}
/srv #
`

**Comment by ggloveswp** [comment]
Seems that enabled:false is coming from changes applied in default.json inside config folder.

**Comment by chrisleekr** [comment]
Let's start from scratch.

Write down all the configuration and last buy price in case you lose the data.

You don't need to replace `docker-compose.yml` from `docker-compose.server.yml`
Just simply use `docker-compose.server.yml`

Make sure you already edited correctly `.env` 

```
# shutdown current docker-compose.yml
$ docker-compose down

# Launch new docker-compose.server.yml
$ docker-compose -f docker-compose.server.yml pull
$ docker-compose -f docker-compose.server.yml up -d
```

**Comment by ggloveswp** [comment]
Seems working now.

Bot added this message (not the public URL): 
![image](https://user-images.githubusercontent.com/18418930/113876673-a0124900-97c0-11eb-97c2-33dc71c434dc.png)

and log reports correct values:
![image](https://user-images.githubusercontent.com/18418930/113876732-b0c2bf00-97c0-11eb-879a-d8829f696123.png)

Is this the normal behavior?

**Comment by chrisleekr** [comment]
Good. 

Try to change `BINANCE_LOCAL_TUNNEL_SUBDOMAIN` to something else and then

```
$ docker restart binance-bot
```

Then it should send new public URL to the slack.

**Comment by ggloveswp** [comment]
My bot runs under no hostname, but IP. Should I leave it to default?
I do not really care about the public IP there, but only about receiving action notifications (orders/sells).

**Comment by chrisleekr** [comment]
If you don't need any public access, then no need to set the local tunnel. 
Because you mentioned `Based on this readme file's sentence: When launching the application, it will notify public URL to the Slack.` , I would expect you to use the local tunnel.

If you don't need it, just disable the local tunnel.

Hostname/IP all doesn't matter as a local tunnel would take care of it.

If you set it as `default`, then every time there is a restart, then it will change the public URL address.
Just simply set a random subdomain, which no one can guess, then it would be ok.

In the mobile browser, you can add to home which can use as the mobile Webapp.

**Comment by ggloveswp** [comment]
Thank you for your amazingly detailed replies, prompt support and willing to help.
Appreciated.

**Comment by chrisleekr** [comment]
No worries. I just had free time. Just one of good timing.
