### ISSUE TITLE
How to build the project

### ISSUE THREAD

**Issue by santoshbmath** [chrisleekr/binance-trading-bot#81]
Hi,

I want to make some changes in UI and I made changes to SettingIcon.js. How to build it and deploy the latest changes? It will be good if you provide the development steps in README.md.

Thanks,
Santosh

**Comment by santoshbmath** [comment]
BTW, after making changes, i tried pull and up but my changes are not visible. I am missing something.

**Comment by chrisleekr** [comment]
Hey @santoshbmath 

That is a good idea, I will update README.md later for the development process.

To test your code, here is what I do,

```
$ docker-compose up -d --build
```

As I use `nodemon`, any server-side code change will be automatically reflected in the bot.
However, for the frontend UI, after you change the code, you need to refresh the browser to see the changes.

Let me know if you have any trouble.
