### ISSUE TITLE
Execution failed Code: EAI_AGAIN

### ISSUE THREAD

**Issue by ggloveswp** [chrisleekr/binance-trading-bot#83]
This message came from the slack bot. Is this something related to binance's API or the bot iself? 

![image](https://user-images.githubusercontent.com/18418930/114000267-81b15980-9863-11eb-9d7f-f84eef717ba9.png)

**Comment by chrisleekr** [comment]
This is not a bug.

It literally means that your network caused the issue to contact api.binance.com

**Comment by ggloveswp** [comment]
Thanks for explaining.
