### ISSUE TITLE
Settings UI Improvements

### ISSUE THREAD

**Issue by santoshbmath** [chrisleekr/binance-trading-bot#85]
### Is your proposal related to a problem?
Settings modal is too big, which is not as per UI standards. Here are few issues,
1. Modal is too big.
2. To save or close, user has to scroll down the modal.
3. No default action (Close or Save changes)
4. No Close button at the title bar.
5. Most of the time user open settings to add/remove symbols rest all settings are not often changed. Even if a new symbol is added/removed, user has to scroll down to save the changes.

### Describe the solution you'd like
Here's my proposal,

1. Group the different sections using accordions.
2. Open first accordion by default.
2. Make two column rows.
3. Have help icon and move all help text as tooltip.
4. Default button selected is "Save"

![settings](https://user-images.githubusercontent.com/3702899/114167698-e7c5db80-994c-11eb-81d4-b5abceb951bc.png)

### Describe alternatives you've considered
Alternative option is to have two options, settings and symbols. Move everything other than symbols and fiats into settings.

**Comment by chrisleekr** [comment]
This is a really good suggestion. 

I will change accordingly.

Just one issue is, I am still testing #77, which had massive refactoring. 
Once I am confident with that PR, then I will work on this. 

Thanks @santoshbmath

**Comment by chopeta** [comment]
This is a really professional and good looking wireframe @santoshbmath 

It's nice to see people contributing in such a way.

I really like this proposal for the Global Settings page, it's much better, I had problems more than once when scrolling over the page with the mouse my numbers get changed by the scrolling wheel without me noticing it.

Let's get #77 tested and merged so @chrisleekr can move forward with new code.

**Comment by santoshbmath** [comment]
@chopeta @chrisleekr glad that you liked the wireframe. :)

**Comment by chrisleekr** [comment]
@santoshbmath I have updated the settings UI in PR #77. This change will be merged later.

![image](https://user-images.githubusercontent.com/5715919/115626445-da432500-a340-11eb-96c2-10a8c9ee802a.png)
