### ISSUE TITLE
Bot don't start on Raspberry Pi

### ISSUE THREAD

**Issue by 4KJuegos** [chrisleekr/binance-trading-bot#87]
Now, the bot doesn't works on Raspberry, mongo is restarting on docker.

![image](https://user-images.githubusercontent.com/51173839/114199039-3d51b680-9954-11eb-9af7-88ed4c4d615c.png)

**Comment by 4KJuegos** [comment]
Now, I can't build for Raspberry. This says the version of compose file is unsupoorted... I reinstalled all the SO.

**Comment by chrisleekr** [comment]
First, get the log from binance-mongo 

```
docker logs binance-mongo
```

Have you installed RPi 32bit or Ubuntu 64bit? The docker-compose.rpi.yml is for RPi 32bit. You can do with Ubuntu 64bit if you modify mongo image.

If it is saying unsupported, then you must have wrong docker-compose version.
This is what I am using

```
pi@raspberrypi:~ $ docker -v
Docker version 20.10.3, build 48d30b5
pi@raspberrypi:~ $ docker-compose -v
docker-compose version 1.28.2, build unknown
```

**Comment by 4KJuegos** [comment]
It seems that works with the OS reinstalled. May be the update of raspbian broke something. I close the ticket. Thanks!!
