### ISSUE TITLE
New to front-end and JS

### ISSUE THREAD

**Issue by MathGuiMach** [chrisleekr/binance-trading-bot#89]
How can I open this project in my machine? Which IDE's should I use? I managed to pull it on docker, but I wanted to see how it works from inside!

**Comment by chrisleekr** [comment]
@MathGuiMach 

I use vscode and this project is optimised to use by it.

**Comment by chopeta** [comment]
@chrisleekr I know you're busy... but when you have a chance try to document something about this on the wiki... I've created a link for called "Developers Corner"... I think this would help other devs to join the project and send their PRs with possible bug fixes, improvements and new features.

**Comment by dmitriy-sokolyanskiy** [comment]
@chrisleekr could you explain how it's possible to require files from the directory in this way:
`const { logger, mongo } = require('./helpers');`
I've got an error because of it. When I rewrite on 
`const logger = require('./helpers/logger');`
it works

**Comment by chrisleekr** [comment]
@chopeta 
Yeah, definitely. When I get time, I will add some.

**Comment by chrisleekr** [comment]
Hey @dmitriy-sokolyanskiy 

That is super weird. 
In the `helpers` folder, there is a file called `index.js` which exports all the helpers.
That way, this `const { logger, mongo } = require('./helpers');` is possible.

It is built under node 14 latest, so it shouldn't have any issue.

**Comment by MathGuiMach** [comment]
> @MathGuiMach
> 
> I use vscode and this project is optimised to use by it.

I see. Do you have a list of plugins? I'll try figuring out by myself, but it would help;

**Comment by chrisleekr** [comment]
@MathGuiMach 
It should already recommend plugins that I use for the project.

https://github.com/chrisleekr/binance-trading-bot/blob/master/.vscode/extensions.json
