### ISSUE TITLE
Erro toFixed() in coin wrappers scripts

### ISSUE THREAD

**Issue by Lavyk** [chrisleekr/binance-trading-bot#90]
## Description

When I add symbols that involve the FIAT BRL the following error appears in several files that contain _toFixed(precision)_:

**_"Uncaught RangeError: toFixed() digits argument must be between 0 and 100."_**

Note that when we add the symbols, an _"precision"_ is -1

## To Reproduce

To produce the error, I just added the symbols BTCBRL, ETHBRL and BNBBRL.

## Solution found

The solution I found was to add "_Math.abs()_", for example:

`{(+baseAssetBalance.free).toFixed(Math.abs(precision))}`

I don't know if it interferes with anything, could someone help me in this correction?

## Additional context

Sorry my english, I'm using google translator.

**Comment by chrisleekr** [comment]
@Lavyk Thank you for reporting the bug.

I replicated, let me see what I can do.

**Comment by chrisleekr** [comment]
@Lavyk The issue has been resolved in the PR, which will be merged later. 
If you want to use BTCBRL, then please use this PR - https://github.com/chrisleekr/binance-trading-bot/pull/77

![image](https://user-images.githubusercontent.com/5715919/114298039-a58ccd80-9af7-11eb-814c-3758032964ac.png)
