### ISSUE TITLE
Not working on AWS EC2 

### ISSUE THREAD

**Issue by edebie** [chrisleekr/binance-trading-bot#91]
I tried to run the repo on an EC2 instance with Ubuntu OS but the web interface is stuck and showing the progress circle.
![image](https://user-images.githubusercontent.com/14147087/114288312-e9f57a80-9ab1-11eb-8fe7-722fd95ac028.png)

**Comment by halleybr** [comment]
me too...

**Comment by halleybr** [comment]
the problem is in the key and secret key of binance.


edit the .env and check if it is correct.

**Comment by edebie** [comment]
It runs perfectly on my windows machine with the same keys!

**Comment by chrisleekr** [comment]
@edebie please check your docker status.

```
$ docker ps -a
```
And if there is anything wrong with the container, check the log.

Refer this wiki page  - https://github.com/chrisleekr/binance-trading-bot/wiki/Troubleshooting#how-to-get-the-logs-by-installing-bunyan-npm-package

**Comment by edebie** [comment]
Thanks @chrisleekr 

The log was showing a wrong api key. I copied it again from binance account into e.nv file and recompiled it and it is working now!
