### ISSUE TITLE
Data look wrong

### ISSUE THREAD

**Issue by niyazikeklik** [chrisleekr/binance-trading-bot#95]
I tried the bot on my Binance test api account today, but I guess I did something wrong.

For example, the current price of BTC / USDT looks like this on the bot.

![image](https://user-images.githubusercontent.com/27292457/114463093-a3f10180-9bec-11eb-82c7-5deefdde81c1.png)

The current BTC / USDT chart is like this:

![image](https://user-images.githubusercontent.com/27292457/114463331-f7fbe600-9bec-11eb-9708-c28ea38309a4.png)

My settings:
![image](https://user-images.githubusercontent.com/27292457/114463503-2e396580-9bed-11eb-89ab-78f4944f37a1.png)

**Comment by chrisleekr** [comment]
> I tried the bot on my Binance test api account today, but I guess I did something wrong.

Errr, so you are using test API account, right? Test and live servers have different price.

**Comment by niyazikeklik** [comment]
> > Botu bugün Binance test api hesabımda denedim, ancak sanırım yanlış bir şey yaptım.
> 
> Hata, test API hesabı kullanıyorsunuz, değil mi? Test ve canlı sunucuların fiyatı farklıdır.

Yes I am using test api. It is thought-provoking why Binance needed such a difference. Is the rate of price change also different? So for example, when BTC / USDT rises 3%, does the test api rise 3%?

**Comment by chrisleekr** [comment]
@niyazikeklik 
Nope, both are a completely different market. I also felt annoyed by that. 
If you watch the price in the test server, there is not much price movement, which makes it hard to test.
If no one buys from the test server, then the price is not moving at all.

**Comment by niyazikeklik** [comment]
> @niyazikeklik
> Hayır, her ikisi de tamamen farklı bir pazar. Bundan da rahatsız oldum.
> Test sunucusunda fiyatı izlerseniz, çok fazla fiyat hareketi yoktur, bu da test etmeyi zorlaştırır.
> Kimse test sunucusundan satın almazsa, fiyat hiç hareket etmiyor demektir.

This is really annoying.
Well, do you have any suggestions to try the bot at original prices risk-free?

**Comment by chrisleekr** [comment]
@niyazikeklik 
Nope, I myself also uses real money to test. 
And just note that Binance will not accept less than $10 worth of the coin for the order.
The bot is also removing the last buy price if the coin is worth less than $10.

**Comment by niyazikeklik** [comment]
Opening a second binance account for testing seems to be the most logical solution. Thank you for everything.

> @niyazikeklik
> Hayır, ben de test etmek için gerçek para kullanıyorum.
> Ve binance'in sipariş için 10 dolardan daha az para kabul etmeyeceğine dikkat edin.
> Bot, madeni paranın değeri 10 dolardan azsa son satın alma fiyatını da kaldırıyor.

Opening a second binance account for testing seems to be the most logical solution. Thank you for everything.

**Comment by chrisleekr** [comment]
Please close the issue if your question is answered.
