### ISSUE TITLE
Binance Delisting WAPI Endpoints

### ISSUE THREAD

**Issue by chopeta** [chrisleekr/binance-trading-bot#96]
Just checking if this is something that would affect the bot....

[Notice to API Users on Delisting WAPI Endpoints](https://www.binance.com/en/support/announcement/f45dde7da58b473aa885349946bed269)

If not, you can just close the issue.

**Comment by chrisleekr** [comment]
Thanks @chopeta 

As we are not using any wapi or sapi, we should be oki.
